# cMAB Simulation

This notebook shows a simulation framework for the contextual multi-armed bandit (cMAB). It allows to study the behaviour of the bandit algoritm, to evaluate results and to run experiments on simulated data under different context, reward and action settings.

In [1]:
from sklearn.datasets import make_classification

from pybandits.cmab import CmabBernoulli
from pybandits.cmab_simulator import CmabSimulator
from pybandits.model import BayesianLogisticRegression, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

First we need to define the simulation parameters. The parameters are split into two parts. The general parameters contain:
- Number of update rounds
- Number of samples per batch of update round
- Seed for reproducibility
- Verbosity enabler
- Visualization enabler

The problem definition parameters contain:
- Number of groups
- Number of features

Data are processed in batches of size n>=1. Per each batch of simulated samples, the cMAB selects one action and collects the corresponding simulated reward for each sample. Then, prior parameters are updated based on returned rewards from recommended actions.

In [2]:
# general simulator parameters
n_updates = 10
batch_size = 100
random_seed = None
verbose = True
visualize = True

In [3]:
# problem definition simulation parameters
n_groups = 3
n_features = 5

Next, we initialize the context matrix $X$ and the groups of samples. Samples that belong to the same group have features that come from the same distribution.
Then, the action model and the cMAB are defined. We define three actions, each with a Bayesian Logistic Regression model. The model is defined by a Student-T prior for the intercept and a Student-T prior for each feature coefficient.

In [4]:
# init context matrix and groups

context, group = make_classification(
    n_samples=batch_size * n_updates, n_features=n_features, n_informative=n_features, n_redundant=0, n_classes=n_groups
)
group = [str(g) for g in group]

In [5]:
# define action model


def create_blr(n_features, bias_mu, bias_sigma, update_method, update_kwargs):
    """Create a BayesianLogisticRegression with given parameters."""
    bias = StudentTArray.cold_start(mu=bias_mu, sigma=bias_sigma, shape=1)
    weight = StudentTArray.cold_start(shape=(n_features, 1))
    layer_params = BnnLayerParams(weight=weight, bias=bias)
    model_params = BnnParams(bnn_layer_params=[layer_params])
    feature_config = FeaturesConfig(n_features=n_features)
    return BayesianLogisticRegression(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    )


update_method = "VI"
update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}
blr_kwargs = dict(
    n_features=n_features, bias_mu=1, bias_sigma=2, update_method=update_method, update_kwargs=update_kwargs
)
actions = {
    "a1": create_blr(**blr_kwargs),
    "a2": create_blr(**blr_kwargs),
    "a3": create_blr(**blr_kwargs),
}
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

Finally, we need to define the probabilities of positive rewards per each action/group, i.e. the ground truth ('Action A': 0.8 for group '0' means that if the bandits selects 'Action A' for samples that belong to group '0', then the environment will return a positive reward with 80% probability).

In [6]:
# init probability of rewards randomly using splines
probs_reward = None

Now, we initialize the cMAB as shown in the previous notebook and the CmabSimulator with the parameters set above.

In [7]:
# init simulation
cmab_simulator = CmabSimulator(
    mab=cmab,
    group=group,
    batch_size=batch_size,
    n_updates=n_updates,
    probs_reward=probs_reward,
    context=context,
    verbose=verbose,
)

Now, we can start simulation process by executing run() which performs the following steps:
```
For i=0 to n_updates:
    Extract batch[i] of samples from X
    Model recommends the best actions as the action with the highest reward probability to each simulated sample in batch[i] and collect corresponding simulated rewards
    Model priors are updated using information from recommended actions and returned rewards
```
Finally, we can visualize the results of the simulation. As defined in the ground truth: 'a2' was the action recommended the most for samples that belong to group '0', 'a1' to group '1' and both 'a1' and 'a3' to group '2'.

In [8]:
cmab_simulator.run()

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self._results = pd.concat((self._results, batch_results), ignore_index=True)

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 36. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:59,  1.67it/s]

SVI:   1%|          | 1/100 [00:00<00:59,  1.67it/s, loss=247.4976]

SVI:   2%|▏         | 2/100 [00:00<00:58,  1.67it/s, loss=242.2338]

SVI:   3%|▎         | 3/100 [00:00<00:57,  1.67it/s, loss=245.3052]

SVI:   4%|▍         | 4/100 [00:00<00:57,  1.67it/s, loss=244.2849]

SVI:   5%|▌         | 5/100 [00:00<00:56,  1.67it/s, loss=245.7636]

SVI:   6%|▌         | 6/100 [00:00<00:56,  1.67it/s, loss=245.4944]

SVI:   7%|▋         | 7/100 [00:00<00:55,  1.67it/s, loss=244.9404]

SVI:   8%|▊         | 8/100 [00:00<00:54,  1.67it/s, loss=246.8542]

SVI:   9%|▉         | 9/100 [00:00<00:54,  1.67it/s, loss=242.8750]

SVI:  10%|█         | 10/100 [00:00<00:53,  1.67it/s, loss=238.9330]

SVI:  11%|█         | 11/100 [00:00<00:53,  1.67it/s, loss=241.0053]

SVI:  12%|█▏        | 12/100 [00:00<00:52,  1.67it/s, loss=236.9375]

SVI:  13%|█▎        | 13/100 [00:00<00:51,  1.67it/s, loss=233.6846]

SVI:  14%|█▍        | 14/100 [00:00<00:51,  1.67it/s, loss=242.8912]

SVI:  15%|█▌        | 15/100 [00:00<00:50,  1.67it/s, loss=238.9079]

SVI:  16%|█▌        | 16/100 [00:00<00:50,  1.67it/s, loss=241.0305]

SVI:  17%|█▋        | 17/100 [00:00<00:49,  1.67it/s, loss=241.0259]

SVI:  18%|█▊        | 18/100 [00:00<00:48,  1.67it/s, loss=239.2437]

SVI:  19%|█▉        | 19/100 [00:00<00:48,  1.67it/s, loss=237.6475]

SVI:  20%|██        | 20/100 [00:00<00:47,  1.67it/s, loss=240.3416]

SVI:  21%|██        | 21/100 [00:00<00:47,  1.67it/s, loss=240.5259]

SVI:  22%|██▏       | 22/100 [00:00<00:46,  1.67it/s, loss=236.4106]

SVI:  23%|██▎       | 23/100 [00:00<00:45,  1.67it/s, loss=235.7275]

SVI:  24%|██▍       | 24/100 [00:00<00:45,  1.67it/s, loss=235.6274]

SVI:  25%|██▌       | 25/100 [00:00<00:44,  1.67it/s, loss=237.7204]

SVI:  26%|██▌       | 26/100 [00:00<00:44,  1.67it/s, loss=239.1294]

SVI:  27%|██▋       | 27/100 [00:00<00:43,  1.67it/s, loss=233.8359]

SVI:  28%|██▊       | 28/100 [00:00<00:42,  1.67it/s, loss=234.7050]

SVI:  29%|██▉       | 29/100 [00:00<00:42,  1.67it/s, loss=232.0431]

SVI:  30%|███       | 30/100 [00:00<00:41,  1.67it/s, loss=236.0933]

SVI:  31%|███       | 31/100 [00:00<00:41,  1.67it/s, loss=236.8932]

SVI:  32%|███▏      | 32/100 [00:00<00:40,  1.67it/s, loss=235.9951]

SVI:  33%|███▎      | 33/100 [00:00<00:40,  1.67it/s, loss=234.1238]

SVI:  34%|███▍      | 34/100 [00:00<00:39,  1.67it/s, loss=230.0801]

SVI:  35%|███▌      | 35/100 [00:00<00:38,  1.67it/s, loss=231.4424]

SVI:  36%|███▌      | 36/100 [00:00<00:38,  1.67it/s, loss=234.8074]

SVI:  37%|███▋      | 37/100 [00:00<00:37,  1.67it/s, loss=231.1354]

SVI:  38%|███▊      | 38/100 [00:00<00:37,  1.67it/s, loss=233.3513]

SVI:  39%|███▉      | 39/100 [00:00<00:36,  1.67it/s, loss=234.3567]

SVI:  40%|████      | 40/100 [00:00<00:35,  1.67it/s, loss=227.8450]

SVI:  41%|████      | 41/100 [00:00<00:35,  1.67it/s, loss=231.9175]

SVI:  42%|████▏     | 42/100 [00:00<00:34,  1.67it/s, loss=232.2642]

SVI:  43%|████▎     | 43/100 [00:00<00:34,  1.67it/s, loss=228.2583]

SVI:  44%|████▍     | 44/100 [00:00<00:33,  1.67it/s, loss=232.9290]

SVI:  45%|████▌     | 45/100 [00:00<00:32,  1.67it/s, loss=228.9297]

SVI:  46%|████▌     | 46/100 [00:00<00:32,  1.67it/s, loss=229.1138]

SVI:  47%|████▋     | 47/100 [00:00<00:31,  1.67it/s, loss=227.5773]

SVI:  48%|████▊     | 48/100 [00:00<00:31,  1.67it/s, loss=225.0436]

SVI:  49%|████▉     | 49/100 [00:00<00:30,  1.67it/s, loss=220.0432]

SVI:  50%|█████     | 50/100 [00:00<00:29,  1.67it/s, loss=224.8066]

SVI:  51%|█████     | 51/100 [00:00<00:29,  1.67it/s, loss=226.8304]

SVI:  52%|█████▏    | 52/100 [00:00<00:28,  1.67it/s, loss=224.3020]

SVI:  53%|█████▎    | 53/100 [00:00<00:28,  1.67it/s, loss=227.5898]

SVI:  54%|█████▍    | 54/100 [00:00<00:27,  1.67it/s, loss=222.3127]

SVI:  55%|█████▌    | 55/100 [00:00<00:26,  1.67it/s, loss=221.9318]

SVI:  56%|█████▌    | 56/100 [00:00<00:26,  1.67it/s, loss=226.6886]

SVI:  57%|█████▋    | 57/100 [00:00<00:25,  1.67it/s, loss=225.0341]

SVI:  58%|█████▊    | 58/100 [00:00<00:25,  1.67it/s, loss=227.2111]

SVI:  59%|█████▉    | 59/100 [00:00<00:24,  1.67it/s, loss=214.6905]

SVI:  60%|██████    | 60/100 [00:00<00:23,  1.67it/s, loss=222.6131]

SVI:  61%|██████    | 61/100 [00:00<00:23,  1.67it/s, loss=218.7412]

SVI:  62%|██████▏   | 62/100 [00:00<00:22,  1.67it/s, loss=219.6961]

SVI:  63%|██████▎   | 63/100 [00:00<00:22,  1.67it/s, loss=221.0357]

SVI:  64%|██████▍   | 64/100 [00:00<00:21,  1.67it/s, loss=223.4033]

SVI:  65%|██████▌   | 65/100 [00:00<00:20,  1.67it/s, loss=213.0545]

SVI:  66%|██████▌   | 66/100 [00:00<00:20,  1.67it/s, loss=217.6602]

SVI:  67%|██████▋   | 67/100 [00:00<00:19,  1.67it/s, loss=218.1713]

SVI:  68%|██████▊   | 68/100 [00:00<00:19,  1.67it/s, loss=221.4367]

SVI:  69%|██████▉   | 69/100 [00:00<00:18,  1.67it/s, loss=219.3035]

SVI:  70%|███████   | 70/100 [00:00<00:17,  1.67it/s, loss=217.8992]

SVI:  71%|███████   | 71/100 [00:00<00:17,  1.67it/s, loss=221.3631]

SVI:  72%|███████▏  | 72/100 [00:00<00:16,  1.67it/s, loss=218.3982]

SVI:  73%|███████▎  | 73/100 [00:00<00:16,  1.67it/s, loss=216.1985]

SVI:  74%|███████▍  | 74/100 [00:00<00:15,  1.67it/s, loss=220.6233]

SVI:  75%|███████▌  | 75/100 [00:00<00:14,  1.67it/s, loss=218.6023]

SVI:  76%|███████▌  | 76/100 [00:00<00:14,  1.67it/s, loss=211.1320]

SVI:  77%|███████▋  | 77/100 [00:00<00:13,  1.67it/s, loss=210.0532]

SVI:  78%|███████▊  | 78/100 [00:00<00:13,  1.67it/s, loss=207.8875]

SVI:  79%|███████▉  | 79/100 [00:00<00:12,  1.67it/s, loss=218.6705]

SVI:  80%|████████  | 80/100 [00:00<00:11,  1.67it/s, loss=214.8865]

SVI:  81%|████████  | 81/100 [00:00<00:11,  1.67it/s, loss=214.9940]

SVI:  82%|████████▏ | 82/100 [00:00<00:10,  1.67it/s, loss=208.3190]

SVI:  83%|████████▎ | 83/100 [00:00<00:10,  1.67it/s, loss=212.6216]

SVI:  84%|████████▍ | 84/100 [00:00<00:09,  1.67it/s, loss=216.0854]

SVI:  85%|████████▌ | 85/100 [00:00<00:08,  1.67it/s, loss=210.9861]

SVI:  86%|████████▌ | 86/100 [00:00<00:08,  1.67it/s, loss=210.6960]

SVI:  87%|████████▋ | 87/100 [00:00<00:07,  1.67it/s, loss=203.9987]

SVI:  88%|████████▊ | 88/100 [00:00<00:07,  1.67it/s, loss=210.5253]

SVI:  89%|████████▉ | 89/100 [00:00<00:06,  1.67it/s, loss=213.9740]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.67it/s, loss=209.4713]

SVI:  91%|█████████ | 91/100 [00:00<00:05,  1.67it/s, loss=205.0672]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.67it/s, loss=206.0632]

SVI:  93%|█████████▎| 93/100 [00:00<00:04,  1.67it/s, loss=203.6894]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.67it/s, loss=208.7389]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.67it/s, loss=206.9037]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.67it/s, loss=211.2049]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.67it/s, loss=203.8194]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.67it/s, loss=207.0023]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.67it/s, loss=208.3421]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.67it/s, loss=208.2062]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 30. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.95it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.95it/s, loss=121.6406]

SVI:   2%|▏         | 2/100 [00:00<00:50,  1.95it/s, loss=125.5379]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.95it/s, loss=122.5505]

SVI:   4%|▍         | 4/100 [00:00<00:49,  1.95it/s, loss=124.1992]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.95it/s, loss=125.1322]

SVI:   6%|▌         | 6/100 [00:00<00:48,  1.95it/s, loss=124.8566]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.95it/s, loss=120.2886]

SVI:   8%|▊         | 8/100 [00:00<00:47,  1.95it/s, loss=120.1237]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.95it/s, loss=118.6385]

SVI:  10%|█         | 10/100 [00:00<00:46,  1.95it/s, loss=121.0319]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.95it/s, loss=118.8473]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.95it/s, loss=120.9109]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.95it/s, loss=119.8283]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.95it/s, loss=118.8625]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.95it/s, loss=120.0248]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.95it/s, loss=119.2335]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.95it/s, loss=116.3482]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.95it/s, loss=119.2143]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.95it/s, loss=118.6602]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.95it/s, loss=115.8944]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.95it/s, loss=119.1778]

SVI:  22%|██▏       | 22/100 [00:00<00:40,  1.95it/s, loss=116.1474]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.95it/s, loss=116.8973]

SVI:  24%|██▍       | 24/100 [00:00<00:39,  1.95it/s, loss=118.9908]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.95it/s, loss=118.0104]

SVI:  26%|██▌       | 26/100 [00:00<00:38,  1.95it/s, loss=117.0691]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.95it/s, loss=116.0252]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.95it/s, loss=115.3522]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.95it/s, loss=116.5311]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.95it/s, loss=113.1722]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.95it/s, loss=113.3058]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.95it/s, loss=114.6856]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.95it/s, loss=115.5657]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.95it/s, loss=108.8188]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.95it/s, loss=115.1200]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.95it/s, loss=111.6502]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.95it/s, loss=111.2354]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.95it/s, loss=113.8785]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.95it/s, loss=114.1287]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.95it/s, loss=111.5703]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.95it/s, loss=114.0607]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.95it/s, loss=110.3874]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.95it/s, loss=114.1973]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.95it/s, loss=111.9734]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.95it/s, loss=113.3056]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.95it/s, loss=112.5654]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.95it/s, loss=110.5534]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.95it/s, loss=113.0236]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.95it/s, loss=111.8198]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.95it/s, loss=108.5838]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.95it/s, loss=108.4107]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.95it/s, loss=111.9865]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.95it/s, loss=110.1183]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.95it/s, loss=103.5376]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.95it/s, loss=108.8386]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.95it/s, loss=109.5880]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.95it/s, loss=108.8341]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.95it/s, loss=108.2231]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.95it/s, loss=110.4093]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.95it/s, loss=102.5589]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.95it/s, loss=108.6323]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.95it/s, loss=104.4487]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.95it/s, loss=108.3722]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.95it/s, loss=106.1737]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.95it/s, loss=109.4551]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.95it/s, loss=107.3935]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.95it/s, loss=110.1773]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.95it/s, loss=108.1436]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.95it/s, loss=106.9985]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.95it/s, loss=105.1603]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.95it/s, loss=107.8463]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.95it/s, loss=101.4159]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.95it/s, loss=105.9738]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.95it/s, loss=108.1872]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.95it/s, loss=105.6819]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.95it/s, loss=100.1253]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.95it/s, loss=105.3929]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.95it/s, loss=103.2150]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.95it/s, loss=103.1217]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.95it/s, loss=100.8610]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.95it/s, loss=103.7322]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.95it/s, loss=106.2977]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.95it/s, loss=101.4087]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.95it/s, loss=104.3555]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.95it/s, loss=97.1820]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.95it/s, loss=100.4682]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.95it/s, loss=100.9165]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.95it/s, loss=101.9035]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.95it/s, loss=104.6035]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.95it/s, loss=100.7541]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.95it/s, loss=104.6086]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.95it/s, loss=101.9983]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.95it/s, loss=92.7520]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.95it/s, loss=100.3994]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.95it/s, loss=102.0690]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.95it/s, loss=103.2705]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.95it/s, loss=103.1250]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.95it/s, loss=98.8766]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.95it/s, loss=100.7524]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.95it/s, loss=100.8751]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 34. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<01:06,  1.49it/s]

SVI:   1%|          | 1/100 [00:00<01:06,  1.49it/s, loss=266.4378]

SVI:   2%|▏         | 2/100 [00:00<01:05,  1.49it/s, loss=262.1736]

SVI:   3%|▎         | 3/100 [00:00<01:04,  1.49it/s, loss=266.2052]

SVI:   4%|▍         | 4/100 [00:00<01:04,  1.49it/s, loss=262.1401]

SVI:   5%|▌         | 5/100 [00:00<01:03,  1.49it/s, loss=265.7367]

SVI:   6%|▌         | 6/100 [00:00<01:02,  1.49it/s, loss=263.3440]

SVI:   7%|▋         | 7/100 [00:00<01:02,  1.49it/s, loss=266.2906]

SVI:   8%|▊         | 8/100 [00:00<01:01,  1.49it/s, loss=266.9232]

SVI:   9%|▉         | 9/100 [00:00<01:00,  1.49it/s, loss=262.7699]

SVI:  10%|█         | 10/100 [00:00<01:00,  1.49it/s, loss=262.9397]

SVI:  11%|█         | 11/100 [00:00<00:59,  1.49it/s, loss=262.0487]

SVI:  12%|█▏        | 12/100 [00:00<00:58,  1.49it/s, loss=255.7756]

SVI:  13%|█▎        | 13/100 [00:00<00:58,  1.49it/s, loss=263.9806]

SVI:  14%|█▍        | 14/100 [00:00<00:57,  1.49it/s, loss=263.0695]

SVI:  15%|█▌        | 15/100 [00:00<00:56,  1.49it/s, loss=261.9303]

SVI:  16%|█▌        | 16/100 [00:00<00:56,  1.49it/s, loss=262.5364]

SVI:  17%|█▋        | 17/100 [00:00<00:55,  1.49it/s, loss=263.1139]

SVI:  18%|█▊        | 18/100 [00:00<00:54,  1.49it/s, loss=262.1264]

SVI:  19%|█▉        | 19/100 [00:00<00:54,  1.49it/s, loss=259.7492]

SVI:  20%|██        | 20/100 [00:00<00:53,  1.49it/s, loss=261.3100]

SVI:  21%|██        | 21/100 [00:00<00:52,  1.49it/s, loss=260.4415]

SVI:  22%|██▏       | 22/100 [00:00<00:52,  1.49it/s, loss=261.3160]

SVI:  23%|██▎       | 23/100 [00:00<00:51,  1.49it/s, loss=260.2224]

SVI:  24%|██▍       | 24/100 [00:00<00:50,  1.49it/s, loss=256.2778]

SVI:  25%|██▌       | 25/100 [00:00<00:50,  1.49it/s, loss=256.3247]

SVI:  26%|██▌       | 26/100 [00:00<00:49,  1.49it/s, loss=259.7999]

SVI:  27%|██▋       | 27/100 [00:00<00:48,  1.49it/s, loss=257.7350]

SVI:  28%|██▊       | 28/100 [00:00<00:48,  1.49it/s, loss=258.1219]

SVI:  29%|██▉       | 29/100 [00:00<00:47,  1.49it/s, loss=255.4050]

SVI:  30%|███       | 30/100 [00:00<00:46,  1.49it/s, loss=260.4857]

SVI:  31%|███       | 31/100 [00:00<00:46,  1.49it/s, loss=258.2354]

SVI:  32%|███▏      | 32/100 [00:00<00:45,  1.49it/s, loss=260.0948]

SVI:  33%|███▎      | 33/100 [00:00<00:44,  1.49it/s, loss=255.6163]

SVI:  34%|███▍      | 34/100 [00:00<00:44,  1.49it/s, loss=246.6540]

SVI:  35%|███▌      | 35/100 [00:00<00:43,  1.49it/s, loss=256.0930]

SVI:  36%|███▌      | 36/100 [00:00<00:42,  1.49it/s, loss=252.0530]

SVI:  37%|███▋      | 37/100 [00:00<00:42,  1.49it/s, loss=253.6347]

SVI:  38%|███▊      | 38/100 [00:00<00:41,  1.49it/s, loss=249.9660]

SVI:  39%|███▉      | 39/100 [00:00<00:40,  1.49it/s, loss=248.9108]

SVI:  40%|████      | 40/100 [00:00<00:40,  1.49it/s, loss=255.2506]

SVI:  41%|████      | 41/100 [00:00<00:39,  1.49it/s, loss=254.6252]

SVI:  42%|████▏     | 42/100 [00:00<00:38,  1.49it/s, loss=254.0373]

SVI:  43%|████▎     | 43/100 [00:00<00:38,  1.49it/s, loss=252.9623]

SVI:  44%|████▍     | 44/100 [00:00<00:37,  1.49it/s, loss=253.6531]

SVI:  45%|████▌     | 45/100 [00:00<00:36,  1.49it/s, loss=247.6350]

SVI:  46%|████▌     | 46/100 [00:00<00:36,  1.49it/s, loss=251.8070]

SVI:  47%|████▋     | 47/100 [00:00<00:35,  1.49it/s, loss=250.5276]

SVI:  48%|████▊     | 48/100 [00:00<00:34,  1.49it/s, loss=245.0555]

SVI:  49%|████▉     | 49/100 [00:00<00:34,  1.49it/s, loss=245.2055]

SVI:  50%|█████     | 50/100 [00:00<00:33,  1.49it/s, loss=251.4416]

SVI:  51%|█████     | 51/100 [00:00<00:32,  1.49it/s, loss=244.1935]

SVI:  52%|█████▏    | 52/100 [00:00<00:32,  1.49it/s, loss=244.5256]

SVI:  53%|█████▎    | 53/100 [00:00<00:31,  1.49it/s, loss=237.6195]

SVI:  54%|█████▍    | 54/100 [00:00<00:30,  1.49it/s, loss=240.0550]

SVI:  55%|█████▌    | 55/100 [00:00<00:30,  1.49it/s, loss=246.4246]

SVI:  56%|█████▌    | 56/100 [00:00<00:29,  1.49it/s, loss=249.7725]

SVI:  57%|█████▋    | 57/100 [00:00<00:28,  1.49it/s, loss=248.2063]

SVI:  58%|█████▊    | 58/100 [00:00<00:28,  1.49it/s, loss=244.9696]

SVI:  59%|█████▉    | 59/100 [00:00<00:27,  1.49it/s, loss=239.7881]

SVI:  60%|██████    | 60/100 [00:00<00:26,  1.49it/s, loss=243.8151]

SVI:  61%|██████    | 61/100 [00:00<00:26,  1.49it/s, loss=243.3130]

SVI:  62%|██████▏   | 62/100 [00:00<00:25,  1.49it/s, loss=244.6216]

SVI:  63%|██████▎   | 63/100 [00:00<00:24,  1.49it/s, loss=245.2601]

SVI:  64%|██████▍   | 64/100 [00:00<00:24,  1.49it/s, loss=243.8996]

SVI:  65%|██████▌   | 65/100 [00:00<00:23,  1.49it/s, loss=242.3910]

SVI:  66%|██████▌   | 66/100 [00:00<00:22,  1.49it/s, loss=242.0476]

SVI:  67%|██████▋   | 67/100 [00:00<00:22,  1.49it/s, loss=242.3256]

SVI:  68%|██████▊   | 68/100 [00:00<00:21,  1.49it/s, loss=240.3161]

SVI:  69%|██████▉   | 69/100 [00:00<00:20,  1.49it/s, loss=241.9312]

SVI:  70%|███████   | 70/100 [00:00<00:20,  1.49it/s, loss=237.7486]

SVI:  71%|███████   | 71/100 [00:00<00:19,  1.49it/s, loss=241.1353]

SVI:  72%|███████▏  | 72/100 [00:00<00:18,  1.49it/s, loss=240.6739]

SVI:  73%|███████▎  | 73/100 [00:00<00:18,  1.49it/s, loss=244.3043]

SVI:  74%|███████▍  | 74/100 [00:00<00:17,  1.49it/s, loss=236.5597]

SVI:  75%|███████▌  | 75/100 [00:00<00:16,  1.49it/s, loss=239.7305]

SVI:  76%|███████▌  | 76/100 [00:00<00:16,  1.49it/s, loss=234.7385]

SVI:  77%|███████▋  | 77/100 [00:00<00:15,  1.49it/s, loss=240.0774]

SVI:  78%|███████▊  | 78/100 [00:00<00:14,  1.49it/s, loss=241.6810]

SVI:  79%|███████▉  | 79/100 [00:00<00:14,  1.49it/s, loss=238.5836]

SVI:  80%|████████  | 80/100 [00:00<00:13,  1.49it/s, loss=238.9817]

SVI:  81%|████████  | 81/100 [00:00<00:12,  1.49it/s, loss=231.1992]

SVI:  82%|████████▏ | 82/100 [00:00<00:12,  1.49it/s, loss=231.4524]

SVI:  83%|████████▎ | 83/100 [00:00<00:11,  1.49it/s, loss=240.6670]

SVI:  84%|████████▍ | 84/100 [00:00<00:10,  1.49it/s, loss=239.4355]

SVI:  85%|████████▌ | 85/100 [00:00<00:10,  1.49it/s, loss=235.1403]

SVI:  86%|████████▌ | 86/100 [00:00<00:09,  1.49it/s, loss=235.9968]

SVI:  87%|████████▋ | 87/100 [00:00<00:08,  1.49it/s, loss=236.9535]

SVI:  88%|████████▊ | 88/100 [00:00<00:08,  1.49it/s, loss=231.5092]

SVI:  89%|████████▉ | 89/100 [00:00<00:07,  1.49it/s, loss=225.8721]

SVI:  90%|█████████ | 90/100 [00:00<00:06,  1.49it/s, loss=238.2638]

SVI:  91%|█████████ | 91/100 [00:00<00:06,  1.49it/s, loss=235.7640]

SVI:  92%|█████████▏| 92/100 [00:00<00:05,  1.49it/s, loss=232.2363]

SVI:  93%|█████████▎| 93/100 [00:00<00:04,  1.49it/s, loss=231.0360]

SVI:  94%|█████████▍| 94/100 [00:00<00:04,  1.49it/s, loss=233.5284]

SVI:  95%|█████████▌| 95/100 [00:00<00:03,  1.49it/s, loss=230.9017]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.49it/s, loss=230.3505]

SVI:  97%|█████████▋| 97/100 [00:00<00:02,  1.49it/s, loss=233.3952]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.49it/s, loss=231.9242]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.49it/s, loss=229.6137]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.49it/s, loss=232.2384]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 19. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s, loss=46.6560]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.89it/s, loss=49.5139]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.89it/s, loss=47.2968]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.89it/s, loss=46.3091]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.89it/s, loss=47.5061]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.89it/s, loss=49.0471]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.89it/s, loss=47.5377]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.89it/s, loss=45.1053]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.89it/s, loss=49.5593]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.89it/s, loss=46.8942]

SVI:  11%|█         | 11/100 [00:00<00:46,  1.89it/s, loss=49.1039]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.89it/s, loss=44.0886]

SVI:  13%|█▎        | 13/100 [00:00<00:45,  1.89it/s, loss=45.6909]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.89it/s, loss=48.1384]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.89it/s, loss=46.7621]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.89it/s, loss=46.5286]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.89it/s, loss=45.8692]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.89it/s, loss=47.4199]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.89it/s, loss=48.0464]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.89it/s, loss=47.1100]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.89it/s, loss=46.7280]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.89it/s, loss=45.7920]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.89it/s, loss=47.7163]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.89it/s, loss=46.9447]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.89it/s, loss=48.0871]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.89it/s, loss=47.5135]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.89it/s, loss=45.8476]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.89it/s, loss=47.3231]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.89it/s, loss=44.7774]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.89it/s, loss=47.3109]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.89it/s, loss=47.0673]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.89it/s, loss=47.0515]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.89it/s, loss=46.4796]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.89it/s, loss=46.5031]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.89it/s, loss=46.0578]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.89it/s, loss=46.3153]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.89it/s, loss=45.3837]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.89it/s, loss=47.8822]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.89it/s, loss=47.6674]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.89it/s, loss=47.3533]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.89it/s, loss=47.5215]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.89it/s, loss=46.2490]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.89it/s, loss=47.6308]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.89it/s, loss=46.0977]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.89it/s, loss=46.0065]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.89it/s, loss=45.2987]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.89it/s, loss=46.4739]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.89it/s, loss=46.0809]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.89it/s, loss=45.4700]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.89it/s, loss=46.8660]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.89it/s, loss=46.2851]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.89it/s, loss=45.5763]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.89it/s, loss=46.3019]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.89it/s, loss=46.2966]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.89it/s, loss=45.6093]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.89it/s, loss=46.2279]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.89it/s, loss=43.2922]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.89it/s, loss=45.8513]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.89it/s, loss=46.0734]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.89it/s, loss=46.4804]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.89it/s, loss=45.2868]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.89it/s, loss=45.8075]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.89it/s, loss=45.7089]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.89it/s, loss=46.0223]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.89it/s, loss=46.0449]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.89it/s, loss=45.8217]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.89it/s, loss=46.0188]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.89it/s, loss=44.6328]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.89it/s, loss=45.6397]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.89it/s, loss=45.3696]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.89it/s, loss=46.3191]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.89it/s, loss=45.2934]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.89it/s, loss=45.1167]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.89it/s, loss=45.9546]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.89it/s, loss=45.9260]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.89it/s, loss=45.5016]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.89it/s, loss=44.6011]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.89it/s, loss=45.6833]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.89it/s, loss=46.0406]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.89it/s, loss=44.6433]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.89it/s, loss=46.3900]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.89it/s, loss=45.7665]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.89it/s, loss=46.1514]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.89it/s, loss=40.6710]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.89it/s, loss=43.6691]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.89it/s, loss=45.4466]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.89it/s, loss=45.4880]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.89it/s, loss=45.2843]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.89it/s, loss=45.3330]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.89it/s, loss=44.4595]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.89it/s, loss=46.0170]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.89it/s, loss=43.8467]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.89it/s, loss=45.4967]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.89it/s, loss=44.8334]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.89it/s, loss=46.0243]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.89it/s, loss=45.5811]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.89it/s, loss=44.5761]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.89it/s, loss=45.2207]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.89it/s, loss=45.0801]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.89it/s, loss=44.4131]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 49. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.88it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.88it/s, loss=153.5280]

SVI:   2%|▏         | 2/100 [00:00<00:52,  1.88it/s, loss=144.2924]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.88it/s, loss=151.2414]

SVI:   4%|▍         | 4/100 [00:00<00:51,  1.88it/s, loss=149.1736]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.88it/s, loss=145.7552]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.88it/s, loss=148.4804]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.88it/s, loss=150.9656]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.88it/s, loss=144.1864]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.88it/s, loss=142.6102]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.88it/s, loss=145.9875]

SVI:  11%|█         | 11/100 [00:00<00:47,  1.88it/s, loss=142.0220]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.88it/s, loss=137.0297]

SVI:  13%|█▎        | 13/100 [00:00<00:46,  1.88it/s, loss=144.0694]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.88it/s, loss=136.7301]

SVI:  15%|█▌        | 15/100 [00:00<00:45,  1.88it/s, loss=144.3406]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.88it/s, loss=138.7673]

SVI:  17%|█▋        | 17/100 [00:00<00:44,  1.88it/s, loss=133.8167]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.88it/s, loss=133.4756]

SVI:  19%|█▉        | 19/100 [00:00<00:43,  1.88it/s, loss=133.0750]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.88it/s, loss=137.2028]

SVI:  21%|██        | 21/100 [00:00<00:42,  1.88it/s, loss=135.1760]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.88it/s, loss=134.2128]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.88it/s, loss=135.5076]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.88it/s, loss=129.3134]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.88it/s, loss=135.1940]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.88it/s, loss=131.1191]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.88it/s, loss=135.4909]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.88it/s, loss=135.8143]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.88it/s, loss=133.0662]

SVI:  30%|███       | 30/100 [00:00<00:37,  1.88it/s, loss=132.7424]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.88it/s, loss=129.9977]

SVI:  32%|███▏      | 32/100 [00:00<00:36,  1.88it/s, loss=129.1934]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.88it/s, loss=129.6187]

SVI:  34%|███▍      | 34/100 [00:00<00:35,  1.88it/s, loss=129.9130]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.88it/s, loss=131.7555]

SVI:  36%|███▌      | 36/100 [00:00<00:34,  1.88it/s, loss=127.1409]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.88it/s, loss=123.1946]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.88it/s, loss=126.2192]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.88it/s, loss=126.7410]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.88it/s, loss=123.7862]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.88it/s, loss=125.4449]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.88it/s, loss=127.2228]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.88it/s, loss=126.3594]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.88it/s, loss=128.1792]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.88it/s, loss=118.6289]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.88it/s, loss=123.6741]

SVI:  47%|████▋     | 47/100 [00:00<00:28,  1.88it/s, loss=118.3820]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.88it/s, loss=126.5069]

SVI:  49%|████▉     | 49/100 [00:00<00:27,  1.88it/s, loss=118.8959]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.88it/s, loss=123.3192]

SVI:  51%|█████     | 51/100 [00:00<00:26,  1.88it/s, loss=122.6843]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.88it/s, loss=123.0606]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.88it/s, loss=121.5995]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.88it/s, loss=113.7120]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.88it/s, loss=122.3567]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.88it/s, loss=118.4731]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.88it/s, loss=112.2723]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.88it/s, loss=117.9181]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.88it/s, loss=115.0624]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.88it/s, loss=119.4492]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.88it/s, loss=120.6180]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.88it/s, loss=116.9769]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.88it/s, loss=112.9784]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.88it/s, loss=116.9132]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.88it/s, loss=117.3277]

SVI:  66%|██████▌   | 66/100 [00:00<00:18,  1.88it/s, loss=118.5453]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.88it/s, loss=119.4633]

SVI:  68%|██████▊   | 68/100 [00:00<00:17,  1.88it/s, loss=118.9546]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.88it/s, loss=116.5048]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.88it/s, loss=109.8890]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.88it/s, loss=115.2550]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.88it/s, loss=115.7343]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.88it/s, loss=116.1876]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.88it/s, loss=114.9694]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.88it/s, loss=113.6973]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.88it/s, loss=112.6870]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.88it/s, loss=115.7111]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.88it/s, loss=114.8981]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.88it/s, loss=115.6934]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.88it/s, loss=114.5096]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.88it/s, loss=115.9859]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.88it/s, loss=108.4265]

SVI:  83%|████████▎ | 83/100 [00:00<00:09,  1.88it/s, loss=114.2158]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.88it/s, loss=112.1882]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.88it/s, loss=115.0949]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.88it/s, loss=107.2695]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.88it/s, loss=113.3848]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.88it/s, loss=111.8764]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.88it/s, loss=108.2322]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.88it/s, loss=105.3306]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.88it/s, loss=111.6960]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.88it/s, loss=110.1988]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.88it/s, loss=108.8341]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.88it/s, loss=109.7247]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.88it/s, loss=109.9546]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.88it/s, loss=109.2510]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.88it/s, loss=110.4874]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.88it/s, loss=111.6327]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.88it/s, loss=112.6657]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.88it/s, loss=109.7401]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 32. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.97it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.97it/s, loss=289.9408]

SVI:   2%|▏         | 2/100 [00:00<00:49,  1.97it/s, loss=290.9119]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.97it/s, loss=289.4265]

SVI:   4%|▍         | 4/100 [00:00<00:48,  1.97it/s, loss=285.6376]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.97it/s, loss=288.0034]

SVI:   6%|▌         | 6/100 [00:00<00:47,  1.97it/s, loss=288.1275]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.97it/s, loss=283.8310]

SVI:   8%|▊         | 8/100 [00:00<00:46,  1.97it/s, loss=289.6191]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.97it/s, loss=289.4178]

SVI:  10%|█         | 10/100 [00:00<00:45,  1.97it/s, loss=286.8054]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.97it/s, loss=284.5974]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.97it/s, loss=287.2530]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.97it/s, loss=284.1011]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.97it/s, loss=284.4615]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.97it/s, loss=285.1300]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.97it/s, loss=282.1377]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.97it/s, loss=284.6677]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.97it/s, loss=282.0522]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.97it/s, loss=285.8575]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.97it/s, loss=286.1811]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.97it/s, loss=282.5152]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.97it/s, loss=278.2953]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.97it/s, loss=283.9988]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.97it/s, loss=278.2897]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.97it/s, loss=280.9863]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.97it/s, loss=280.6746]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.97it/s, loss=283.2704]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.97it/s, loss=279.9117]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.97it/s, loss=282.1608]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.97it/s, loss=281.6502]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.97it/s, loss=275.6588]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.97it/s, loss=277.4964]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.97it/s, loss=278.4770]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.97it/s, loss=278.9707]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.97it/s, loss=276.6615]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.97it/s, loss=274.7219]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.97it/s, loss=278.2957]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.97it/s, loss=276.5565]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.97it/s, loss=279.3287]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.97it/s, loss=276.7531]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.97it/s, loss=271.5876]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.97it/s, loss=277.9979]

SVI:  43%|████▎     | 43/100 [00:00<00:28,  1.97it/s, loss=274.5199]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.97it/s, loss=273.1908]

SVI:  45%|████▌     | 45/100 [00:00<00:27,  1.97it/s, loss=277.3913]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.97it/s, loss=275.8781]

SVI:  47%|████▋     | 47/100 [00:00<00:26,  1.97it/s, loss=276.0301]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.97it/s, loss=274.9084]

SVI:  49%|████▉     | 49/100 [00:00<00:25,  1.97it/s, loss=271.3107]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.97it/s, loss=275.6130]

SVI:  51%|█████     | 51/100 [00:00<00:24,  1.97it/s, loss=273.5466]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.97it/s, loss=273.4688]

SVI:  53%|█████▎    | 53/100 [00:00<00:23,  1.97it/s, loss=274.4301]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.97it/s, loss=268.3813]

SVI:  55%|█████▌    | 55/100 [00:00<00:22,  1.97it/s, loss=270.5245]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.97it/s, loss=272.2362]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.97it/s, loss=275.1442]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.97it/s, loss=275.0909]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.97it/s, loss=267.6573]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.97it/s, loss=271.3974]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.97it/s, loss=271.6508]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.97it/s, loss=272.9320]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.97it/s, loss=270.5291]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.97it/s, loss=267.9497]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.97it/s, loss=269.8587]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.97it/s, loss=269.6842]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.97it/s, loss=269.7707]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.97it/s, loss=266.5669]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.97it/s, loss=268.7051]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.97it/s, loss=263.6704]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.97it/s, loss=269.4993]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.97it/s, loss=270.3460]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.97it/s, loss=267.9784]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.97it/s, loss=267.0645]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.97it/s, loss=265.8557]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.97it/s, loss=266.0077]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.97it/s, loss=265.0925]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.97it/s, loss=265.7246]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.97it/s, loss=261.8005]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.97it/s, loss=263.3203]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.97it/s, loss=264.5414]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.97it/s, loss=265.0661]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.97it/s, loss=259.3563]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.97it/s, loss=260.9324]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.97it/s, loss=264.0771]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.97it/s, loss=264.8869]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.97it/s, loss=263.2164]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.97it/s, loss=255.3379]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.97it/s, loss=259.8423]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.97it/s, loss=258.0275]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.97it/s, loss=257.0157]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.97it/s, loss=262.9231]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.97it/s, loss=254.4301]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.97it/s, loss=259.4575]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.97it/s, loss=260.0180]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.97it/s, loss=256.1741]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.97it/s, loss=251.0819]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.97it/s, loss=255.4400]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.97it/s, loss=258.2139]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.97it/s, loss=254.3916]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 37. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.91it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.91it/s, loss=103.3302]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.91it/s, loss=101.5447]

SVI:   3%|▎         | 3/100 [00:00<00:50,  1.91it/s, loss=99.9238]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.91it/s, loss=101.9573]

SVI:   5%|▌         | 5/100 [00:00<00:49,  1.91it/s, loss=103.1680]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.91it/s, loss=100.5527]

SVI:   7%|▋         | 7/100 [00:00<00:48,  1.91it/s, loss=100.6559]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.91it/s, loss=102.2831]

SVI:   9%|▉         | 9/100 [00:00<00:47,  1.91it/s, loss=100.7334]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.91it/s, loss=98.7346]

SVI:  11%|█         | 11/100 [00:00<00:46,  1.91it/s, loss=101.9981]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.91it/s, loss=100.4168]

SVI:  13%|█▎        | 13/100 [00:00<00:45,  1.91it/s, loss=98.9312]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.91it/s, loss=95.6924]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.91it/s, loss=97.2252]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.91it/s, loss=97.2250]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.91it/s, loss=100.1927]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.91it/s, loss=100.3769]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.91it/s, loss=95.1615]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.91it/s, loss=94.7168]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.91it/s, loss=97.6703]

SVI:  22%|██▏       | 22/100 [00:00<00:40,  1.91it/s, loss=97.8583]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.91it/s, loss=98.7297]

SVI:  24%|██▍       | 24/100 [00:00<00:39,  1.91it/s, loss=98.7949]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.91it/s, loss=97.5358]

SVI:  26%|██▌       | 26/100 [00:00<00:38,  1.91it/s, loss=98.7750]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.91it/s, loss=97.2456]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.91it/s, loss=97.1182]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.91it/s, loss=95.8574]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.91it/s, loss=94.9586]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.91it/s, loss=94.3801]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.91it/s, loss=98.2037]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.91it/s, loss=95.6916]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.91it/s, loss=95.5474]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.91it/s, loss=98.6256]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.91it/s, loss=96.7064]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.91it/s, loss=95.3300]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.91it/s, loss=97.0616]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.91it/s, loss=97.6173]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.91it/s, loss=96.2969]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.91it/s, loss=97.8062]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.91it/s, loss=96.0928]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.91it/s, loss=92.7170]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.91it/s, loss=95.6207]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.91it/s, loss=96.1926]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.91it/s, loss=95.5149]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.91it/s, loss=94.8367]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.91it/s, loss=97.6010]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.91it/s, loss=97.0767]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.91it/s, loss=95.5008]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.91it/s, loss=96.4813]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.91it/s, loss=93.2444]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.91it/s, loss=95.6513]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.91it/s, loss=92.3176]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.91it/s, loss=95.4896]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.91it/s, loss=94.9354]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.91it/s, loss=93.8804]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.91it/s, loss=94.9192]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.91it/s, loss=95.5934]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.91it/s, loss=92.1368]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.91it/s, loss=94.9252]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.91it/s, loss=93.5423]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.91it/s, loss=93.8950]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.91it/s, loss=91.2468]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.91it/s, loss=92.3447]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.91it/s, loss=94.7809]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.91it/s, loss=93.6629]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.91it/s, loss=95.0373]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.91it/s, loss=94.1601]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.91it/s, loss=94.2193]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.91it/s, loss=95.6240]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.91it/s, loss=93.0894]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.91it/s, loss=94.7433]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.91it/s, loss=95.0218]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.91it/s, loss=89.3613]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.91it/s, loss=94.7999]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.91it/s, loss=93.2104]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.91it/s, loss=94.3836]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.91it/s, loss=94.5483]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.91it/s, loss=93.0651]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.91it/s, loss=93.6063]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.91it/s, loss=92.6495]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.91it/s, loss=92.1894]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.91it/s, loss=93.9141]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.91it/s, loss=93.9478]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.91it/s, loss=93.3066]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.91it/s, loss=94.1986]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.91it/s, loss=94.2277]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.91it/s, loss=92.0695]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.91it/s, loss=91.7268]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.91it/s, loss=91.9717]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.91it/s, loss=92.2376]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.91it/s, loss=92.0254]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.91it/s, loss=87.5994]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.91it/s, loss=93.1071]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.91it/s, loss=91.6446]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.91it/s, loss=93.3357]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.91it/s, loss=90.4063]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.91it/s, loss=91.9026]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.91it/s, loss=91.2943]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 36. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.95it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.95it/s, loss=114.5803]

SVI:   2%|▏         | 2/100 [00:00<00:50,  1.95it/s, loss=117.0677]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.95it/s, loss=126.2024]

SVI:   4%|▍         | 4/100 [00:00<00:49,  1.95it/s, loss=118.1659]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.95it/s, loss=127.2170]

SVI:   6%|▌         | 6/100 [00:00<00:48,  1.95it/s, loss=113.8569]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.95it/s, loss=113.0723]

SVI:   8%|▊         | 8/100 [00:00<00:47,  1.95it/s, loss=116.1405]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.95it/s, loss=113.4439]

SVI:  10%|█         | 10/100 [00:00<00:46,  1.95it/s, loss=116.2876]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.95it/s, loss=111.7587]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.95it/s, loss=113.5831]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.95it/s, loss=120.9437]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.95it/s, loss=117.2289]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.95it/s, loss=111.0729]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.95it/s, loss=108.9755]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.95it/s, loss=115.0804]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.95it/s, loss=113.9009]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.95it/s, loss=115.8247]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.95it/s, loss=108.5926]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.95it/s, loss=107.9711]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.95it/s, loss=113.6602]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.95it/s, loss=108.6146]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.95it/s, loss=110.3520]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.95it/s, loss=100.8552]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.95it/s, loss=107.6178]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.95it/s, loss=106.2804]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.95it/s, loss=108.6397]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.95it/s, loss=109.7981]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.95it/s, loss=103.1402]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.95it/s, loss=104.7104]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.95it/s, loss=107.3287]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.95it/s, loss=104.8188]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.95it/s, loss=102.5203]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.95it/s, loss=102.7528]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.95it/s, loss=99.1122]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.95it/s, loss=103.7728]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.95it/s, loss=98.9906]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.95it/s, loss=100.6302]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.95it/s, loss=102.1924]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.95it/s, loss=103.3921]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.95it/s, loss=98.2660]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.95it/s, loss=100.4485]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.95it/s, loss=93.7324]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.95it/s, loss=100.9707]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.95it/s, loss=101.4836]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.95it/s, loss=101.2190]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.95it/s, loss=94.4802]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.95it/s, loss=100.2788]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.95it/s, loss=96.7709]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.95it/s, loss=97.6746]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.95it/s, loss=96.5846]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.95it/s, loss=96.3130]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.95it/s, loss=97.3525]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.95it/s, loss=93.8687]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.95it/s, loss=94.6110]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.95it/s, loss=92.8960]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.95it/s, loss=94.3137]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.95it/s, loss=93.5790]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.95it/s, loss=92.6997]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.95it/s, loss=93.1955]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.95it/s, loss=93.4411]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.95it/s, loss=88.9844]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.95it/s, loss=94.2793]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.95it/s, loss=89.4009]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.95it/s, loss=94.3584]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.95it/s, loss=93.2569]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.95it/s, loss=93.2335]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.95it/s, loss=94.4189]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.95it/s, loss=90.9870]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.95it/s, loss=93.1998]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.95it/s, loss=85.9833]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.95it/s, loss=93.7118]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.95it/s, loss=92.0086]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.95it/s, loss=91.2694]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.95it/s, loss=90.6308]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.95it/s, loss=89.8872]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.95it/s, loss=91.2889]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.95it/s, loss=92.7840]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.95it/s, loss=91.9338]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.95it/s, loss=91.8335]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.95it/s, loss=90.5973]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.95it/s, loss=89.0561]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.95it/s, loss=90.8042]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.95it/s, loss=91.3090]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.95it/s, loss=91.0297]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.95it/s, loss=83.9995]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.95it/s, loss=90.1163]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.95it/s, loss=89.1630]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.95it/s, loss=86.2681]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.95it/s, loss=90.3635]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.95it/s, loss=90.5403]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.95it/s, loss=89.0136]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.95it/s, loss=88.9478]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.95it/s, loss=89.5987]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.95it/s, loss=87.8647]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.95it/s, loss=89.6589]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.95it/s, loss=87.9304]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.95it/s, loss=88.7226]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.95it/s, loss=87.2310]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 27. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:49,  1.99it/s]

SVI:   1%|          | 1/100 [00:00<00:49,  1.99it/s, loss=161.0551]

SVI:   2%|▏         | 2/100 [00:00<00:49,  1.99it/s, loss=162.2952]

SVI:   3%|▎         | 3/100 [00:00<00:48,  1.99it/s, loss=161.6171]

SVI:   4%|▍         | 4/100 [00:00<00:48,  1.99it/s, loss=160.2773]

SVI:   5%|▌         | 5/100 [00:00<00:47,  1.99it/s, loss=160.1922]

SVI:   6%|▌         | 6/100 [00:00<00:47,  1.99it/s, loss=159.9645]

SVI:   7%|▋         | 7/100 [00:00<00:46,  1.99it/s, loss=158.4480]

SVI:   8%|▊         | 8/100 [00:00<00:46,  1.99it/s, loss=158.3196]

SVI:   9%|▉         | 9/100 [00:00<00:45,  1.99it/s, loss=159.1385]

SVI:  10%|█         | 10/100 [00:00<00:45,  1.99it/s, loss=158.1896]

SVI:  11%|█         | 11/100 [00:00<00:44,  1.99it/s, loss=157.8454]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.99it/s, loss=154.1739]

SVI:  13%|█▎        | 13/100 [00:00<00:43,  1.99it/s, loss=156.6738]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.99it/s, loss=153.0896]

SVI:  15%|█▌        | 15/100 [00:00<00:42,  1.99it/s, loss=151.7344]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.99it/s, loss=155.7050]

SVI:  17%|█▋        | 17/100 [00:00<00:41,  1.99it/s, loss=157.8291]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.99it/s, loss=154.2435]

SVI:  19%|█▉        | 19/100 [00:00<00:40,  1.99it/s, loss=156.1590]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.99it/s, loss=150.9384]

SVI:  21%|██        | 21/100 [00:00<00:39,  1.99it/s, loss=156.3696]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.99it/s, loss=155.3772]

SVI:  23%|██▎       | 23/100 [00:00<00:38,  1.99it/s, loss=154.4695]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.99it/s, loss=151.9535]

SVI:  25%|██▌       | 25/100 [00:00<00:37,  1.99it/s, loss=154.6732]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.99it/s, loss=152.9899]

SVI:  27%|██▋       | 27/100 [00:00<00:36,  1.99it/s, loss=153.3230]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.99it/s, loss=154.5834]

SVI:  29%|██▉       | 29/100 [00:00<00:35,  1.99it/s, loss=149.9199]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.99it/s, loss=154.6819]

SVI:  31%|███       | 31/100 [00:00<00:34,  1.99it/s, loss=149.1870]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.99it/s, loss=149.8668]

SVI:  33%|███▎      | 33/100 [00:00<00:33,  1.99it/s, loss=151.7176]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.99it/s, loss=151.5508]

SVI:  35%|███▌      | 35/100 [00:00<00:32,  1.99it/s, loss=153.2602]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.99it/s, loss=152.4348]

SVI:  37%|███▋      | 37/100 [00:00<00:31,  1.99it/s, loss=152.6750]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.99it/s, loss=153.5007]

SVI:  39%|███▉      | 39/100 [00:00<00:30,  1.99it/s, loss=150.2741]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.99it/s, loss=151.4402]

SVI:  41%|████      | 41/100 [00:00<00:29,  1.99it/s, loss=151.0811]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.99it/s, loss=146.9940]

SVI:  43%|████▎     | 43/100 [00:00<00:28,  1.99it/s, loss=152.1054]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.99it/s, loss=152.4502]

SVI:  45%|████▌     | 45/100 [00:00<00:27,  1.99it/s, loss=148.5606]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.99it/s, loss=152.1702]

SVI:  47%|████▋     | 47/100 [00:00<00:26,  1.99it/s, loss=151.0900]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.99it/s, loss=151.3525]

SVI:  49%|████▉     | 49/100 [00:00<00:25,  1.99it/s, loss=149.1386]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.99it/s, loss=149.8102]

SVI:  51%|█████     | 51/100 [00:00<00:24,  1.99it/s, loss=149.7860]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.99it/s, loss=150.0580]

SVI:  53%|█████▎    | 53/100 [00:00<00:23,  1.99it/s, loss=151.1877]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.99it/s, loss=148.6469]

SVI:  55%|█████▌    | 55/100 [00:00<00:22,  1.99it/s, loss=147.5772]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.99it/s, loss=147.7933]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.99it/s, loss=144.8311]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.99it/s, loss=148.9300]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.99it/s, loss=147.7683]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.99it/s, loss=147.6680]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.99it/s, loss=148.0383]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.99it/s, loss=144.0011]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.99it/s, loss=142.4447]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.99it/s, loss=146.6345]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.99it/s, loss=146.4193]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.99it/s, loss=146.0472]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.99it/s, loss=147.2880]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.99it/s, loss=148.4545]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.99it/s, loss=141.5200]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.99it/s, loss=145.9081]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.99it/s, loss=140.3477]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.99it/s, loss=145.9295]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.99it/s, loss=147.4779]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.99it/s, loss=147.5802]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.99it/s, loss=141.0926]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.99it/s, loss=144.8874]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.99it/s, loss=139.8371]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.99it/s, loss=145.5163]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.99it/s, loss=136.6589]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.99it/s, loss=144.2012]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.99it/s, loss=146.7385]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.99it/s, loss=142.5848]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.99it/s, loss=143.7092]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.99it/s, loss=142.8742]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.99it/s, loss=144.9138]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.99it/s, loss=136.6970]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.99it/s, loss=145.1938]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.99it/s, loss=140.9588]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.99it/s, loss=139.8381]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.99it/s, loss=139.5815]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.99it/s, loss=140.8493]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.99it/s, loss=141.7523]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.99it/s, loss=142.7130]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.99it/s, loss=138.8865]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.99it/s, loss=133.6689]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.99it/s, loss=131.3296]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.99it/s, loss=138.3689]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.99it/s, loss=137.7359]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.99it/s, loss=131.9968]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.99it/s, loss=132.3428]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 31. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<01:11,  1.39it/s]

SVI:   1%|          | 1/100 [00:00<01:11,  1.39it/s, loss=72.7951]

SVI:   2%|▏         | 2/100 [00:00<01:10,  1.39it/s, loss=71.6987]

SVI:   3%|▎         | 3/100 [00:00<01:09,  1.39it/s, loss=72.3675]

SVI:   4%|▍         | 4/100 [00:00<01:09,  1.39it/s, loss=71.1163]

SVI:   5%|▌         | 5/100 [00:00<01:08,  1.39it/s, loss=62.5334]

SVI:   6%|▌         | 6/100 [00:00<01:07,  1.39it/s, loss=70.7000]

SVI:   7%|▋         | 7/100 [00:00<01:06,  1.39it/s, loss=69.3138]

SVI:   8%|▊         | 8/100 [00:00<01:06,  1.39it/s, loss=69.8736]

SVI:   9%|▉         | 9/100 [00:00<01:05,  1.39it/s, loss=66.5859]

SVI:  10%|█         | 10/100 [00:00<01:04,  1.39it/s, loss=69.4414]

SVI:  11%|█         | 11/100 [00:00<01:04,  1.39it/s, loss=69.8026]

SVI:  12%|█▏        | 12/100 [00:00<01:03,  1.39it/s, loss=65.9493]

SVI:  13%|█▎        | 13/100 [00:00<01:02,  1.39it/s, loss=67.5165]

SVI:  14%|█▍        | 14/100 [00:00<01:01,  1.39it/s, loss=67.3872]

SVI:  15%|█▌        | 15/100 [00:00<01:01,  1.39it/s, loss=66.5214]

SVI:  16%|█▌        | 16/100 [00:00<01:00,  1.39it/s, loss=67.7958]

SVI:  17%|█▋        | 17/100 [00:00<00:59,  1.39it/s, loss=67.9802]

SVI:  18%|█▊        | 18/100 [00:00<00:59,  1.39it/s, loss=68.1782]

SVI:  19%|█▉        | 19/100 [00:00<00:58,  1.39it/s, loss=65.9936]

SVI:  20%|██        | 20/100 [00:00<00:57,  1.39it/s, loss=68.3194]

SVI:  21%|██        | 21/100 [00:00<00:56,  1.39it/s, loss=66.2273]

SVI:  22%|██▏       | 22/100 [00:00<00:56,  1.39it/s, loss=67.4649]

SVI:  23%|██▎       | 23/100 [00:00<00:55,  1.39it/s, loss=64.8406]

SVI:  24%|██▍       | 24/100 [00:00<00:54,  1.39it/s, loss=65.4475]

SVI:  25%|██▌       | 25/100 [00:00<00:54,  1.39it/s, loss=66.0396]

SVI:  26%|██▌       | 26/100 [00:00<00:53,  1.39it/s, loss=64.6946]

SVI:  27%|██▋       | 27/100 [00:00<00:52,  1.39it/s, loss=65.0658]

SVI:  28%|██▊       | 28/100 [00:00<00:51,  1.39it/s, loss=67.5512]

SVI:  29%|██▉       | 29/100 [00:00<00:51,  1.39it/s, loss=65.5155]

SVI:  30%|███       | 30/100 [00:00<00:50,  1.39it/s, loss=66.5835]

SVI:  31%|███       | 31/100 [00:00<00:49,  1.39it/s, loss=66.8393]

SVI:  32%|███▏      | 32/100 [00:00<00:48,  1.39it/s, loss=64.6165]

SVI:  33%|███▎      | 33/100 [00:00<00:48,  1.39it/s, loss=64.7309]

SVI:  34%|███▍      | 34/100 [00:00<00:47,  1.39it/s, loss=65.9037]

SVI:  35%|███▌      | 35/100 [00:00<00:46,  1.39it/s, loss=61.5686]

SVI:  36%|███▌      | 36/100 [00:00<00:46,  1.39it/s, loss=65.2581]

SVI:  37%|███▋      | 37/100 [00:00<00:45,  1.39it/s, loss=59.9374]

SVI:  38%|███▊      | 38/100 [00:00<00:44,  1.39it/s, loss=60.2792]

SVI:  39%|███▉      | 39/100 [00:00<00:43,  1.39it/s, loss=64.1253]

SVI:  40%|████      | 40/100 [00:00<00:43,  1.39it/s, loss=63.0033]

SVI:  41%|████      | 41/100 [00:00<00:42,  1.39it/s, loss=65.3532]

SVI:  42%|████▏     | 42/100 [00:00<00:41,  1.39it/s, loss=63.2468]

SVI:  43%|████▎     | 43/100 [00:00<00:41,  1.39it/s, loss=64.2363]

SVI:  44%|████▍     | 44/100 [00:00<00:40,  1.39it/s, loss=63.3154]

SVI:  45%|████▌     | 45/100 [00:00<00:39,  1.39it/s, loss=63.8066]

SVI:  46%|████▌     | 46/100 [00:00<00:38,  1.39it/s, loss=64.5106]

SVI:  47%|████▋     | 47/100 [00:00<00:38,  1.39it/s, loss=63.6223]

SVI:  48%|████▊     | 48/100 [00:00<00:37,  1.39it/s, loss=65.2043]

SVI:  49%|████▉     | 49/100 [00:00<00:36,  1.39it/s, loss=64.1042]

SVI:  50%|█████     | 50/100 [00:00<00:36,  1.39it/s, loss=63.4277]

SVI:  51%|█████     | 51/100 [00:00<00:35,  1.39it/s, loss=64.4235]

SVI:  52%|█████▏    | 52/100 [00:00<00:34,  1.39it/s, loss=63.8902]

SVI:  53%|█████▎    | 53/100 [00:00<00:33,  1.39it/s, loss=63.7477]

SVI:  54%|█████▍    | 54/100 [00:00<00:33,  1.39it/s, loss=60.3758]

SVI:  55%|█████▌    | 55/100 [00:00<00:32,  1.39it/s, loss=63.9755]

SVI:  56%|█████▌    | 56/100 [00:00<00:31,  1.39it/s, loss=63.0207]

SVI:  57%|█████▋    | 57/100 [00:00<00:30,  1.39it/s, loss=62.7120]

SVI:  58%|█████▊    | 58/100 [00:00<00:30,  1.39it/s, loss=59.9326]

SVI:  59%|█████▉    | 59/100 [00:00<00:29,  1.39it/s, loss=62.3772]

SVI:  60%|██████    | 60/100 [00:00<00:28,  1.39it/s, loss=63.0886]

SVI:  61%|██████    | 61/100 [00:00<00:28,  1.39it/s, loss=63.0713]

SVI:  62%|██████▏   | 62/100 [00:00<00:27,  1.39it/s, loss=62.3055]

SVI:  63%|██████▎   | 63/100 [00:00<00:26,  1.39it/s, loss=61.5691]

SVI:  64%|██████▍   | 64/100 [00:00<00:25,  1.39it/s, loss=61.8510]

SVI:  65%|██████▌   | 65/100 [00:00<00:25,  1.39it/s, loss=61.1940]

SVI:  66%|██████▌   | 66/100 [00:00<00:24,  1.39it/s, loss=63.2441]

SVI:  67%|██████▋   | 67/100 [00:00<00:23,  1.39it/s, loss=63.4855]

SVI:  68%|██████▊   | 68/100 [00:00<00:23,  1.39it/s, loss=62.6823]

SVI:  69%|██████▉   | 69/100 [00:00<00:22,  1.39it/s, loss=62.1620]

SVI:  70%|███████   | 70/100 [00:00<00:21,  1.39it/s, loss=60.5625]

SVI:  71%|███████   | 71/100 [00:00<00:20,  1.39it/s, loss=62.0603]

SVI:  72%|███████▏  | 72/100 [00:00<00:20,  1.39it/s, loss=61.6097]

SVI:  73%|███████▎  | 73/100 [00:00<00:19,  1.39it/s, loss=60.7844]

SVI:  74%|███████▍  | 74/100 [00:00<00:18,  1.39it/s, loss=61.5164]

SVI:  75%|███████▌  | 75/100 [00:00<00:18,  1.39it/s, loss=60.1902]

SVI:  76%|███████▌  | 76/100 [00:00<00:17,  1.39it/s, loss=60.0347]

SVI:  77%|███████▋  | 77/100 [00:00<00:16,  1.39it/s, loss=59.7968]

SVI:  78%|███████▊  | 78/100 [00:00<00:15,  1.39it/s, loss=62.3247]

SVI:  79%|███████▉  | 79/100 [00:00<00:15,  1.39it/s, loss=61.6131]

SVI:  80%|████████  | 80/100 [00:00<00:14,  1.39it/s, loss=59.0974]

SVI:  81%|████████  | 81/100 [00:00<00:13,  1.39it/s, loss=61.7851]

SVI:  82%|████████▏ | 82/100 [00:00<00:12,  1.39it/s, loss=60.3331]

SVI:  83%|████████▎ | 83/100 [00:00<00:12,  1.39it/s, loss=61.1386]

SVI:  84%|████████▍ | 84/100 [00:00<00:11,  1.39it/s, loss=60.9997]

SVI:  85%|████████▌ | 85/100 [00:00<00:10,  1.39it/s, loss=59.5320]

SVI:  86%|████████▌ | 86/100 [00:00<00:10,  1.39it/s, loss=60.8643]

SVI:  87%|████████▋ | 87/100 [00:00<00:09,  1.39it/s, loss=60.6109]

SVI:  88%|████████▊ | 88/100 [00:00<00:08,  1.39it/s, loss=59.5487]

SVI:  89%|████████▉ | 89/100 [00:00<00:07,  1.39it/s, loss=59.6547]

SVI:  90%|█████████ | 90/100 [00:00<00:07,  1.39it/s, loss=59.4457]

SVI:  91%|█████████ | 91/100 [00:00<00:06,  1.39it/s, loss=57.7570]

SVI:  92%|█████████▏| 92/100 [00:00<00:05,  1.39it/s, loss=56.6014]

SVI:  93%|█████████▎| 93/100 [00:00<00:05,  1.39it/s, loss=60.9860]

SVI:  94%|█████████▍| 94/100 [00:00<00:04,  1.39it/s, loss=59.5645]

SVI:  95%|█████████▌| 95/100 [00:00<00:03,  1.39it/s, loss=60.6806]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.39it/s, loss=60.1799]

SVI:  97%|█████████▋| 97/100 [00:00<00:02,  1.39it/s, loss=59.0568]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.39it/s, loss=60.8615]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.39it/s, loss=60.9728]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.39it/s, loss=58.7475]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 38. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s, loss=156.2476]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.89it/s, loss=158.9581]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.89it/s, loss=153.7998]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.89it/s, loss=157.1399]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.89it/s, loss=155.7731]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.89it/s, loss=155.6215]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.89it/s, loss=149.9166]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.89it/s, loss=154.0873]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.89it/s, loss=154.1805]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.89it/s, loss=154.5872]

SVI:  11%|█         | 11/100 [00:00<00:47,  1.89it/s, loss=152.3384]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.89it/s, loss=153.8285]

SVI:  13%|█▎        | 13/100 [00:00<00:46,  1.89it/s, loss=149.9066]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.89it/s, loss=154.4094]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.89it/s, loss=151.4931]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.89it/s, loss=154.3459]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.89it/s, loss=150.9864]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.89it/s, loss=151.5975]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.89it/s, loss=149.4551]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.89it/s, loss=151.1435]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.89it/s, loss=150.1468]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.89it/s, loss=145.6201]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.89it/s, loss=150.1786]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.89it/s, loss=150.8843]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.89it/s, loss=148.2805]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.89it/s, loss=150.7545]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.89it/s, loss=149.6047]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.89it/s, loss=147.5172]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.89it/s, loss=147.6441]

SVI:  30%|███       | 30/100 [00:00<00:37,  1.89it/s, loss=148.5491]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.89it/s, loss=147.3672]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.89it/s, loss=148.8979]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.89it/s, loss=149.2929]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.89it/s, loss=149.7624]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.89it/s, loss=149.4705]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.89it/s, loss=147.7635]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.89it/s, loss=148.5085]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.89it/s, loss=146.6215]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.89it/s, loss=147.2781]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.89it/s, loss=146.9624]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.89it/s, loss=148.6942]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.89it/s, loss=148.4686]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.89it/s, loss=148.4532]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.89it/s, loss=149.0231]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.89it/s, loss=149.1005]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.89it/s, loss=146.0633]

SVI:  47%|████▋     | 47/100 [00:00<00:28,  1.89it/s, loss=147.0924]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.89it/s, loss=145.6114]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.89it/s, loss=146.8767]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.89it/s, loss=147.4241]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.89it/s, loss=148.2661]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.89it/s, loss=146.5388]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.89it/s, loss=143.2728]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.89it/s, loss=146.6681]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.89it/s, loss=146.6593]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.89it/s, loss=146.5073]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.89it/s, loss=147.2096]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.89it/s, loss=145.7398]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.89it/s, loss=146.3840]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.89it/s, loss=144.6156]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.89it/s, loss=145.3989]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.89it/s, loss=145.1280]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.89it/s, loss=145.3478]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.89it/s, loss=146.1052]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.89it/s, loss=145.8821]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.89it/s, loss=145.7633]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.89it/s, loss=143.9709]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.89it/s, loss=139.3835]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.89it/s, loss=140.5292]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.89it/s, loss=142.8382]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.89it/s, loss=143.3716]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.89it/s, loss=142.0218]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.89it/s, loss=142.8879]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.89it/s, loss=142.0963]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.89it/s, loss=144.1818]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.89it/s, loss=140.8556]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.89it/s, loss=143.1311]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.89it/s, loss=142.8277]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.89it/s, loss=144.8694]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.89it/s, loss=144.1982]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.89it/s, loss=137.3597]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.89it/s, loss=143.5159]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.89it/s, loss=142.2428]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.89it/s, loss=143.6756]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.89it/s, loss=135.0176]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.89it/s, loss=139.5989]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.89it/s, loss=141.8957]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.89it/s, loss=143.0194]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.89it/s, loss=142.2914]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.89it/s, loss=143.7326]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.89it/s, loss=142.7798]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.89it/s, loss=140.7254]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.89it/s, loss=138.9766]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.89it/s, loss=142.0211]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.89it/s, loss=140.2168]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.89it/s, loss=139.2689]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.89it/s, loss=140.7452]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.89it/s, loss=140.4575]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.89it/s, loss=138.2384]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.89it/s, loss=141.0945]

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.98it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.98it/s, loss=180.6584]

SVI:   2%|▏         | 2/100 [00:00<00:49,  1.98it/s, loss=186.6746]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.98it/s, loss=180.1735]

SVI:   4%|▍         | 4/100 [00:00<00:48,  1.98it/s, loss=184.5914]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.98it/s, loss=186.5901]

SVI:   6%|▌         | 6/100 [00:00<00:47,  1.98it/s, loss=182.3593]

SVI:   7%|▋         | 7/100 [00:00<00:46,  1.98it/s, loss=183.5774]

SVI:   8%|▊         | 8/100 [00:00<00:46,  1.98it/s, loss=183.2279]

SVI:   9%|▉         | 9/100 [00:00<00:45,  1.98it/s, loss=179.8587]

SVI:  10%|█         | 10/100 [00:00<00:45,  1.98it/s, loss=179.0299]

SVI:  11%|█         | 11/100 [00:00<00:44,  1.98it/s, loss=181.7322]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.98it/s, loss=180.2589]

SVI:  13%|█▎        | 13/100 [00:00<00:43,  1.98it/s, loss=176.3347]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.98it/s, loss=178.9376]

SVI:  15%|█▌        | 15/100 [00:00<00:42,  1.98it/s, loss=173.5197]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.98it/s, loss=175.7779]

SVI:  17%|█▋        | 17/100 [00:00<00:41,  1.98it/s, loss=179.7865]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.98it/s, loss=171.7485]

SVI:  19%|█▉        | 19/100 [00:00<00:40,  1.98it/s, loss=177.9492]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.98it/s, loss=178.8408]

SVI:  21%|██        | 21/100 [00:00<00:39,  1.98it/s, loss=177.5832]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.98it/s, loss=179.7712]

SVI:  23%|██▎       | 23/100 [00:00<00:38,  1.98it/s, loss=172.2430]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.98it/s, loss=172.9233]

SVI:  25%|██▌       | 25/100 [00:00<00:37,  1.98it/s, loss=175.0838]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.98it/s, loss=167.7747]

SVI:  27%|██▋       | 27/100 [00:00<00:36,  1.98it/s, loss=169.7255]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.98it/s, loss=166.5886]

SVI:  29%|██▉       | 29/100 [00:00<00:35,  1.98it/s, loss=172.8624]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.98it/s, loss=173.6508]

SVI:  31%|███       | 31/100 [00:00<00:34,  1.98it/s, loss=173.8604]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.98it/s, loss=171.1279]

SVI:  33%|███▎      | 33/100 [00:00<00:33,  1.98it/s, loss=171.4623]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.98it/s, loss=168.2613]

SVI:  35%|███▌      | 35/100 [00:00<00:32,  1.98it/s, loss=166.5810]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.98it/s, loss=164.6994]

SVI:  37%|███▋      | 37/100 [00:00<00:31,  1.98it/s, loss=167.5925]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.98it/s, loss=164.9422]

SVI:  39%|███▉      | 39/100 [00:00<00:30,  1.98it/s, loss=156.9521]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.98it/s, loss=167.6847]

SVI:  41%|████      | 41/100 [00:00<00:29,  1.98it/s, loss=162.2562]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.98it/s, loss=171.3097]

SVI:  43%|████▎     | 43/100 [00:00<00:28,  1.98it/s, loss=167.6398]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.98it/s, loss=162.9647]

SVI:  45%|████▌     | 45/100 [00:00<00:27,  1.98it/s, loss=167.4902]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.98it/s, loss=166.4552]

SVI:  47%|████▋     | 47/100 [00:00<00:26,  1.98it/s, loss=161.6942]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.98it/s, loss=165.4057]

SVI:  49%|████▉     | 49/100 [00:00<00:25,  1.98it/s, loss=157.4376]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.98it/s, loss=162.8005]

SVI:  51%|█████     | 51/100 [00:00<00:24,  1.98it/s, loss=165.0935]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.98it/s, loss=165.7439]

SVI:  53%|█████▎    | 53/100 [00:00<00:23,  1.98it/s, loss=159.8982]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.98it/s, loss=158.8045]

SVI:  55%|█████▌    | 55/100 [00:00<00:22,  1.98it/s, loss=163.9263]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.98it/s, loss=155.3447]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.98it/s, loss=159.4391]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.98it/s, loss=160.8292]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.98it/s, loss=161.2604]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.98it/s, loss=160.7507]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.98it/s, loss=155.6202]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.98it/s, loss=161.7762]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.98it/s, loss=155.4550]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.98it/s, loss=154.2432]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.98it/s, loss=156.6089]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.98it/s, loss=148.0158]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.98it/s, loss=156.7630]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.98it/s, loss=158.3268]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.98it/s, loss=155.5669]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.98it/s, loss=157.4454]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.98it/s, loss=150.5696]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.98it/s, loss=158.4162]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.98it/s, loss=155.2292]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.98it/s, loss=151.2847]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.98it/s, loss=139.7273]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.98it/s, loss=150.4229]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.98it/s, loss=153.9765]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.98it/s, loss=148.7417]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.98it/s, loss=154.7673]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.98it/s, loss=148.8986]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.98it/s, loss=147.6891]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.98it/s, loss=135.7402]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.98it/s, loss=147.1668]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.98it/s, loss=139.0307]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.98it/s, loss=137.8209]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.98it/s, loss=137.0077]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.98it/s, loss=142.7348]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.98it/s, loss=150.4220]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.98it/s, loss=141.7519]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.98it/s, loss=143.8373]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.98it/s, loss=137.4136]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.98it/s, loss=139.4000]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.98it/s, loss=135.6147]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.98it/s, loss=143.6012]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.98it/s, loss=142.7481]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.98it/s, loss=136.4676]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.98it/s, loss=141.4381]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.98it/s, loss=139.6464]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.98it/s, loss=133.8218]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.98it/s, loss=126.0381]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 40. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.96it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.96it/s, loss=115.1966]

SVI:   2%|▏         | 2/100 [00:00<00:49,  1.96it/s, loss=116.4383]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.96it/s, loss=113.8358]

SVI:   4%|▍         | 4/100 [00:00<00:48,  1.96it/s, loss=116.6372]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.96it/s, loss=116.2417]

SVI:   6%|▌         | 6/100 [00:00<00:47,  1.96it/s, loss=115.5644]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.96it/s, loss=114.4908]

SVI:   8%|▊         | 8/100 [00:00<00:46,  1.96it/s, loss=114.2030]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.96it/s, loss=113.4276]

SVI:  10%|█         | 10/100 [00:00<00:45,  1.96it/s, loss=111.4304]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.96it/s, loss=113.9767]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.96it/s, loss=113.8298]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.96it/s, loss=112.8622]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.96it/s, loss=112.8161]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.96it/s, loss=113.6618]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.96it/s, loss=110.2176]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.96it/s, loss=112.0942]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.96it/s, loss=114.3751]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.96it/s, loss=110.1938]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.96it/s, loss=112.0492]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.96it/s, loss=113.0218]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.96it/s, loss=110.4972]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.96it/s, loss=111.7655]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.96it/s, loss=113.4950]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.96it/s, loss=113.4081]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.96it/s, loss=111.7547]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.96it/s, loss=113.0409]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.96it/s, loss=113.4569]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.96it/s, loss=111.9146]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.96it/s, loss=112.4694]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.96it/s, loss=111.6798]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.96it/s, loss=112.5571]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.96it/s, loss=112.4667]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.96it/s, loss=110.5279]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.96it/s, loss=110.7124]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.96it/s, loss=112.3678]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.96it/s, loss=110.9460]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.96it/s, loss=112.6457]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.96it/s, loss=112.9510]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.96it/s, loss=110.8024]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.96it/s, loss=111.0042]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.96it/s, loss=110.1670]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.96it/s, loss=111.2975]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.96it/s, loss=110.5432]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.96it/s, loss=109.8010]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.96it/s, loss=112.4868]

SVI:  47%|████▋     | 47/100 [00:00<00:26,  1.96it/s, loss=112.9030]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.96it/s, loss=110.8194]

SVI:  49%|████▉     | 49/100 [00:00<00:25,  1.96it/s, loss=110.5255]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.96it/s, loss=110.8032]

SVI:  51%|█████     | 51/100 [00:00<00:24,  1.96it/s, loss=111.2801]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.96it/s, loss=111.3347]

SVI:  53%|█████▎    | 53/100 [00:00<00:23,  1.96it/s, loss=111.2095]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.96it/s, loss=111.2386]

SVI:  55%|█████▌    | 55/100 [00:00<00:22,  1.96it/s, loss=110.6897]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.96it/s, loss=111.3774]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.96it/s, loss=111.3665]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.96it/s, loss=109.3618]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.96it/s, loss=108.1138]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.96it/s, loss=111.7727]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.96it/s, loss=111.7510]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.96it/s, loss=111.5997]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.96it/s, loss=109.6772]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.96it/s, loss=110.4988]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.96it/s, loss=111.7688]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.96it/s, loss=111.8834]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.96it/s, loss=108.3136]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.96it/s, loss=111.5876]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.96it/s, loss=109.8555]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.96it/s, loss=109.6819]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.96it/s, loss=111.9439]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.96it/s, loss=110.4465]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.96it/s, loss=111.5171]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.96it/s, loss=111.1532]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.96it/s, loss=111.8810]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.96it/s, loss=110.5302]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.96it/s, loss=110.3500]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.96it/s, loss=110.3879]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.96it/s, loss=109.9739]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.96it/s, loss=110.7064]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.96it/s, loss=108.9077]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.96it/s, loss=111.1365]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.96it/s, loss=111.1026]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.96it/s, loss=110.8484]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.96it/s, loss=109.4585]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.96it/s, loss=111.2366]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.96it/s, loss=109.2917]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.96it/s, loss=110.5893]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.96it/s, loss=107.0448]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.96it/s, loss=111.0190]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.96it/s, loss=110.3781]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.96it/s, loss=108.7559]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.96it/s, loss=110.6132]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.96it/s, loss=110.8312]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.96it/s, loss=111.8649]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.96it/s, loss=111.9035]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.96it/s, loss=108.7082]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.96it/s, loss=109.1553]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.96it/s, loss=110.4959]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.96it/s, loss=110.6994]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 39. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s, loss=30.4243]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.89it/s, loss=29.8705]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.89it/s, loss=30.0397]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.89it/s, loss=30.2254]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.89it/s, loss=31.3350]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.89it/s, loss=31.0868]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.89it/s, loss=30.6821]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.89it/s, loss=27.6776]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.89it/s, loss=29.4300]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.89it/s, loss=30.3752]

SVI:  11%|█         | 11/100 [00:00<00:47,  1.89it/s, loss=29.9451]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.89it/s, loss=28.5248]

SVI:  13%|█▎        | 13/100 [00:00<00:46,  1.89it/s, loss=26.8342]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.89it/s, loss=30.0804]

SVI:  15%|█▌        | 15/100 [00:00<00:45,  1.89it/s, loss=28.8886]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.89it/s, loss=29.5472]

SVI:  17%|█▋        | 17/100 [00:00<00:44,  1.89it/s, loss=29.0590]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.89it/s, loss=27.0088]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.89it/s, loss=29.2987]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.89it/s, loss=28.3346]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.89it/s, loss=29.0038]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.89it/s, loss=29.3832]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.89it/s, loss=29.9277]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.89it/s, loss=28.6428]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.89it/s, loss=28.3408]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.89it/s, loss=29.1110]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.89it/s, loss=27.3983]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.89it/s, loss=28.0545]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.89it/s, loss=29.4472]

SVI:  30%|███       | 30/100 [00:00<00:37,  1.89it/s, loss=28.5338]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.89it/s, loss=29.6375]

SVI:  32%|███▏      | 32/100 [00:00<00:36,  1.89it/s, loss=29.4203]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.89it/s, loss=29.0137]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.89it/s, loss=29.5160]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.89it/s, loss=28.7676]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.89it/s, loss=29.0565]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.89it/s, loss=29.5079]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.89it/s, loss=29.3358]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.89it/s, loss=28.9867]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.89it/s, loss=28.1617]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.89it/s, loss=29.0634]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.89it/s, loss=29.2098]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.89it/s, loss=28.8134]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.89it/s, loss=28.4113]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.89it/s, loss=29.5585]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.89it/s, loss=28.0009]

SVI:  47%|████▋     | 47/100 [00:00<00:28,  1.89it/s, loss=29.3477]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.89it/s, loss=28.2758]

SVI:  49%|████▉     | 49/100 [00:00<00:27,  1.89it/s, loss=28.3860]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.89it/s, loss=28.6025]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.89it/s, loss=25.1735]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.89it/s, loss=29.1146]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.89it/s, loss=28.7981]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.89it/s, loss=27.8623]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.89it/s, loss=29.3520]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.89it/s, loss=26.8174]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.89it/s, loss=28.3363]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.89it/s, loss=28.2794]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.89it/s, loss=28.6962]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.89it/s, loss=27.9955]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.89it/s, loss=28.0913]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.89it/s, loss=28.6270]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.89it/s, loss=26.4909]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.89it/s, loss=26.5622]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.89it/s, loss=28.8094]

SVI:  66%|██████▌   | 66/100 [00:00<00:18,  1.89it/s, loss=28.1861]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.89it/s, loss=27.4210]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.89it/s, loss=26.8210]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.89it/s, loss=29.2859]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.89it/s, loss=27.3491]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.89it/s, loss=27.3857]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.89it/s, loss=28.5435]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.89it/s, loss=28.5886]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.89it/s, loss=28.0981]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.89it/s, loss=28.0654]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.89it/s, loss=28.7779]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.89it/s, loss=28.6618]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.89it/s, loss=27.5863]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.89it/s, loss=27.2222]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.89it/s, loss=28.2161]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.89it/s, loss=28.3419]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.89it/s, loss=27.6195]

SVI:  83%|████████▎ | 83/100 [00:00<00:09,  1.89it/s, loss=27.8687]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.89it/s, loss=28.6576]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.89it/s, loss=27.7581]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.89it/s, loss=28.7933]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.89it/s, loss=25.3113]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.89it/s, loss=27.9335]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.89it/s, loss=28.0139]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.89it/s, loss=27.6128]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.89it/s, loss=28.1847]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.89it/s, loss=28.1681]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.89it/s, loss=28.0741]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.89it/s, loss=28.0867]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.89it/s, loss=27.8298]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.89it/s, loss=28.6354]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.89it/s, loss=28.3422]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.89it/s, loss=28.3760]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.89it/s, loss=28.1557]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.89it/s, loss=28.2381]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 21. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:54,  1.81it/s]

SVI:   1%|          | 1/100 [00:00<00:54,  1.81it/s, loss=112.2529]

SVI:   2%|▏         | 2/100 [00:00<00:54,  1.81it/s, loss=109.0173]

SVI:   3%|▎         | 3/100 [00:00<00:53,  1.81it/s, loss=108.9947]

SVI:   4%|▍         | 4/100 [00:00<00:53,  1.81it/s, loss=111.2673]

SVI:   5%|▌         | 5/100 [00:00<00:52,  1.81it/s, loss=110.0689]

SVI:   6%|▌         | 6/100 [00:00<00:52,  1.81it/s, loss=110.7170]

SVI:   7%|▋         | 7/100 [00:00<00:51,  1.81it/s, loss=110.2094]

SVI:   8%|▊         | 8/100 [00:00<00:50,  1.81it/s, loss=110.3129]

SVI:   9%|▉         | 9/100 [00:00<00:50,  1.81it/s, loss=100.2258]

SVI:  10%|█         | 10/100 [00:00<00:49,  1.81it/s, loss=106.2282]

SVI:  11%|█         | 11/100 [00:00<00:49,  1.81it/s, loss=103.5030]

SVI:  12%|█▏        | 12/100 [00:00<00:48,  1.81it/s, loss=108.4663]

SVI:  13%|█▎        | 13/100 [00:00<00:48,  1.81it/s, loss=101.8162]

SVI:  14%|█▍        | 14/100 [00:00<00:47,  1.81it/s, loss=109.1812]

SVI:  15%|█▌        | 15/100 [00:00<00:47,  1.81it/s, loss=107.0646]

SVI:  16%|█▌        | 16/100 [00:00<00:46,  1.81it/s, loss=108.3497]

SVI:  17%|█▋        | 17/100 [00:00<00:45,  1.81it/s, loss=105.3491]

SVI:  18%|█▊        | 18/100 [00:00<00:45,  1.81it/s, loss=105.6859]

SVI:  19%|█▉        | 19/100 [00:00<00:44,  1.81it/s, loss=103.6131]

SVI:  20%|██        | 20/100 [00:00<00:44,  1.81it/s, loss=105.5533]

SVI:  21%|██        | 21/100 [00:00<00:43,  1.81it/s, loss=104.5000]

SVI:  22%|██▏       | 22/100 [00:00<00:43,  1.81it/s, loss=105.2804]

SVI:  23%|██▎       | 23/100 [00:00<00:42,  1.81it/s, loss=98.8108]

SVI:  24%|██▍       | 24/100 [00:00<00:42,  1.81it/s, loss=98.6975]

SVI:  25%|██▌       | 25/100 [00:00<00:41,  1.81it/s, loss=93.9561]

SVI:  26%|██▌       | 26/100 [00:00<00:40,  1.81it/s, loss=102.2129]

SVI:  27%|██▋       | 27/100 [00:00<00:40,  1.81it/s, loss=100.1067]

SVI:  28%|██▊       | 28/100 [00:00<00:39,  1.81it/s, loss=96.7588]

SVI:  29%|██▉       | 29/100 [00:00<00:39,  1.81it/s, loss=93.5172]

SVI:  30%|███       | 30/100 [00:00<00:38,  1.81it/s, loss=101.7679]

SVI:  31%|███       | 31/100 [00:00<00:38,  1.81it/s, loss=100.5299]

SVI:  32%|███▏      | 32/100 [00:00<00:37,  1.81it/s, loss=99.9331]

SVI:  33%|███▎      | 33/100 [00:00<00:37,  1.81it/s, loss=98.0360]

SVI:  34%|███▍      | 34/100 [00:00<00:36,  1.81it/s, loss=101.0204]

SVI:  35%|███▌      | 35/100 [00:00<00:35,  1.81it/s, loss=99.2951]

SVI:  36%|███▌      | 36/100 [00:00<00:35,  1.81it/s, loss=93.4054]

SVI:  37%|███▋      | 37/100 [00:00<00:34,  1.81it/s, loss=95.6634]

SVI:  38%|███▊      | 38/100 [00:00<00:34,  1.81it/s, loss=95.6083]

SVI:  39%|███▉      | 39/100 [00:00<00:33,  1.81it/s, loss=95.9352]

SVI:  40%|████      | 40/100 [00:00<00:33,  1.81it/s, loss=100.0681]

SVI:  41%|████      | 41/100 [00:00<00:32,  1.81it/s, loss=96.7613]

SVI:  42%|████▏     | 42/100 [00:00<00:32,  1.81it/s, loss=98.6857]

SVI:  43%|████▎     | 43/100 [00:00<00:31,  1.81it/s, loss=97.2122]

SVI:  44%|████▍     | 44/100 [00:00<00:30,  1.81it/s, loss=94.3085]

SVI:  45%|████▌     | 45/100 [00:00<00:30,  1.81it/s, loss=97.2383]

SVI:  46%|████▌     | 46/100 [00:00<00:29,  1.81it/s, loss=97.7142]

SVI:  47%|████▋     | 47/100 [00:00<00:29,  1.81it/s, loss=96.7068]

SVI:  48%|████▊     | 48/100 [00:00<00:28,  1.81it/s, loss=93.3384]

SVI:  49%|████▉     | 49/100 [00:00<00:28,  1.81it/s, loss=97.8073]

SVI:  50%|█████     | 50/100 [00:00<00:27,  1.81it/s, loss=92.2313]

SVI:  51%|█████     | 51/100 [00:00<00:27,  1.81it/s, loss=94.1557]

SVI:  52%|█████▏    | 52/100 [00:00<00:26,  1.81it/s, loss=93.1336]

SVI:  53%|█████▎    | 53/100 [00:00<00:26,  1.81it/s, loss=93.2079]

SVI:  54%|█████▍    | 54/100 [00:00<00:25,  1.81it/s, loss=90.6185]

SVI:  55%|█████▌    | 55/100 [00:00<00:24,  1.81it/s, loss=88.7552]

SVI:  56%|█████▌    | 56/100 [00:00<00:24,  1.81it/s, loss=92.0153]

SVI:  57%|█████▋    | 57/100 [00:00<00:23,  1.81it/s, loss=92.8898]

SVI:  58%|█████▊    | 58/100 [00:00<00:23,  1.81it/s, loss=95.0038]

SVI:  59%|█████▉    | 59/100 [00:00<00:22,  1.81it/s, loss=95.1784]

SVI:  60%|██████    | 60/100 [00:00<00:22,  1.81it/s, loss=90.5323]

SVI:  61%|██████    | 61/100 [00:00<00:21,  1.81it/s, loss=93.5221]

SVI:  62%|██████▏   | 62/100 [00:00<00:21,  1.81it/s, loss=92.5553]

SVI:  63%|██████▎   | 63/100 [00:00<00:20,  1.81it/s, loss=86.9208]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.81it/s, loss=89.8390]

SVI:  65%|██████▌   | 65/100 [00:00<00:19,  1.81it/s, loss=82.4094]

SVI:  66%|██████▌   | 66/100 [00:00<00:18,  1.81it/s, loss=88.2442]

SVI:  67%|██████▋   | 67/100 [00:00<00:18,  1.81it/s, loss=89.0395]

SVI:  68%|██████▊   | 68/100 [00:00<00:17,  1.81it/s, loss=85.1592]

SVI:  69%|██████▉   | 69/100 [00:00<00:17,  1.81it/s, loss=93.3471]

SVI:  70%|███████   | 70/100 [00:00<00:16,  1.81it/s, loss=86.4599]

SVI:  71%|███████   | 71/100 [00:00<00:16,  1.81it/s, loss=85.4170]

SVI:  72%|███████▏  | 72/100 [00:00<00:15,  1.81it/s, loss=91.1021]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.81it/s, loss=89.2601]

SVI:  74%|███████▍  | 74/100 [00:00<00:14,  1.81it/s, loss=81.3430]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.81it/s, loss=90.9276]

SVI:  76%|███████▌  | 76/100 [00:00<00:13,  1.81it/s, loss=87.2270]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.81it/s, loss=86.1443]

SVI:  78%|███████▊  | 78/100 [00:00<00:12,  1.81it/s, loss=85.5414]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.81it/s, loss=87.6114]

SVI:  80%|████████  | 80/100 [00:00<00:11,  1.81it/s, loss=85.7558]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.81it/s, loss=89.0438]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.81it/s, loss=83.8902]

SVI:  83%|████████▎ | 83/100 [00:00<00:09,  1.81it/s, loss=85.5300]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.81it/s, loss=86.3808]

SVI:  85%|████████▌ | 85/100 [00:00<00:08,  1.81it/s, loss=87.6390]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.81it/s, loss=89.0544]

SVI:  87%|████████▋ | 87/100 [00:00<00:07,  1.81it/s, loss=86.4080]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.81it/s, loss=82.1215]

SVI:  89%|████████▉ | 89/100 [00:00<00:06,  1.81it/s, loss=83.0260]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.81it/s, loss=83.5482]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.81it/s, loss=83.7744]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.81it/s, loss=84.1161]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.81it/s, loss=83.8404]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.81it/s, loss=83.8289]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.81it/s, loss=80.2064]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.81it/s, loss=82.5927]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.81it/s, loss=73.4642]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.81it/s, loss=84.9897]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.81it/s, loss=79.1726]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.81it/s, loss=80.0122]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 31. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.96it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.96it/s, loss=55.7978]

SVI:   2%|▏         | 2/100 [00:00<00:50,  1.96it/s, loss=56.0941]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.96it/s, loss=53.7009]

SVI:   4%|▍         | 4/100 [00:00<00:49,  1.96it/s, loss=56.8604]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.96it/s, loss=56.3987]

SVI:   6%|▌         | 6/100 [00:00<00:48,  1.96it/s, loss=53.6538]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.96it/s, loss=55.1210]

SVI:   8%|▊         | 8/100 [00:00<00:47,  1.96it/s, loss=54.2440]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.96it/s, loss=54.2037]

SVI:  10%|█         | 10/100 [00:00<00:46,  1.96it/s, loss=54.6689]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.96it/s, loss=52.3994]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.96it/s, loss=46.1508]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.96it/s, loss=54.1509]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.96it/s, loss=51.0438]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.96it/s, loss=52.1398]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.96it/s, loss=53.0782]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.96it/s, loss=52.4653]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.96it/s, loss=50.2713]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.96it/s, loss=51.1446]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.96it/s, loss=51.8208]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.96it/s, loss=49.7768]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.96it/s, loss=50.1457]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.96it/s, loss=50.7819]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.96it/s, loss=50.8695]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.96it/s, loss=50.9852]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.96it/s, loss=49.6247]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.96it/s, loss=49.9464]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.96it/s, loss=51.8949]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.96it/s, loss=50.0736]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.96it/s, loss=50.7353]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.96it/s, loss=50.5502]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.96it/s, loss=50.3169]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.96it/s, loss=52.0189]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.96it/s, loss=49.9870]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.96it/s, loss=46.7651]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.96it/s, loss=51.1281]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.96it/s, loss=51.0090]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.96it/s, loss=50.4442]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.96it/s, loss=49.6321]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.96it/s, loss=51.0042]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.96it/s, loss=50.5027]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.96it/s, loss=49.9246]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.96it/s, loss=49.8450]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.96it/s, loss=47.1617]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.96it/s, loss=49.3325]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.96it/s, loss=50.4312]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.96it/s, loss=50.6353]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.96it/s, loss=50.2397]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.96it/s, loss=50.1492]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.96it/s, loss=49.4035]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.96it/s, loss=51.2116]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.96it/s, loss=49.1558]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.96it/s, loss=50.5751]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.96it/s, loss=50.8866]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.96it/s, loss=50.1661]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.96it/s, loss=48.1869]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.96it/s, loss=47.7038]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.96it/s, loss=50.7156]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.96it/s, loss=50.6247]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.96it/s, loss=50.1797]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.96it/s, loss=49.0168]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.96it/s, loss=50.0827]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.96it/s, loss=49.8444]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.96it/s, loss=49.4878]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.96it/s, loss=49.4716]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.96it/s, loss=50.0667]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.96it/s, loss=50.5524]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.96it/s, loss=49.4565]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.96it/s, loss=50.1155]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.96it/s, loss=45.0256]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.96it/s, loss=50.3109]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.96it/s, loss=50.1093]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.96it/s, loss=50.2517]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.96it/s, loss=50.0720]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.96it/s, loss=49.5521]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.96it/s, loss=49.0238]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.96it/s, loss=49.3961]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.96it/s, loss=48.9319]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.96it/s, loss=48.4054]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.96it/s, loss=49.8228]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.96it/s, loss=47.9522]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.96it/s, loss=48.7098]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.96it/s, loss=46.8806]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.96it/s, loss=49.1048]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.96it/s, loss=49.9482]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.96it/s, loss=49.8763]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.96it/s, loss=48.6731]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.96it/s, loss=49.8705]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.96it/s, loss=49.2274]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.96it/s, loss=48.0195]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.96it/s, loss=45.4304]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.96it/s, loss=49.4098]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.96it/s, loss=48.8258]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.96it/s, loss=49.9362]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.96it/s, loss=48.0364]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.96it/s, loss=48.9391]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.96it/s, loss=48.7822]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.96it/s, loss=47.8334]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.96it/s, loss=50.2466]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.96it/s, loss=49.9413]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 36. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s, loss=117.7378]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.89it/s, loss=120.2699]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.89it/s, loss=110.4572]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.89it/s, loss=116.5137]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.89it/s, loss=113.5718]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.89it/s, loss=117.2451]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.89it/s, loss=116.1408]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.89it/s, loss=117.9128]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.89it/s, loss=114.9624]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.89it/s, loss=111.6907]

SVI:  11%|█         | 11/100 [00:00<00:46,  1.89it/s, loss=115.1930]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.89it/s, loss=113.4778]

SVI:  13%|█▎        | 13/100 [00:00<00:45,  1.89it/s, loss=115.7444]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.89it/s, loss=115.6948]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.89it/s, loss=112.9043]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.89it/s, loss=111.4026]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.89it/s, loss=113.8777]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.89it/s, loss=112.8959]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.89it/s, loss=113.5961]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.89it/s, loss=113.6206]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.89it/s, loss=113.8688]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.89it/s, loss=111.9182]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.89it/s, loss=114.5325]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.89it/s, loss=113.9946]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.89it/s, loss=108.8231]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.89it/s, loss=114.1195]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.89it/s, loss=110.4584]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.89it/s, loss=111.7511]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.89it/s, loss=112.0304]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.89it/s, loss=109.2969]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.89it/s, loss=110.6101]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.89it/s, loss=110.2672]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.89it/s, loss=109.0263]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.89it/s, loss=112.9311]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.89it/s, loss=112.3331]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.89it/s, loss=109.9179]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.89it/s, loss=110.8761]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.89it/s, loss=111.4179]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.89it/s, loss=110.7282]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.89it/s, loss=111.0228]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.89it/s, loss=111.6378]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.89it/s, loss=111.1580]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.89it/s, loss=111.2808]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.89it/s, loss=106.2072]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.89it/s, loss=111.5906]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.89it/s, loss=112.0574]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.89it/s, loss=109.5338]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.89it/s, loss=109.8848]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.89it/s, loss=110.7784]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.89it/s, loss=109.7344]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.89it/s, loss=108.1192]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.89it/s, loss=105.7731]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.89it/s, loss=109.7426]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.89it/s, loss=104.8759]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.89it/s, loss=108.7342]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.89it/s, loss=107.9775]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.89it/s, loss=109.2868]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.89it/s, loss=106.7486]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.89it/s, loss=108.0939]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.89it/s, loss=109.8444]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.89it/s, loss=106.8998]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.89it/s, loss=109.5435]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.89it/s, loss=109.2745]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.89it/s, loss=107.9454]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.89it/s, loss=108.5552]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.89it/s, loss=106.5828]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.89it/s, loss=109.4383]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.89it/s, loss=108.5212]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.89it/s, loss=107.9087]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.89it/s, loss=107.4375]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.89it/s, loss=107.2678]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.89it/s, loss=103.9918]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.89it/s, loss=108.9052]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.89it/s, loss=105.3687]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.89it/s, loss=106.5185]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.89it/s, loss=100.0678]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.89it/s, loss=105.0926]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.89it/s, loss=107.2306]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.89it/s, loss=102.8316]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.89it/s, loss=107.1682]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.89it/s, loss=106.7484]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.89it/s, loss=108.3409]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.89it/s, loss=106.0403]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.89it/s, loss=108.4278]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.89it/s, loss=107.3414]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.89it/s, loss=103.7588]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.89it/s, loss=101.3276]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.89it/s, loss=105.8037]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.89it/s, loss=105.6439]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.89it/s, loss=105.8944]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.89it/s, loss=103.4856]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.89it/s, loss=103.4065]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.89it/s, loss=106.2992]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.89it/s, loss=104.9618]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.89it/s, loss=103.4392]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.89it/s, loss=102.1742]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.89it/s, loss=97.4585]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.89it/s, loss=105.5565]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.89it/s, loss=104.1691]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.89it/s, loss=105.0028]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 33. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.91it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.91it/s, loss=78.8437]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.91it/s, loss=75.7279]

SVI:   3%|▎         | 3/100 [00:00<00:50,  1.91it/s, loss=78.3476]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.91it/s, loss=81.5617]

SVI:   5%|▌         | 5/100 [00:00<00:49,  1.91it/s, loss=72.1971]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.91it/s, loss=78.1640]

SVI:   7%|▋         | 7/100 [00:00<00:48,  1.91it/s, loss=78.8016]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.91it/s, loss=77.6393]

SVI:   9%|▉         | 9/100 [00:00<00:47,  1.91it/s, loss=75.8628]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.91it/s, loss=74.2977]

SVI:  11%|█         | 11/100 [00:00<00:46,  1.91it/s, loss=74.1836]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.91it/s, loss=73.1564]

SVI:  13%|█▎        | 13/100 [00:00<00:45,  1.91it/s, loss=72.7134]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.91it/s, loss=71.7873]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.91it/s, loss=67.6916]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.91it/s, loss=68.2691]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.91it/s, loss=71.4039]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.91it/s, loss=69.0863]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.91it/s, loss=72.8628]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.91it/s, loss=70.5189]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.91it/s, loss=71.9700]

SVI:  22%|██▏       | 22/100 [00:00<00:40,  1.91it/s, loss=73.7881]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.91it/s, loss=72.2345]

SVI:  24%|██▍       | 24/100 [00:00<00:39,  1.91it/s, loss=67.5338]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.91it/s, loss=67.9640]

SVI:  26%|██▌       | 26/100 [00:00<00:38,  1.91it/s, loss=67.7595]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.91it/s, loss=69.9088]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.91it/s, loss=64.4371]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.91it/s, loss=67.3426]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.91it/s, loss=70.3934]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.91it/s, loss=70.3025]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.91it/s, loss=67.8268]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.91it/s, loss=67.8017]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.91it/s, loss=67.5668]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.91it/s, loss=63.9031]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.91it/s, loss=67.3432]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.91it/s, loss=67.4025]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.91it/s, loss=66.2265]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.91it/s, loss=66.7751]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.91it/s, loss=64.2567]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.91it/s, loss=67.5151]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.91it/s, loss=65.0922]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.91it/s, loss=66.3579]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.91it/s, loss=63.3712]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.91it/s, loss=65.0700]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.91it/s, loss=64.5856]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.91it/s, loss=67.1535]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.91it/s, loss=57.8075]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.91it/s, loss=62.5223]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.91it/s, loss=61.7688]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.91it/s, loss=64.1741]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.91it/s, loss=64.1413]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.91it/s, loss=62.6898]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.91it/s, loss=61.9830]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.91it/s, loss=61.6136]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.91it/s, loss=62.6773]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.91it/s, loss=60.1841]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.91it/s, loss=58.7839]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.91it/s, loss=62.7003]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.91it/s, loss=57.5036]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.91it/s, loss=59.8183]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.91it/s, loss=57.1052]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.91it/s, loss=56.9895]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.91it/s, loss=62.7616]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.91it/s, loss=61.2172]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.91it/s, loss=59.8439]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.91it/s, loss=55.8962]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.91it/s, loss=58.5172]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.91it/s, loss=61.4366]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.91it/s, loss=54.6356]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.91it/s, loss=60.9944]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.91it/s, loss=59.6831]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.91it/s, loss=60.7790]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.91it/s, loss=60.5633]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.91it/s, loss=53.6489]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.91it/s, loss=61.2834]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.91it/s, loss=59.8588]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.91it/s, loss=59.6371]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.91it/s, loss=57.5720]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.91it/s, loss=55.8001]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.91it/s, loss=57.7557]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.91it/s, loss=59.4971]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.91it/s, loss=56.5434]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.91it/s, loss=54.4833]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.91it/s, loss=57.4978]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.91it/s, loss=56.4099]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.91it/s, loss=54.8374]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.91it/s, loss=54.6368]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.91it/s, loss=57.2693]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.91it/s, loss=56.0201]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.91it/s, loss=55.5156]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.91it/s, loss=57.7462]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.91it/s, loss=56.6721]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.91it/s, loss=53.9289]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.91it/s, loss=57.4053]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.91it/s, loss=57.3255]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.91it/s, loss=57.8058]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.91it/s, loss=56.6560]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.91it/s, loss=50.4119]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.91it/s, loss=56.7803]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 38. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.96it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.96it/s, loss=51.5225]

SVI:   2%|▏         | 2/100 [00:00<00:50,  1.96it/s, loss=50.6749]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.96it/s, loss=50.0681]

SVI:   4%|▍         | 4/100 [00:00<00:49,  1.96it/s, loss=50.2188]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.96it/s, loss=51.0237]

SVI:   6%|▌         | 6/100 [00:00<00:48,  1.96it/s, loss=52.1424]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.96it/s, loss=49.7821]

SVI:   8%|▊         | 8/100 [00:00<00:47,  1.96it/s, loss=50.1058]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.96it/s, loss=49.8210]

SVI:  10%|█         | 10/100 [00:00<00:45,  1.96it/s, loss=49.9055]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.96it/s, loss=48.3154]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.96it/s, loss=49.0749]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.96it/s, loss=48.6137]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.96it/s, loss=48.2478]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.96it/s, loss=47.8187]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.96it/s, loss=47.9418]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.96it/s, loss=46.8152]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.96it/s, loss=47.9426]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.96it/s, loss=48.9894]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.96it/s, loss=48.6163]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.96it/s, loss=47.2145]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.96it/s, loss=47.5502]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.96it/s, loss=48.1843]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.96it/s, loss=48.8248]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.96it/s, loss=47.2798]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.96it/s, loss=46.8603]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.96it/s, loss=48.8342]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.96it/s, loss=48.0706]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.96it/s, loss=48.1898]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.96it/s, loss=47.8470]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.96it/s, loss=46.7287]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.96it/s, loss=48.1968]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.96it/s, loss=47.5106]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.96it/s, loss=48.4438]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.96it/s, loss=47.8731]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.96it/s, loss=47.4550]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.96it/s, loss=47.8137]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.96it/s, loss=47.5825]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.96it/s, loss=48.4209]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.96it/s, loss=47.7562]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.96it/s, loss=47.4145]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.96it/s, loss=47.8984]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.96it/s, loss=43.9749]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.96it/s, loss=47.5383]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.96it/s, loss=48.2136]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.96it/s, loss=47.1833]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.96it/s, loss=44.6626]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.96it/s, loss=48.1370]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.96it/s, loss=47.1416]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.96it/s, loss=46.4677]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.96it/s, loss=47.6568]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.96it/s, loss=47.4023]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.96it/s, loss=48.5115]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.96it/s, loss=47.5673]

SVI:  55%|█████▌    | 55/100 [00:00<00:22,  1.96it/s, loss=47.7992]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.96it/s, loss=46.1146]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.96it/s, loss=47.2712]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.96it/s, loss=47.2505]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.96it/s, loss=46.3232]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.96it/s, loss=47.2180]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.96it/s, loss=45.0821]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.96it/s, loss=47.7196]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.96it/s, loss=47.8713]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.96it/s, loss=46.8205]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.96it/s, loss=46.6740]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.96it/s, loss=46.3044]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.96it/s, loss=47.0777]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.96it/s, loss=47.2877]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.96it/s, loss=45.3969]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.96it/s, loss=46.9274]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.96it/s, loss=46.4240]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.96it/s, loss=46.6909]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.96it/s, loss=46.7572]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.96it/s, loss=44.6801]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.96it/s, loss=46.0726]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.96it/s, loss=46.9285]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.96it/s, loss=47.1318]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.96it/s, loss=47.3322]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.96it/s, loss=46.5487]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.96it/s, loss=45.9706]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.96it/s, loss=47.5630]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.96it/s, loss=46.8738]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.96it/s, loss=41.1525]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.96it/s, loss=42.1175]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.96it/s, loss=47.9431]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.96it/s, loss=45.8059]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.96it/s, loss=45.9987]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.96it/s, loss=46.1531]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.96it/s, loss=47.0122]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.96it/s, loss=47.3734]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.96it/s, loss=46.7428]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.96it/s, loss=47.3102]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.96it/s, loss=45.9908]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.96it/s, loss=46.9071]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.96it/s, loss=46.8258]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.96it/s, loss=47.1443]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.96it/s, loss=46.3951]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.96it/s, loss=46.2182]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.96it/s, loss=47.7554]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.96it/s, loss=45.7390]

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.88it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.88it/s, loss=52.3840]

SVI:   2%|▏         | 2/100 [00:00<00:52,  1.88it/s, loss=54.6304]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.88it/s, loss=53.3104]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.88it/s, loss=55.1029]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.88it/s, loss=52.6191]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.88it/s, loss=53.4571]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.88it/s, loss=55.1667]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.88it/s, loss=54.0245]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.88it/s, loss=54.2297]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.88it/s, loss=51.1726]

SVI:  11%|█         | 11/100 [00:00<00:47,  1.88it/s, loss=52.4568]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.88it/s, loss=51.3419]

SVI:  13%|█▎        | 13/100 [00:00<00:46,  1.88it/s, loss=53.6033]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.88it/s, loss=52.7990]

SVI:  15%|█▌        | 15/100 [00:00<00:45,  1.88it/s, loss=50.8347]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.88it/s, loss=53.2620]

SVI:  17%|█▋        | 17/100 [00:00<00:44,  1.88it/s, loss=51.6547]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.88it/s, loss=52.2047]

SVI:  19%|█▉        | 19/100 [00:00<00:43,  1.88it/s, loss=51.9166]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.88it/s, loss=48.6527]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.88it/s, loss=50.6344]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.88it/s, loss=51.9750]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.88it/s, loss=52.6373]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.88it/s, loss=51.7998]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.88it/s, loss=50.8777]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.88it/s, loss=51.4003]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.88it/s, loss=48.6398]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.88it/s, loss=52.6516]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.88it/s, loss=50.7722]

SVI:  30%|███       | 30/100 [00:00<00:37,  1.88it/s, loss=51.3388]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.88it/s, loss=51.6469]

SVI:  32%|███▏      | 32/100 [00:00<00:36,  1.88it/s, loss=49.4277]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.88it/s, loss=45.9949]

SVI:  34%|███▍      | 34/100 [00:00<00:35,  1.88it/s, loss=51.3728]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.88it/s, loss=50.5382]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.88it/s, loss=49.4682]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.88it/s, loss=48.3196]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.88it/s, loss=50.1658]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.88it/s, loss=51.5620]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.88it/s, loss=50.2469]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.88it/s, loss=48.5235]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.88it/s, loss=51.1529]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.88it/s, loss=45.3312]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.88it/s, loss=48.9266]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.88it/s, loss=50.4594]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.88it/s, loss=46.4734]

SVI:  47%|████▋     | 47/100 [00:00<00:28,  1.88it/s, loss=49.5127]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.88it/s, loss=49.7282]

SVI:  49%|████▉     | 49/100 [00:00<00:27,  1.88it/s, loss=46.1330]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.88it/s, loss=45.4000]

SVI:  51%|█████     | 51/100 [00:00<00:26,  1.88it/s, loss=49.5832]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.88it/s, loss=47.5164]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.88it/s, loss=50.6893]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.88it/s, loss=49.9520]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.88it/s, loss=49.8465]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.88it/s, loss=50.3433]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.88it/s, loss=48.8044]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.88it/s, loss=50.1147]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.88it/s, loss=47.8716]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.88it/s, loss=49.1343]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.88it/s, loss=47.8117]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.88it/s, loss=49.6616]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.88it/s, loss=50.1755]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.88it/s, loss=49.1699]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.88it/s, loss=49.0825]

SVI:  66%|██████▌   | 66/100 [00:00<00:18,  1.88it/s, loss=49.7575]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.88it/s, loss=46.9644]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.88it/s, loss=49.0848]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.88it/s, loss=48.4563]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.88it/s, loss=47.4607]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.88it/s, loss=47.5659]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.88it/s, loss=46.8028]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.88it/s, loss=48.7877]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.88it/s, loss=47.0348]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.88it/s, loss=48.1451]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.88it/s, loss=47.9555]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.88it/s, loss=48.0985]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.88it/s, loss=47.4293]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.88it/s, loss=48.4512]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.88it/s, loss=47.8962]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.88it/s, loss=48.0325]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.88it/s, loss=49.5507]

SVI:  83%|████████▎ | 83/100 [00:00<00:09,  1.88it/s, loss=45.7037]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.88it/s, loss=47.5987]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.88it/s, loss=48.8253]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.88it/s, loss=47.5282]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.88it/s, loss=47.4829]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.88it/s, loss=46.9543]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.88it/s, loss=48.2902]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.88it/s, loss=48.9768]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.88it/s, loss=49.5653]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.88it/s, loss=47.0813]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.88it/s, loss=47.9209]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.88it/s, loss=47.8686]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.88it/s, loss=45.7801]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.88it/s, loss=48.2655]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.88it/s, loss=47.2419]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.88it/s, loss=48.8200]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.88it/s, loss=48.5638]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.88it/s, loss=48.6117]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 24. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.94it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.94it/s, loss=30.1436]

SVI:   2%|▏         | 2/100 [00:00<00:50,  1.94it/s, loss=30.5381]

SVI:   3%|▎         | 3/100 [00:00<00:50,  1.94it/s, loss=28.6266]

SVI:   4%|▍         | 4/100 [00:00<00:49,  1.94it/s, loss=30.5239]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.94it/s, loss=26.7930]

SVI:   6%|▌         | 6/100 [00:00<00:48,  1.94it/s, loss=30.1627]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.94it/s, loss=28.3098]

SVI:   8%|▊         | 8/100 [00:00<00:47,  1.94it/s, loss=25.4801]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.94it/s, loss=24.2826]

SVI:  10%|█         | 10/100 [00:00<00:46,  1.94it/s, loss=30.4628]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.94it/s, loss=28.9058]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.94it/s, loss=26.3666]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.94it/s, loss=26.0650]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.94it/s, loss=27.5114]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.94it/s, loss=26.9420]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.94it/s, loss=27.2021]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.94it/s, loss=23.7015]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.94it/s, loss=19.7415]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.94it/s, loss=27.1000]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.94it/s, loss=26.1517]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.94it/s, loss=26.6803]

SVI:  22%|██▏       | 22/100 [00:00<00:40,  1.94it/s, loss=24.4664]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.94it/s, loss=25.9751]

SVI:  24%|██▍       | 24/100 [00:00<00:39,  1.94it/s, loss=25.2230]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.94it/s, loss=23.7061]

SVI:  26%|██▌       | 26/100 [00:00<00:38,  1.94it/s, loss=24.3861]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.94it/s, loss=25.8635]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.94it/s, loss=26.1609]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.94it/s, loss=25.0238]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.94it/s, loss=23.8042]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.94it/s, loss=24.9529]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.94it/s, loss=25.0395]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.94it/s, loss=23.2784]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.94it/s, loss=20.9638]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.94it/s, loss=22.4956]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.94it/s, loss=24.6403]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.94it/s, loss=22.6292]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.94it/s, loss=24.1904]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.94it/s, loss=22.4895]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.94it/s, loss=24.0659]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.94it/s, loss=23.2598]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.94it/s, loss=24.0037]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.94it/s, loss=23.0639]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.94it/s, loss=19.3955]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.94it/s, loss=23.1000]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.94it/s, loss=21.4003]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.94it/s, loss=22.4231]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.94it/s, loss=23.9166]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.94it/s, loss=23.2941]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.94it/s, loss=21.5634]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.94it/s, loss=23.5118]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.94it/s, loss=22.3839]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.94it/s, loss=23.6905]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.94it/s, loss=20.6342]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.94it/s, loss=22.2720]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.94it/s, loss=23.3786]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.94it/s, loss=20.5661]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.94it/s, loss=21.2034]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.94it/s, loss=23.1890]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.94it/s, loss=22.4253]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.94it/s, loss=21.5204]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.94it/s, loss=19.7004]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.94it/s, loss=22.5480]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.94it/s, loss=22.4909]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.94it/s, loss=22.5900]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.94it/s, loss=22.6336]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.94it/s, loss=23.1758]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.94it/s, loss=21.3079]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.94it/s, loss=22.1372]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.94it/s, loss=20.2649]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.94it/s, loss=21.1163]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.94it/s, loss=21.6544]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.94it/s, loss=21.2259]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.94it/s, loss=22.3014]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.94it/s, loss=22.4303]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.94it/s, loss=22.0603]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.94it/s, loss=21.4766]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.94it/s, loss=20.0470]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.94it/s, loss=22.0959]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.94it/s, loss=21.6443]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.94it/s, loss=21.5707]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.94it/s, loss=21.3263]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.94it/s, loss=21.6691]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.94it/s, loss=21.7798]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.94it/s, loss=19.9777]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.94it/s, loss=20.6733]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.94it/s, loss=22.2415]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.94it/s, loss=22.2688]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.94it/s, loss=20.9663]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.94it/s, loss=18.9863]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.94it/s, loss=21.9726]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.94it/s, loss=21.2075]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.94it/s, loss=21.7521]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.94it/s, loss=20.7901]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.94it/s, loss=21.7350]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.94it/s, loss=19.7024]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.94it/s, loss=20.9167]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.94it/s, loss=21.6480]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.94it/s, loss=21.4560]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.94it/s, loss=20.5951]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 36. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.93it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.93it/s, loss=51.7106]

SVI:   2%|▏         | 2/100 [00:00<00:50,  1.93it/s, loss=50.4140]

SVI:   3%|▎         | 3/100 [00:00<00:50,  1.93it/s, loss=51.0875]

SVI:   4%|▍         | 4/100 [00:00<00:49,  1.93it/s, loss=48.3569]

SVI:   5%|▌         | 5/100 [00:00<00:49,  1.93it/s, loss=48.3502]

SVI:   6%|▌         | 6/100 [00:00<00:48,  1.93it/s, loss=48.1787]

SVI:   7%|▋         | 7/100 [00:00<00:48,  1.93it/s, loss=48.9230]

SVI:   8%|▊         | 8/100 [00:00<00:47,  1.93it/s, loss=48.3863]

SVI:   9%|▉         | 9/100 [00:00<00:47,  1.93it/s, loss=46.8361]

SVI:  10%|█         | 10/100 [00:00<00:46,  1.93it/s, loss=47.4982]

SVI:  11%|█         | 11/100 [00:00<00:46,  1.93it/s, loss=48.0759]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.93it/s, loss=46.6235]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.93it/s, loss=47.1952]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.93it/s, loss=45.7671]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.93it/s, loss=46.8720]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.93it/s, loss=46.3750]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.93it/s, loss=47.8245]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.93it/s, loss=47.9196]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.93it/s, loss=47.0137]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.93it/s, loss=47.8573]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.93it/s, loss=45.8431]

SVI:  22%|██▏       | 22/100 [00:00<00:40,  1.93it/s, loss=46.2527]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.93it/s, loss=46.9061]

SVI:  24%|██▍       | 24/100 [00:00<00:39,  1.93it/s, loss=46.0105]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.93it/s, loss=46.6939]

SVI:  26%|██▌       | 26/100 [00:00<00:38,  1.93it/s, loss=45.7861]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.93it/s, loss=47.1749]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.93it/s, loss=43.7510]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.93it/s, loss=45.6381]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.93it/s, loss=47.4361]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.93it/s, loss=44.0466]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.93it/s, loss=45.9502]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.93it/s, loss=46.8382]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.93it/s, loss=46.5698]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.93it/s, loss=46.1836]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.93it/s, loss=44.1024]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.93it/s, loss=46.1040]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.93it/s, loss=44.9269]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.93it/s, loss=44.8829]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.93it/s, loss=46.1332]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.93it/s, loss=46.7296]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.93it/s, loss=46.0987]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.93it/s, loss=46.2413]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.93it/s, loss=45.9179]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.93it/s, loss=45.8853]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.93it/s, loss=44.2815]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.93it/s, loss=46.6659]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.93it/s, loss=46.2200]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.93it/s, loss=46.3614]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.93it/s, loss=45.0197]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.93it/s, loss=44.8561]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.93it/s, loss=44.9439]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.93it/s, loss=45.0115]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.93it/s, loss=46.0649]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.93it/s, loss=45.6216]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.93it/s, loss=42.7544]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.93it/s, loss=45.9467]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.93it/s, loss=44.5260]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.93it/s, loss=45.6089]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.93it/s, loss=46.3718]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.93it/s, loss=46.5239]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.93it/s, loss=44.1408]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.93it/s, loss=43.7555]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.93it/s, loss=45.4903]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.93it/s, loss=45.8857]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.93it/s, loss=46.0365]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.93it/s, loss=46.4365]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.93it/s, loss=45.9662]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.93it/s, loss=46.4121]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.93it/s, loss=44.6535]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.93it/s, loss=43.7969]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.93it/s, loss=44.6260]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.93it/s, loss=45.9383]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.93it/s, loss=42.0608]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.93it/s, loss=45.6008]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.93it/s, loss=44.4856]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.93it/s, loss=45.4469]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.93it/s, loss=43.1664]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.93it/s, loss=44.8746]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.93it/s, loss=44.3380]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.93it/s, loss=45.2013]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.93it/s, loss=45.2049]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.93it/s, loss=45.4128]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.93it/s, loss=44.8509]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.93it/s, loss=45.8918]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.93it/s, loss=44.8236]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.93it/s, loss=42.7025]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.93it/s, loss=44.7284]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.93it/s, loss=45.0707]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.93it/s, loss=45.4101]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.93it/s, loss=45.4166]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.93it/s, loss=44.9203]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.93it/s, loss=45.8925]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.93it/s, loss=45.4621]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.93it/s, loss=42.3620]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.93it/s, loss=45.7958]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.93it/s, loss=44.3966]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.93it/s, loss=45.1742]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.93it/s, loss=44.5466]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.93it/s, loss=45.1841]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 32. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.91it/s]

SVI:   1%|          | 1/100 [00:00<00:51,  1.91it/s, loss=76.4944]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.91it/s, loss=74.1183]

SVI:   3%|▎         | 3/100 [00:00<00:50,  1.91it/s, loss=70.2519]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.91it/s, loss=71.9534]

SVI:   5%|▌         | 5/100 [00:00<00:49,  1.91it/s, loss=71.9025]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.91it/s, loss=74.1212]

SVI:   7%|▋         | 7/100 [00:00<00:48,  1.91it/s, loss=76.8158]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.91it/s, loss=72.1055]

SVI:   9%|▉         | 9/100 [00:00<00:47,  1.91it/s, loss=71.7186]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.91it/s, loss=75.4887]

SVI:  11%|█         | 11/100 [00:00<00:46,  1.91it/s, loss=71.6961]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.91it/s, loss=72.7359]

SVI:  13%|█▎        | 13/100 [00:00<00:45,  1.91it/s, loss=71.6903]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.91it/s, loss=69.4866]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.91it/s, loss=71.3601]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.91it/s, loss=66.5684]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.91it/s, loss=68.2403]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.91it/s, loss=72.1017]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.91it/s, loss=68.4901]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.91it/s, loss=69.9685]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.91it/s, loss=71.7338]

SVI:  22%|██▏       | 22/100 [00:00<00:40,  1.91it/s, loss=66.4327]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.91it/s, loss=70.7010]

SVI:  24%|██▍       | 24/100 [00:00<00:39,  1.91it/s, loss=66.0205]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.91it/s, loss=69.1969]

SVI:  26%|██▌       | 26/100 [00:00<00:38,  1.91it/s, loss=69.4121]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.91it/s, loss=67.2570]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.91it/s, loss=68.5471]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.91it/s, loss=69.0852]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.91it/s, loss=65.3496]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.91it/s, loss=67.0843]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.91it/s, loss=68.8216]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.91it/s, loss=61.7886]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.91it/s, loss=68.7085]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.91it/s, loss=68.0587]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.91it/s, loss=66.0506]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.91it/s, loss=63.3321]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.91it/s, loss=64.4217]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.91it/s, loss=63.6247]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.91it/s, loss=67.3184]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.91it/s, loss=65.6929]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.91it/s, loss=63.6605]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.91it/s, loss=64.1710]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.91it/s, loss=66.4035]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.91it/s, loss=66.4476]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.91it/s, loss=64.8833]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.91it/s, loss=58.5304]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.91it/s, loss=61.5676]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.91it/s, loss=62.2605]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.91it/s, loss=64.0890]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.91it/s, loss=59.4138]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.91it/s, loss=61.3138]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.91it/s, loss=62.0206]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.91it/s, loss=61.3778]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.91it/s, loss=64.2661]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.91it/s, loss=60.0682]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.91it/s, loss=61.7992]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.91it/s, loss=60.5603]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.91it/s, loss=60.0453]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.91it/s, loss=60.2254]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.91it/s, loss=61.6384]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.91it/s, loss=58.3951]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.91it/s, loss=59.8838]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.91it/s, loss=63.0226]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.91it/s, loss=60.9725]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.91it/s, loss=56.0874]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.91it/s, loss=61.7413]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.91it/s, loss=60.9741]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.91it/s, loss=60.9202]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.91it/s, loss=59.7610]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.91it/s, loss=52.2687]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.91it/s, loss=59.4170]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.91it/s, loss=61.0073]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.91it/s, loss=58.5413]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.91it/s, loss=58.8051]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.91it/s, loss=55.7521]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.91it/s, loss=55.4269]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.91it/s, loss=58.1701]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.91it/s, loss=58.9249]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.91it/s, loss=58.7293]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.91it/s, loss=55.0247]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.91it/s, loss=56.7246]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.91it/s, loss=56.1338]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.91it/s, loss=59.1918]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.91it/s, loss=55.3009]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.91it/s, loss=57.4354]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.91it/s, loss=56.9799]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.91it/s, loss=56.7284]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.91it/s, loss=57.1785]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.91it/s, loss=56.1390]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.91it/s, loss=55.2709]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.91it/s, loss=51.8323]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.91it/s, loss=50.4286]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.91it/s, loss=58.1046]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.91it/s, loss=55.3692]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.91it/s, loss=54.5476]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.91it/s, loss=57.1393]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.91it/s, loss=56.9550]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.91it/s, loss=51.8065]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.91it/s, loss=55.6425]

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:49,  1.99it/s]

SVI:   1%|          | 1/100 [00:00<00:49,  1.99it/s, loss=51.4091]

SVI:   2%|▏         | 2/100 [00:00<00:49,  1.99it/s, loss=50.6334]

SVI:   3%|▎         | 3/100 [00:00<00:48,  1.99it/s, loss=46.5755]

SVI:   4%|▍         | 4/100 [00:00<00:48,  1.99it/s, loss=46.7410]

SVI:   5%|▌         | 5/100 [00:00<00:47,  1.99it/s, loss=40.9733]

SVI:   6%|▌         | 6/100 [00:00<00:47,  1.99it/s, loss=42.0074]

SVI:   7%|▋         | 7/100 [00:00<00:46,  1.99it/s, loss=46.6272]

SVI:   8%|▊         | 8/100 [00:00<00:46,  1.99it/s, loss=44.1010]

SVI:   9%|▉         | 9/100 [00:00<00:45,  1.99it/s, loss=47.7440]

SVI:  10%|█         | 10/100 [00:00<00:45,  1.99it/s, loss=44.5153]

SVI:  11%|█         | 11/100 [00:00<00:44,  1.99it/s, loss=46.7573]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.99it/s, loss=43.6204]

SVI:  13%|█▎        | 13/100 [00:00<00:43,  1.99it/s, loss=46.5312]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.99it/s, loss=42.7318]

SVI:  15%|█▌        | 15/100 [00:00<00:42,  1.99it/s, loss=38.3360]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.99it/s, loss=44.4796]

SVI:  17%|█▋        | 17/100 [00:00<00:41,  1.99it/s, loss=44.8733]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.99it/s, loss=43.1240]

SVI:  19%|█▉        | 19/100 [00:00<00:40,  1.99it/s, loss=42.4452]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.99it/s, loss=39.7132]

SVI:  21%|██        | 21/100 [00:00<00:39,  1.99it/s, loss=43.5657]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.99it/s, loss=43.0604]

SVI:  23%|██▎       | 23/100 [00:00<00:38,  1.99it/s, loss=44.0327]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.99it/s, loss=44.3255]

SVI:  25%|██▌       | 25/100 [00:00<00:37,  1.99it/s, loss=41.6211]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.99it/s, loss=42.6124]

SVI:  27%|██▋       | 27/100 [00:00<00:36,  1.99it/s, loss=41.0134]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.99it/s, loss=42.4914]

SVI:  29%|██▉       | 29/100 [00:00<00:35,  1.99it/s, loss=42.2970]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.99it/s, loss=39.6698]

SVI:  31%|███       | 31/100 [00:00<00:34,  1.99it/s, loss=41.9555]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.99it/s, loss=42.6574]

SVI:  33%|███▎      | 33/100 [00:00<00:33,  1.99it/s, loss=42.5732]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.99it/s, loss=41.8851]

SVI:  35%|███▌      | 35/100 [00:00<00:32,  1.99it/s, loss=43.0046]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.99it/s, loss=41.7182]

SVI:  37%|███▋      | 37/100 [00:00<00:31,  1.99it/s, loss=42.3289]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.99it/s, loss=39.8847]

SVI:  39%|███▉      | 39/100 [00:00<00:30,  1.99it/s, loss=36.7491]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.99it/s, loss=37.4149]

SVI:  41%|████      | 41/100 [00:00<00:29,  1.99it/s, loss=41.3454]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.99it/s, loss=40.9176]

SVI:  43%|████▎     | 43/100 [00:00<00:28,  1.99it/s, loss=41.7064]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.99it/s, loss=40.6063]

SVI:  45%|████▌     | 45/100 [00:00<00:27,  1.99it/s, loss=42.0405]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.99it/s, loss=34.1178]

SVI:  47%|████▋     | 47/100 [00:00<00:26,  1.99it/s, loss=41.2406]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.99it/s, loss=41.3706]

SVI:  49%|████▉     | 49/100 [00:00<00:25,  1.99it/s, loss=39.0142]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.99it/s, loss=37.6537]

SVI:  51%|█████     | 51/100 [00:00<00:24,  1.99it/s, loss=41.0655]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.99it/s, loss=39.0520]

SVI:  53%|█████▎    | 53/100 [00:00<00:23,  1.99it/s, loss=41.0697]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.99it/s, loss=40.3280]

SVI:  55%|█████▌    | 55/100 [00:00<00:22,  1.99it/s, loss=40.7383]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.99it/s, loss=40.6571]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.99it/s, loss=40.9611]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.99it/s, loss=41.6304]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.99it/s, loss=40.2540]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.99it/s, loss=38.5828]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.99it/s, loss=41.4203]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.99it/s, loss=40.7762]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.99it/s, loss=39.9418]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.99it/s, loss=39.5136]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.99it/s, loss=39.6892]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.99it/s, loss=38.5948]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.99it/s, loss=39.2148]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.99it/s, loss=38.9952]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.99it/s, loss=39.4025]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.99it/s, loss=37.4254]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.99it/s, loss=38.1513]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.99it/s, loss=39.9964]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.99it/s, loss=37.5104]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.99it/s, loss=39.4073]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.99it/s, loss=40.8969]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.99it/s, loss=38.6154]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.99it/s, loss=40.4247]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.99it/s, loss=39.0048]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.99it/s, loss=37.5765]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.99it/s, loss=37.8059]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.99it/s, loss=40.7789]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.99it/s, loss=38.4189]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.99it/s, loss=40.1544]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.99it/s, loss=38.5432]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.99it/s, loss=39.6498]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.99it/s, loss=39.9446]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.99it/s, loss=38.2813]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.99it/s, loss=39.0161]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.99it/s, loss=39.2280]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.99it/s, loss=39.9901]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.99it/s, loss=38.8910]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.99it/s, loss=38.3770]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.99it/s, loss=38.2737]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.99it/s, loss=38.0128]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.99it/s, loss=39.3540]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.99it/s, loss=37.1457]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.99it/s, loss=39.7848]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.99it/s, loss=37.0677]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.99it/s, loss=39.0078]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.99it/s, loss=36.6313]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 58. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.90it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.90it/s, loss=98.9662]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.90it/s, loss=92.1765]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.90it/s, loss=90.5426]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.90it/s, loss=94.4493]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.90it/s, loss=91.5067]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.90it/s, loss=90.2086]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.90it/s, loss=92.2573]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.90it/s, loss=96.3735]

SVI:   9%|▉         | 9/100 [00:00<00:47,  1.90it/s, loss=89.0093]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.90it/s, loss=91.0680]

SVI:  11%|█         | 11/100 [00:00<00:46,  1.90it/s, loss=85.7168]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.90it/s, loss=90.3786]

SVI:  13%|█▎        | 13/100 [00:00<00:45,  1.90it/s, loss=88.6293]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.90it/s, loss=89.1873]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.90it/s, loss=90.0448]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.90it/s, loss=86.9280]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.90it/s, loss=85.3570]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.90it/s, loss=89.7347]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.90it/s, loss=85.7861]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.90it/s, loss=86.2530]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.90it/s, loss=86.5313]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.90it/s, loss=87.0043]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.90it/s, loss=83.7915]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.90it/s, loss=85.7253]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.90it/s, loss=83.6995]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.90it/s, loss=85.4884]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.90it/s, loss=85.5832]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.90it/s, loss=84.5953]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.90it/s, loss=86.5952]

SVI:  30%|███       | 30/100 [00:00<00:36,  1.90it/s, loss=85.2621]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.90it/s, loss=83.5340]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.90it/s, loss=85.5259]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.90it/s, loss=84.9560]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.90it/s, loss=84.6944]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.90it/s, loss=83.9226]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.90it/s, loss=84.8037]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.90it/s, loss=85.2045]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.90it/s, loss=84.4792]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.90it/s, loss=81.1171]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.90it/s, loss=80.9240]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.90it/s, loss=82.3377]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.90it/s, loss=82.5437]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.90it/s, loss=83.7899]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.90it/s, loss=83.7570]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.90it/s, loss=81.8698]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.90it/s, loss=82.5209]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.90it/s, loss=80.6223]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.90it/s, loss=83.4837]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.90it/s, loss=78.7732]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.90it/s, loss=81.8470]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.90it/s, loss=83.5114]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.90it/s, loss=83.4696]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.90it/s, loss=84.4524]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.90it/s, loss=80.9088]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.90it/s, loss=81.9793]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.90it/s, loss=81.1129]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.90it/s, loss=83.4691]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.90it/s, loss=82.4130]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.90it/s, loss=81.8272]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.90it/s, loss=81.3075]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.90it/s, loss=83.2699]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.90it/s, loss=82.4448]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.90it/s, loss=81.9872]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.90it/s, loss=81.7709]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.90it/s, loss=82.5896]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.90it/s, loss=80.4860]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.90it/s, loss=82.1431]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.90it/s, loss=80.0254]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.90it/s, loss=81.6233]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.90it/s, loss=81.4103]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.90it/s, loss=80.3061]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.90it/s, loss=79.4266]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.90it/s, loss=81.0111]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.90it/s, loss=76.7700]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.90it/s, loss=80.7970]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.90it/s, loss=81.4455]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.90it/s, loss=79.8694]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.90it/s, loss=81.5838]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.90it/s, loss=78.8437]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.90it/s, loss=81.0222]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.90it/s, loss=79.0528]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.90it/s, loss=81.7835]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.90it/s, loss=79.6267]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.90it/s, loss=80.3262]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.90it/s, loss=78.3531]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.90it/s, loss=79.5910]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.90it/s, loss=80.7116]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.90it/s, loss=80.9663]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.90it/s, loss=80.4676]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.90it/s, loss=80.0377]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.90it/s, loss=80.8430]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.90it/s, loss=78.8667]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.90it/s, loss=80.7234]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.90it/s, loss=79.1666]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.90it/s, loss=82.3398]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.90it/s, loss=80.6228]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.90it/s, loss=80.2706]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.90it/s, loss=80.2353]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.90it/s, loss=80.4174]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.90it/s, loss=79.0247]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 17. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s, loss=26.9306]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.89it/s, loss=25.6912]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.89it/s, loss=25.8285]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.89it/s, loss=27.1916]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.89it/s, loss=27.1303]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.89it/s, loss=24.7805]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.89it/s, loss=25.7430]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.89it/s, loss=24.8155]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.89it/s, loss=24.5919]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.89it/s, loss=26.2157]

SVI:  11%|█         | 11/100 [00:00<00:47,  1.89it/s, loss=26.1046]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.89it/s, loss=24.8633]

SVI:  13%|█▎        | 13/100 [00:00<00:46,  1.89it/s, loss=26.4242]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.89it/s, loss=26.7050]

SVI:  15%|█▌        | 15/100 [00:00<00:44,  1.89it/s, loss=26.2721]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.89it/s, loss=26.5074]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.89it/s, loss=25.1429]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.89it/s, loss=24.3772]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.89it/s, loss=25.1436]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.89it/s, loss=24.7004]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.89it/s, loss=24.2819]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.89it/s, loss=24.9808]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.89it/s, loss=26.1100]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.89it/s, loss=25.6606]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.89it/s, loss=26.3621]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.89it/s, loss=24.7338]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.89it/s, loss=25.7626]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.89it/s, loss=26.5191]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.89it/s, loss=26.0397]

SVI:  30%|███       | 30/100 [00:00<00:37,  1.89it/s, loss=26.0019]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.89it/s, loss=24.5292]

SVI:  32%|███▏      | 32/100 [00:00<00:35,  1.89it/s, loss=24.9043]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.89it/s, loss=25.5565]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.89it/s, loss=25.9747]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.89it/s, loss=25.2243]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.89it/s, loss=25.7753]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.89it/s, loss=25.4436]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.89it/s, loss=25.7039]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.89it/s, loss=25.2403]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.89it/s, loss=25.2616]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.89it/s, loss=24.7490]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.89it/s, loss=25.3981]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.89it/s, loss=24.3699]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.89it/s, loss=23.4003]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.89it/s, loss=25.8224]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.89it/s, loss=24.6460]

SVI:  47%|████▋     | 47/100 [00:00<00:28,  1.89it/s, loss=25.2649]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.89it/s, loss=24.9279]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.89it/s, loss=23.4733]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.89it/s, loss=23.5297]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.89it/s, loss=24.1133]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.89it/s, loss=21.8159]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.89it/s, loss=25.2243]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.89it/s, loss=24.4930]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.89it/s, loss=25.4225]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.89it/s, loss=24.1484]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.89it/s, loss=24.6487]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.89it/s, loss=23.8816]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.89it/s, loss=23.0963]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.89it/s, loss=23.0227]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.89it/s, loss=25.3089]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.89it/s, loss=24.2070]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.89it/s, loss=24.8153]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.89it/s, loss=23.4971]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.89it/s, loss=24.9759]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.89it/s, loss=23.9120]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.89it/s, loss=23.7646]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.89it/s, loss=25.1715]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.89it/s, loss=22.9755]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.89it/s, loss=23.3024]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.89it/s, loss=23.9988]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.89it/s, loss=23.9663]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.89it/s, loss=25.0096]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.89it/s, loss=24.6367]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.89it/s, loss=24.8427]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.89it/s, loss=24.2025]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.89it/s, loss=25.2437]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.89it/s, loss=24.6073]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.89it/s, loss=24.2249]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.89it/s, loss=25.2154]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.89it/s, loss=24.6696]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.89it/s, loss=25.1604]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.89it/s, loss=24.6845]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.89it/s, loss=24.8749]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.89it/s, loss=25.0386]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.89it/s, loss=24.8917]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.89it/s, loss=24.7640]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.89it/s, loss=24.6294]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.89it/s, loss=24.4484]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.89it/s, loss=24.5503]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.89it/s, loss=23.3928]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.89it/s, loss=24.1591]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.89it/s, loss=24.2304]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.89it/s, loss=24.3946]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.89it/s, loss=24.4780]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.89it/s, loss=24.4401]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.89it/s, loss=23.3312]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.89it/s, loss=23.4299]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.89it/s, loss=24.5587]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.89it/s, loss=23.3010]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 25. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:49,  1.99it/s]

SVI:   1%|          | 1/100 [00:00<00:49,  1.99it/s, loss=27.1388]

SVI:   2%|▏         | 2/100 [00:00<00:49,  1.99it/s, loss=24.1258]

SVI:   3%|▎         | 3/100 [00:00<00:48,  1.99it/s, loss=25.6629]

SVI:   4%|▍         | 4/100 [00:00<00:48,  1.99it/s, loss=30.1649]

SVI:   5%|▌         | 5/100 [00:00<00:47,  1.99it/s, loss=28.2269]

SVI:   6%|▌         | 6/100 [00:00<00:47,  1.99it/s, loss=22.9648]

SVI:   7%|▋         | 7/100 [00:00<00:46,  1.99it/s, loss=30.5774]

SVI:   8%|▊         | 8/100 [00:00<00:46,  1.99it/s, loss=25.8858]

SVI:   9%|▉         | 9/100 [00:00<00:45,  1.99it/s, loss=28.0904]

SVI:  10%|█         | 10/100 [00:00<00:45,  1.99it/s, loss=24.9242]

SVI:  11%|█         | 11/100 [00:00<00:44,  1.99it/s, loss=25.2859]

SVI:  12%|█▏        | 12/100 [00:00<00:44,  1.99it/s, loss=26.3496]

SVI:  13%|█▎        | 13/100 [00:00<00:43,  1.99it/s, loss=24.8726]

SVI:  14%|█▍        | 14/100 [00:00<00:43,  1.99it/s, loss=22.0954]

SVI:  15%|█▌        | 15/100 [00:00<00:42,  1.99it/s, loss=23.3638]

SVI:  16%|█▌        | 16/100 [00:00<00:42,  1.99it/s, loss=20.6298]

SVI:  17%|█▋        | 17/100 [00:00<00:41,  1.99it/s, loss=22.7969]

SVI:  18%|█▊        | 18/100 [00:00<00:41,  1.99it/s, loss=23.5682]

SVI:  19%|█▉        | 19/100 [00:00<00:40,  1.99it/s, loss=24.1244]

SVI:  20%|██        | 20/100 [00:00<00:40,  1.99it/s, loss=21.6293]

SVI:  21%|██        | 21/100 [00:00<00:39,  1.99it/s, loss=21.2145]

SVI:  22%|██▏       | 22/100 [00:00<00:39,  1.99it/s, loss=21.2578]

SVI:  23%|██▎       | 23/100 [00:00<00:38,  1.99it/s, loss=21.3788]

SVI:  24%|██▍       | 24/100 [00:00<00:38,  1.99it/s, loss=21.3990]

SVI:  25%|██▌       | 25/100 [00:00<00:37,  1.99it/s, loss=21.7853]

SVI:  26%|██▌       | 26/100 [00:00<00:37,  1.99it/s, loss=21.3919]

SVI:  27%|██▋       | 27/100 [00:00<00:36,  1.99it/s, loss=21.4123]

SVI:  28%|██▊       | 28/100 [00:00<00:36,  1.99it/s, loss=21.2494]

SVI:  29%|██▉       | 29/100 [00:00<00:35,  1.99it/s, loss=21.8418]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.99it/s, loss=20.7950]

SVI:  31%|███       | 31/100 [00:00<00:34,  1.99it/s, loss=22.1707]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.99it/s, loss=18.2845]

SVI:  33%|███▎      | 33/100 [00:00<00:33,  1.99it/s, loss=22.2570]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.99it/s, loss=19.3063]

SVI:  35%|███▌      | 35/100 [00:00<00:32,  1.99it/s, loss=19.8637]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.99it/s, loss=20.2366]

SVI:  37%|███▋      | 37/100 [00:00<00:31,  1.99it/s, loss=20.9281]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.99it/s, loss=20.2055]

SVI:  39%|███▉      | 39/100 [00:00<00:30,  1.99it/s, loss=21.2009]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.99it/s, loss=19.9481]

SVI:  41%|████      | 41/100 [00:00<00:29,  1.99it/s, loss=21.2033]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.99it/s, loss=18.7514]

SVI:  43%|████▎     | 43/100 [00:00<00:28,  1.99it/s, loss=18.6512]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.99it/s, loss=15.6264]

SVI:  45%|████▌     | 45/100 [00:00<00:27,  1.99it/s, loss=20.8717]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.99it/s, loss=21.6750]

SVI:  47%|████▋     | 47/100 [00:00<00:26,  1.99it/s, loss=19.0302]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.99it/s, loss=19.5847]

SVI:  49%|████▉     | 49/100 [00:00<00:25,  1.99it/s, loss=20.5754]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.99it/s, loss=15.4379]

SVI:  51%|█████     | 51/100 [00:00<00:24,  1.99it/s, loss=18.7206]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.99it/s, loss=20.0151]

SVI:  53%|█████▎    | 53/100 [00:00<00:23,  1.99it/s, loss=18.4122]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.99it/s, loss=19.6177]

SVI:  55%|█████▌    | 55/100 [00:00<00:22,  1.99it/s, loss=20.0444]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.99it/s, loss=17.6396]

SVI:  57%|█████▋    | 57/100 [00:00<00:21,  1.99it/s, loss=20.5841]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.99it/s, loss=18.4431]

SVI:  59%|█████▉    | 59/100 [00:00<00:20,  1.99it/s, loss=20.3983]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.99it/s, loss=19.2537]

SVI:  61%|██████    | 61/100 [00:00<00:19,  1.99it/s, loss=19.8246]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.99it/s, loss=20.2630]

SVI:  63%|██████▎   | 63/100 [00:00<00:18,  1.99it/s, loss=19.4983]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.99it/s, loss=19.8105]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.99it/s, loss=19.3090]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.99it/s, loss=17.5796]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.99it/s, loss=16.0775]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.99it/s, loss=18.8147]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.99it/s, loss=18.3267]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.99it/s, loss=20.6647]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.99it/s, loss=20.5343]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.99it/s, loss=18.8271]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.99it/s, loss=19.2393]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.99it/s, loss=17.7474]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.99it/s, loss=18.6858]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.99it/s, loss=18.1321]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.99it/s, loss=15.9604]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.99it/s, loss=19.4585]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.99it/s, loss=19.4583]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.99it/s, loss=18.6077]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.99it/s, loss=19.8034]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.99it/s, loss=19.8909]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.99it/s, loss=19.3119]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.99it/s, loss=19.4541]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.99it/s, loss=18.6233]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.99it/s, loss=18.5408]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.99it/s, loss=19.0194]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.99it/s, loss=18.0549]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.99it/s, loss=18.6629]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.99it/s, loss=18.7968]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.99it/s, loss=18.4914]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.99it/s, loss=18.2772]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.99it/s, loss=17.4126]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.99it/s, loss=17.6613]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.99it/s, loss=16.4965]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.99it/s, loss=17.3180]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.99it/s, loss=18.9327]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.99it/s, loss=18.5959]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.99it/s, loss=17.8457]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.99it/s, loss=19.0231]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 47. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s]

SVI:   1%|          | 1/100 [00:00<00:52,  1.89it/s, loss=77.4516]

SVI:   2%|▏         | 2/100 [00:00<00:51,  1.89it/s, loss=80.3416]

SVI:   3%|▎         | 3/100 [00:00<00:51,  1.89it/s, loss=82.8893]

SVI:   4%|▍         | 4/100 [00:00<00:50,  1.89it/s, loss=79.9446]

SVI:   5%|▌         | 5/100 [00:00<00:50,  1.89it/s, loss=78.9064]

SVI:   6%|▌         | 6/100 [00:00<00:49,  1.89it/s, loss=76.4541]

SVI:   7%|▋         | 7/100 [00:00<00:49,  1.89it/s, loss=79.9485]

SVI:   8%|▊         | 8/100 [00:00<00:48,  1.89it/s, loss=80.6941]

SVI:   9%|▉         | 9/100 [00:00<00:48,  1.89it/s, loss=74.1462]

SVI:  10%|█         | 10/100 [00:00<00:47,  1.89it/s, loss=79.6252]

SVI:  11%|█         | 11/100 [00:00<00:47,  1.89it/s, loss=77.5147]

SVI:  12%|█▏        | 12/100 [00:00<00:46,  1.89it/s, loss=79.3421]

SVI:  13%|█▎        | 13/100 [00:00<00:46,  1.89it/s, loss=77.8160]

SVI:  14%|█▍        | 14/100 [00:00<00:45,  1.89it/s, loss=76.8021]

SVI:  15%|█▌        | 15/100 [00:00<00:45,  1.89it/s, loss=75.5055]

SVI:  16%|█▌        | 16/100 [00:00<00:44,  1.89it/s, loss=78.4114]

SVI:  17%|█▋        | 17/100 [00:00<00:43,  1.89it/s, loss=77.5711]

SVI:  18%|█▊        | 18/100 [00:00<00:43,  1.89it/s, loss=77.2421]

SVI:  19%|█▉        | 19/100 [00:00<00:42,  1.89it/s, loss=75.0247]

SVI:  20%|██        | 20/100 [00:00<00:42,  1.89it/s, loss=78.2099]

SVI:  21%|██        | 21/100 [00:00<00:41,  1.89it/s, loss=78.4070]

SVI:  22%|██▏       | 22/100 [00:00<00:41,  1.89it/s, loss=76.0667]

SVI:  23%|██▎       | 23/100 [00:00<00:40,  1.89it/s, loss=77.6907]

SVI:  24%|██▍       | 24/100 [00:00<00:40,  1.89it/s, loss=77.4226]

SVI:  25%|██▌       | 25/100 [00:00<00:39,  1.89it/s, loss=76.3616]

SVI:  26%|██▌       | 26/100 [00:00<00:39,  1.89it/s, loss=76.5240]

SVI:  27%|██▋       | 27/100 [00:00<00:38,  1.89it/s, loss=77.3522]

SVI:  28%|██▊       | 28/100 [00:00<00:38,  1.89it/s, loss=76.9893]

SVI:  29%|██▉       | 29/100 [00:00<00:37,  1.89it/s, loss=76.3867]

SVI:  30%|███       | 30/100 [00:00<00:37,  1.89it/s, loss=72.8450]

SVI:  31%|███       | 31/100 [00:00<00:36,  1.89it/s, loss=73.9259]

SVI:  32%|███▏      | 32/100 [00:00<00:36,  1.89it/s, loss=76.3384]

SVI:  33%|███▎      | 33/100 [00:00<00:35,  1.89it/s, loss=73.9573]

SVI:  34%|███▍      | 34/100 [00:00<00:34,  1.89it/s, loss=75.1451]

SVI:  35%|███▌      | 35/100 [00:00<00:34,  1.89it/s, loss=75.1521]

SVI:  36%|███▌      | 36/100 [00:00<00:33,  1.89it/s, loss=75.0073]

SVI:  37%|███▋      | 37/100 [00:00<00:33,  1.89it/s, loss=76.0961]

SVI:  38%|███▊      | 38/100 [00:00<00:32,  1.89it/s, loss=75.7520]

SVI:  39%|███▉      | 39/100 [00:00<00:32,  1.89it/s, loss=74.2132]

SVI:  40%|████      | 40/100 [00:00<00:31,  1.89it/s, loss=74.6431]

SVI:  41%|████      | 41/100 [00:00<00:31,  1.89it/s, loss=74.5372]

SVI:  42%|████▏     | 42/100 [00:00<00:30,  1.89it/s, loss=76.0035]

SVI:  43%|████▎     | 43/100 [00:00<00:30,  1.89it/s, loss=74.4840]

SVI:  44%|████▍     | 44/100 [00:00<00:29,  1.89it/s, loss=72.4445]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.89it/s, loss=73.0908]

SVI:  46%|████▌     | 46/100 [00:00<00:28,  1.89it/s, loss=73.5237]

SVI:  47%|████▋     | 47/100 [00:00<00:28,  1.89it/s, loss=74.3569]

SVI:  48%|████▊     | 48/100 [00:00<00:27,  1.89it/s, loss=73.8283]

SVI:  49%|████▉     | 49/100 [00:00<00:27,  1.89it/s, loss=72.9928]

SVI:  50%|█████     | 50/100 [00:00<00:26,  1.89it/s, loss=71.8702]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.89it/s, loss=72.0288]

SVI:  52%|█████▏    | 52/100 [00:00<00:25,  1.89it/s, loss=74.5405]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.89it/s, loss=73.1332]

SVI:  54%|█████▍    | 54/100 [00:00<00:24,  1.89it/s, loss=74.7352]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.89it/s, loss=73.3124]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.89it/s, loss=74.4853]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.89it/s, loss=74.3517]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.89it/s, loss=73.3286]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.89it/s, loss=72.8778]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.89it/s, loss=72.6289]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.89it/s, loss=73.0956]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.89it/s, loss=74.6992]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.89it/s, loss=74.1894]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.89it/s, loss=74.0949]

SVI:  65%|██████▌   | 65/100 [00:00<00:18,  1.89it/s, loss=72.7568]

SVI:  66%|██████▌   | 66/100 [00:00<00:18,  1.89it/s, loss=73.9893]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.89it/s, loss=72.8011]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.89it/s, loss=73.5094]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.89it/s, loss=73.2847]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.89it/s, loss=74.0106]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.89it/s, loss=72.0665]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.89it/s, loss=70.9977]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.89it/s, loss=70.9412]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.89it/s, loss=71.6279]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.89it/s, loss=72.7434]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.89it/s, loss=71.9483]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.89it/s, loss=72.1497]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.89it/s, loss=72.3778]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.89it/s, loss=73.1118]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.89it/s, loss=73.3237]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.89it/s, loss=69.6732]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.89it/s, loss=73.4104]

SVI:  83%|████████▎ | 83/100 [00:00<00:09,  1.89it/s, loss=70.6657]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.89it/s, loss=69.4962]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.89it/s, loss=72.8337]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.89it/s, loss=69.9703]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.89it/s, loss=71.9870]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.89it/s, loss=72.1234]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.89it/s, loss=70.8289]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.89it/s, loss=72.9193]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.89it/s, loss=72.0632]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.89it/s, loss=72.2753]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.89it/s, loss=72.0351]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.89it/s, loss=72.8646]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.89it/s, loss=70.5934]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.89it/s, loss=72.1798]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.89it/s, loss=69.9272]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.89it/s, loss=70.2492]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.89it/s, loss=70.3727]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.89it/s, loss=71.4070]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 30. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.94it/s]

SVI:   1%|          | 1/100 [00:00<00:50,  1.94it/s, loss=40.3437]

SVI:   2%|▏         | 2/100 [00:00<00:50,  1.94it/s, loss=37.4484]

SVI:   3%|▎         | 3/100 [00:00<00:49,  1.94it/s, loss=36.9754]

SVI:   4%|▍         | 4/100 [00:00<00:49,  1.94it/s, loss=38.9353]

SVI:   5%|▌         | 5/100 [00:00<00:48,  1.94it/s, loss=38.0857]

SVI:   6%|▌         | 6/100 [00:00<00:48,  1.94it/s, loss=37.2920]

SVI:   7%|▋         | 7/100 [00:00<00:47,  1.94it/s, loss=38.2636]

SVI:   8%|▊         | 8/100 [00:00<00:47,  1.94it/s, loss=36.2129]

SVI:   9%|▉         | 9/100 [00:00<00:46,  1.94it/s, loss=35.6315]

SVI:  10%|█         | 10/100 [00:00<00:46,  1.94it/s, loss=32.3044]

SVI:  11%|█         | 11/100 [00:00<00:45,  1.94it/s, loss=37.7315]

SVI:  12%|█▏        | 12/100 [00:00<00:45,  1.94it/s, loss=38.1037]

SVI:  13%|█▎        | 13/100 [00:00<00:44,  1.94it/s, loss=34.6781]

SVI:  14%|█▍        | 14/100 [00:00<00:44,  1.94it/s, loss=36.1939]

SVI:  15%|█▌        | 15/100 [00:00<00:43,  1.94it/s, loss=36.3009]

SVI:  16%|█▌        | 16/100 [00:00<00:43,  1.94it/s, loss=36.6016]

SVI:  17%|█▋        | 17/100 [00:00<00:42,  1.94it/s, loss=33.5981]

SVI:  18%|█▊        | 18/100 [00:00<00:42,  1.94it/s, loss=32.5422]

SVI:  19%|█▉        | 19/100 [00:00<00:41,  1.94it/s, loss=36.8512]

SVI:  20%|██        | 20/100 [00:00<00:41,  1.94it/s, loss=35.0770]

SVI:  21%|██        | 21/100 [00:00<00:40,  1.94it/s, loss=35.6292]

SVI:  22%|██▏       | 22/100 [00:00<00:40,  1.94it/s, loss=35.3442]

SVI:  23%|██▎       | 23/100 [00:00<00:39,  1.94it/s, loss=34.4422]

SVI:  24%|██▍       | 24/100 [00:00<00:39,  1.94it/s, loss=34.1321]

SVI:  25%|██▌       | 25/100 [00:00<00:38,  1.94it/s, loss=35.4437]

SVI:  26%|██▌       | 26/100 [00:00<00:38,  1.94it/s, loss=32.7749]

SVI:  27%|██▋       | 27/100 [00:00<00:37,  1.94it/s, loss=35.4370]

SVI:  28%|██▊       | 28/100 [00:00<00:37,  1.94it/s, loss=35.5179]

SVI:  29%|██▉       | 29/100 [00:00<00:36,  1.94it/s, loss=35.3061]

SVI:  30%|███       | 30/100 [00:00<00:35,  1.94it/s, loss=33.3569]

SVI:  31%|███       | 31/100 [00:00<00:35,  1.94it/s, loss=35.0075]

SVI:  32%|███▏      | 32/100 [00:00<00:34,  1.94it/s, loss=35.0897]

SVI:  33%|███▎      | 33/100 [00:00<00:34,  1.94it/s, loss=34.1382]

SVI:  34%|███▍      | 34/100 [00:00<00:33,  1.94it/s, loss=34.7113]

SVI:  35%|███▌      | 35/100 [00:00<00:33,  1.94it/s, loss=35.6407]

SVI:  36%|███▌      | 36/100 [00:00<00:32,  1.94it/s, loss=33.6481]

SVI:  37%|███▋      | 37/100 [00:00<00:32,  1.94it/s, loss=35.1309]

SVI:  38%|███▊      | 38/100 [00:00<00:31,  1.94it/s, loss=33.4173]

SVI:  39%|███▉      | 39/100 [00:00<00:31,  1.94it/s, loss=34.2360]

SVI:  40%|████      | 40/100 [00:00<00:30,  1.94it/s, loss=34.1675]

SVI:  41%|████      | 41/100 [00:00<00:30,  1.94it/s, loss=32.8543]

SVI:  42%|████▏     | 42/100 [00:00<00:29,  1.94it/s, loss=34.5590]

SVI:  43%|████▎     | 43/100 [00:00<00:29,  1.94it/s, loss=35.1167]

SVI:  44%|████▍     | 44/100 [00:00<00:28,  1.94it/s, loss=34.5952]

SVI:  45%|████▌     | 45/100 [00:00<00:28,  1.94it/s, loss=34.6288]

SVI:  46%|████▌     | 46/100 [00:00<00:27,  1.94it/s, loss=32.7932]

SVI:  47%|████▋     | 47/100 [00:00<00:27,  1.94it/s, loss=32.0706]

SVI:  48%|████▊     | 48/100 [00:00<00:26,  1.94it/s, loss=34.5340]

SVI:  49%|████▉     | 49/100 [00:00<00:26,  1.94it/s, loss=32.1690]

SVI:  50%|█████     | 50/100 [00:00<00:25,  1.94it/s, loss=33.2145]

SVI:  51%|█████     | 51/100 [00:00<00:25,  1.94it/s, loss=33.1627]

SVI:  52%|█████▏    | 52/100 [00:00<00:24,  1.94it/s, loss=34.1092]

SVI:  53%|█████▎    | 53/100 [00:00<00:24,  1.94it/s, loss=32.4086]

SVI:  54%|█████▍    | 54/100 [00:00<00:23,  1.94it/s, loss=34.4657]

SVI:  55%|█████▌    | 55/100 [00:00<00:23,  1.94it/s, loss=32.8939]

SVI:  56%|█████▌    | 56/100 [00:00<00:22,  1.94it/s, loss=32.4531]

SVI:  57%|█████▋    | 57/100 [00:00<00:22,  1.94it/s, loss=33.9451]

SVI:  58%|█████▊    | 58/100 [00:00<00:21,  1.94it/s, loss=33.2316]

SVI:  59%|█████▉    | 59/100 [00:00<00:21,  1.94it/s, loss=33.2259]

SVI:  60%|██████    | 60/100 [00:00<00:20,  1.94it/s, loss=32.9779]

SVI:  61%|██████    | 61/100 [00:00<00:20,  1.94it/s, loss=31.8887]

SVI:  62%|██████▏   | 62/100 [00:00<00:19,  1.94it/s, loss=33.4191]

SVI:  63%|██████▎   | 63/100 [00:00<00:19,  1.94it/s, loss=30.4338]

SVI:  64%|██████▍   | 64/100 [00:00<00:18,  1.94it/s, loss=32.5598]

SVI:  65%|██████▌   | 65/100 [00:00<00:17,  1.94it/s, loss=33.7051]

SVI:  66%|██████▌   | 66/100 [00:00<00:17,  1.94it/s, loss=34.3401]

SVI:  67%|██████▋   | 67/100 [00:00<00:16,  1.94it/s, loss=31.9192]

SVI:  68%|██████▊   | 68/100 [00:00<00:16,  1.94it/s, loss=32.7060]

SVI:  69%|██████▉   | 69/100 [00:00<00:15,  1.94it/s, loss=34.0270]

SVI:  70%|███████   | 70/100 [00:00<00:15,  1.94it/s, loss=30.8431]

SVI:  71%|███████   | 71/100 [00:00<00:14,  1.94it/s, loss=33.0660]

SVI:  72%|███████▏  | 72/100 [00:00<00:14,  1.94it/s, loss=32.0593]

SVI:  73%|███████▎  | 73/100 [00:00<00:13,  1.94it/s, loss=33.1251]

SVI:  74%|███████▍  | 74/100 [00:00<00:13,  1.94it/s, loss=32.9702]

SVI:  75%|███████▌  | 75/100 [00:00<00:12,  1.94it/s, loss=32.0200]

SVI:  76%|███████▌  | 76/100 [00:00<00:12,  1.94it/s, loss=34.2101]

SVI:  77%|███████▋  | 77/100 [00:00<00:11,  1.94it/s, loss=32.8384]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.94it/s, loss=29.9378]

SVI:  79%|███████▉  | 79/100 [00:00<00:10,  1.94it/s, loss=31.8871]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.94it/s, loss=33.2300]

SVI:  81%|████████  | 81/100 [00:00<00:09,  1.94it/s, loss=34.2564]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.94it/s, loss=31.1328]

SVI:  83%|████████▎ | 83/100 [00:00<00:08,  1.94it/s, loss=32.1230]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.94it/s, loss=32.9273]

SVI:  85%|████████▌ | 85/100 [00:00<00:07,  1.94it/s, loss=32.5982]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.94it/s, loss=34.4486]

SVI:  87%|████████▋ | 87/100 [00:00<00:06,  1.94it/s, loss=32.3087]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.94it/s, loss=33.7437]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.94it/s, loss=33.1754]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.94it/s, loss=34.1282]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.94it/s, loss=33.9162]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.94it/s, loss=33.0231]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.94it/s, loss=30.8647]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.94it/s, loss=33.2035]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.94it/s, loss=33.2462]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.94it/s, loss=31.9457]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.94it/s, loss=33.2071]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.94it/s, loss=33.1085]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.94it/s, loss=33.2181]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.94it/s, loss=32.7420]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 128 vs 23. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:00<00:53,  1.84it/s]

SVI:   1%|          | 1/100 [00:00<00:53,  1.84it/s, loss=18.1474]

SVI:   2%|▏         | 2/100 [00:00<00:53,  1.84it/s, loss=15.3678]

SVI:   3%|▎         | 3/100 [00:00<00:52,  1.84it/s, loss=17.9031]

SVI:   4%|▍         | 4/100 [00:00<00:52,  1.84it/s, loss=14.2614]

SVI:   5%|▌         | 5/100 [00:00<00:51,  1.84it/s, loss=16.8982]

SVI:   6%|▌         | 6/100 [00:00<00:51,  1.84it/s, loss=11.3244]

SVI:   7%|▋         | 7/100 [00:00<00:50,  1.84it/s, loss=16.9390]

SVI:   8%|▊         | 8/100 [00:00<00:50,  1.84it/s, loss=15.8051]

SVI:   9%|▉         | 9/100 [00:00<00:49,  1.84it/s, loss=16.1950]

SVI:  10%|█         | 10/100 [00:00<00:49,  1.84it/s, loss=13.5143]

SVI:  11%|█         | 11/100 [00:00<00:48,  1.84it/s, loss=14.9897]

SVI:  12%|█▏        | 12/100 [00:00<00:47,  1.84it/s, loss=13.6540]

SVI:  13%|█▎        | 13/100 [00:00<00:47,  1.84it/s, loss=15.0859]

SVI:  14%|█▍        | 14/100 [00:00<00:46,  1.84it/s, loss=16.0558]

SVI:  15%|█▌        | 15/100 [00:00<00:46,  1.84it/s, loss=15.4802]

SVI:  16%|█▌        | 16/100 [00:00<00:45,  1.84it/s, loss=14.3487]

SVI:  17%|█▋        | 17/100 [00:00<00:45,  1.84it/s, loss=13.5626]

SVI:  18%|█▊        | 18/100 [00:00<00:44,  1.84it/s, loss=13.4703]

SVI:  19%|█▉        | 19/100 [00:00<00:44,  1.84it/s, loss=13.5493]

SVI:  20%|██        | 20/100 [00:00<00:43,  1.84it/s, loss=14.6657]

SVI:  21%|██        | 21/100 [00:00<00:43,  1.84it/s, loss=14.5401]

SVI:  22%|██▏       | 22/100 [00:00<00:42,  1.84it/s, loss=13.8575]

SVI:  23%|██▎       | 23/100 [00:00<00:41,  1.84it/s, loss=14.1189]

SVI:  24%|██▍       | 24/100 [00:00<00:41,  1.84it/s, loss=13.9213]

SVI:  25%|██▌       | 25/100 [00:00<00:40,  1.84it/s, loss=13.7939]

SVI:  26%|██▌       | 26/100 [00:00<00:40,  1.84it/s, loss=14.1924]

SVI:  27%|██▋       | 27/100 [00:00<00:39,  1.84it/s, loss=14.6444]

SVI:  28%|██▊       | 28/100 [00:00<00:39,  1.84it/s, loss=14.6271]

SVI:  29%|██▉       | 29/100 [00:00<00:38,  1.84it/s, loss=13.2287]

SVI:  30%|███       | 30/100 [00:00<00:38,  1.84it/s, loss=13.5332]

SVI:  31%|███       | 31/100 [00:00<00:37,  1.84it/s, loss=13.9409]

SVI:  32%|███▏      | 32/100 [00:00<00:37,  1.84it/s, loss=14.6102]

SVI:  33%|███▎      | 33/100 [00:00<00:36,  1.84it/s, loss=13.9318]

SVI:  34%|███▍      | 34/100 [00:00<00:35,  1.84it/s, loss=14.8274]

SVI:  35%|███▌      | 35/100 [00:00<00:35,  1.84it/s, loss=14.7901]

SVI:  36%|███▌      | 36/100 [00:00<00:34,  1.84it/s, loss=13.5304]

SVI:  37%|███▋      | 37/100 [00:00<00:34,  1.84it/s, loss=12.0707]

SVI:  38%|███▊      | 38/100 [00:00<00:33,  1.84it/s, loss=14.1169]

SVI:  39%|███▉      | 39/100 [00:00<00:33,  1.84it/s, loss=13.5044]

SVI:  40%|████      | 40/100 [00:00<00:32,  1.84it/s, loss=13.5551]

SVI:  41%|████      | 41/100 [00:00<00:32,  1.84it/s, loss=13.7506]

SVI:  42%|████▏     | 42/100 [00:00<00:31,  1.84it/s, loss=14.0067]

SVI:  43%|████▎     | 43/100 [00:00<00:31,  1.84it/s, loss=13.3540]

SVI:  44%|████▍     | 44/100 [00:00<00:30,  1.84it/s, loss=13.2616]

SVI:  45%|████▌     | 45/100 [00:00<00:29,  1.84it/s, loss=13.0334]

SVI:  46%|████▌     | 46/100 [00:00<00:29,  1.84it/s, loss=12.5661]

SVI:  47%|████▋     | 47/100 [00:00<00:28,  1.84it/s, loss=14.4291]

SVI:  48%|████▊     | 48/100 [00:00<00:28,  1.84it/s, loss=13.6166]

SVI:  49%|████▉     | 49/100 [00:00<00:27,  1.84it/s, loss=12.6765]

SVI:  50%|█████     | 50/100 [00:00<00:27,  1.84it/s, loss=12.6900]

SVI:  51%|█████     | 51/100 [00:00<00:26,  1.84it/s, loss=12.4876]

SVI:  52%|█████▏    | 52/100 [00:00<00:26,  1.84it/s, loss=13.1710]

SVI:  53%|█████▎    | 53/100 [00:00<00:25,  1.84it/s, loss=12.1150]

SVI:  54%|█████▍    | 54/100 [00:00<00:25,  1.84it/s, loss=13.6300]

SVI:  55%|█████▌    | 55/100 [00:00<00:24,  1.84it/s, loss=13.7963]

SVI:  56%|█████▌    | 56/100 [00:00<00:23,  1.84it/s, loss=13.6244]

SVI:  57%|█████▋    | 57/100 [00:00<00:23,  1.84it/s, loss=14.0934]

SVI:  58%|█████▊    | 58/100 [00:00<00:22,  1.84it/s, loss=13.5487]

SVI:  59%|█████▉    | 59/100 [00:00<00:22,  1.84it/s, loss=13.1669]

SVI:  60%|██████    | 60/100 [00:00<00:21,  1.84it/s, loss=12.9859]

SVI:  61%|██████    | 61/100 [00:00<00:21,  1.84it/s, loss=13.4912]

SVI:  62%|██████▏   | 62/100 [00:00<00:20,  1.84it/s, loss=13.4500]

SVI:  63%|██████▎   | 63/100 [00:00<00:20,  1.84it/s, loss=13.6711]

SVI:  64%|██████▍   | 64/100 [00:00<00:19,  1.84it/s, loss=13.3156]

SVI:  65%|██████▌   | 65/100 [00:00<00:19,  1.84it/s, loss=14.1254]

SVI:  66%|██████▌   | 66/100 [00:00<00:18,  1.84it/s, loss=13.5864]

SVI:  67%|██████▋   | 67/100 [00:00<00:17,  1.84it/s, loss=13.6494]

SVI:  68%|██████▊   | 68/100 [00:00<00:17,  1.84it/s, loss=13.2494]

SVI:  69%|██████▉   | 69/100 [00:00<00:16,  1.84it/s, loss=13.3531]

SVI:  70%|███████   | 70/100 [00:00<00:16,  1.84it/s, loss=13.6790]

SVI:  71%|███████   | 71/100 [00:00<00:15,  1.84it/s, loss=12.6437]

SVI:  72%|███████▏  | 72/100 [00:00<00:15,  1.84it/s, loss=14.2295]

SVI:  73%|███████▎  | 73/100 [00:00<00:14,  1.84it/s, loss=13.1938]

SVI:  74%|███████▍  | 74/100 [00:00<00:14,  1.84it/s, loss=12.2355]

SVI:  75%|███████▌  | 75/100 [00:00<00:13,  1.84it/s, loss=13.3509]

SVI:  76%|███████▌  | 76/100 [00:00<00:13,  1.84it/s, loss=12.1943]

SVI:  77%|███████▋  | 77/100 [00:00<00:12,  1.84it/s, loss=13.3797]

SVI:  78%|███████▊  | 78/100 [00:00<00:11,  1.84it/s, loss=13.0514]

SVI:  79%|███████▉  | 79/100 [00:00<00:11,  1.84it/s, loss=13.1446]

SVI:  80%|████████  | 80/100 [00:00<00:10,  1.84it/s, loss=13.4347]

SVI:  81%|████████  | 81/100 [00:00<00:10,  1.84it/s, loss=11.9700]

SVI:  82%|████████▏ | 82/100 [00:00<00:09,  1.84it/s, loss=13.4504]

SVI:  83%|████████▎ | 83/100 [00:00<00:09,  1.84it/s, loss=13.5111]

SVI:  84%|████████▍ | 84/100 [00:00<00:08,  1.84it/s, loss=12.4415]

SVI:  85%|████████▌ | 85/100 [00:00<00:08,  1.84it/s, loss=14.7867]

SVI:  86%|████████▌ | 86/100 [00:00<00:07,  1.84it/s, loss=12.6455]

SVI:  87%|████████▋ | 87/100 [00:00<00:07,  1.84it/s, loss=13.1370]

SVI:  88%|████████▊ | 88/100 [00:00<00:06,  1.84it/s, loss=13.3685]

SVI:  89%|████████▉ | 89/100 [00:00<00:05,  1.84it/s, loss=12.1700]

SVI:  90%|█████████ | 90/100 [00:00<00:05,  1.84it/s, loss=14.3885]

SVI:  91%|█████████ | 91/100 [00:00<00:04,  1.84it/s, loss=13.6082]

SVI:  92%|█████████▏| 92/100 [00:00<00:04,  1.84it/s, loss=13.1356]

SVI:  93%|█████████▎| 93/100 [00:00<00:03,  1.84it/s, loss=12.6892]

SVI:  94%|█████████▍| 94/100 [00:00<00:03,  1.84it/s, loss=13.0338]

SVI:  95%|█████████▌| 95/100 [00:00<00:02,  1.84it/s, loss=13.2415]

SVI:  96%|█████████▌| 96/100 [00:00<00:02,  1.84it/s, loss=12.6392]

SVI:  97%|█████████▋| 97/100 [00:00<00:01,  1.84it/s, loss=13.1338]

SVI:  98%|█████████▊| 98/100 [00:00<00:01,  1.84it/s, loss=13.0200]

SVI:  99%|█████████▉| 99/100 [00:00<00:00,  1.84it/s, loss=12.1841]

SVI: 100%|██████████| 100/100 [00:00<00:00,  1.84it/s, loss=12.2981]

2026-03-29 18:47:05.932 | INFO     | pybandits.simulator:_print_results:541 - Simulation results (first 10 observations):

2026-03-29 18:47:05.953 | INFO     | pybandits.simulator:_print_results:542 - Count of actions selected by the bandit:

2026-03-29 18:47:05.955 | INFO     | pybandits.simulator:_print_results:543 - Observed proportion of positive rewards for each action:

Furthermore, we can examine the number of times each action was selected and the proportion of positive rewards for each action.

In [9]:
cmab_simulator.selected_actions_count

action        a1   a2   a3 cum_a1 cum_a2 cum_a3
group batch
0     0.0     11   10    4     11     10      4
1     0.0      7   14   11      7     14     11
2     0.0     12   12   19     12     12     19
0     1.0      8   20    3     19     30      7
1     1.0      9    5   13     16     19     24
2     1.0      2   24   16     14     36     35
0     2.0      8   22    2     27     52      9
1     2.0     20    7   13     36     26     37
2     2.0      9    7   12     23     43     47
0     3.0     10   15    7     37     67     16
1     3.0     18    6   14     54     32     51
2     3.0      3   17   10     26     60     57
0     4.0     16   17    4     53     84     20
1     4.0     18    2    9     72     34     60
2     4.0      6   20    8     32     80     65
0     5.0     11   15   11     64     99     31
1     5.0     11    5   12     83     39     72
2     5.0      9   16   10     41     96     75
0     6.0     15   15    9     79    114     40
1     6.0     17    8    6    100     47     78
2     6.0      6   15    9     47    111     84
0     7.0     13    5   11     92    119     51
1     7.0     16   11   12    116     58     90
2     7.0      7   16    9     54    127     93
0     8.0     24    6   11    116    125     62
1     8.0     21    4    5    137     62     95
2     8.0     13    7    9     67    134    102
0     9.0     19    3   10    135    128     72
1     9.0     23    8    9    160     70    104
2     9.0      5   19    4     72    153    106
0     total  135  128   72    135    128     72
1     total  160   70  104    160     70    104
2     total   72  153  106     72    153    106
total total  367  351  282    367    351    282

In [10]:
cmab_simulator.positive_reward_proportion

             proportion
action group
a1     0       0.874074
       1        0.43125
       2       0.555556
a2     0        0.59375
       1       0.414286
       2       0.836601
a3     0       0.680556
       1       0.144231
       2       0.226415