# cMAB Simulation

This notebook shows a simulation framework for the contextual multi-armed bandit (cMAB). It allows to study the behaviour of the bandit algoritm, to evaluate results and to run experiments on simulated data under different context, reward and action settings.

In [1]:
from sklearn.datasets import make_classification

from pybandits.cmab import CmabBernoulli
from pybandits.cmab_simulator import CmabSimulator
from pybandits.model import BayesianLogisticRegression, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

First we need to define the simulation parameters. The parameters are split into two parts. The general parameters contain:
- Number of update rounds
- Number of samples per batch of update round
- Seed for reproducibility
- Verbosity enabler
- Visualization enabler

The problem definition parameters contain:
- Number of groups
- Number of features

Data are processed in batches of size n>=1. Per each batch of simulated samples, the cMAB selects one action and collects the corresponding simulated reward for each sample. Then, prior parameters are updated based on returned rewards from recommended actions.

In [2]:
# general simulator parameters
n_updates = 5
batch_size = 100
random_seed = None
verbose = True
visualize = True

In [3]:
# problem definition simulation parameters
n_groups = 3
n_features = 5

Next, we initialize the context matrix $X$ and the groups of samples. Samples that belong to the same group have features that come from the same distribution.
Then, the action model and the cMAB are defined. We define three actions, each with a Bayesian Logistic Regression model. The model is defined by a Student-T prior for the intercept and a Student-T prior for each feature coefficient.

In [4]:
# init context matrix and groups

context, group = make_classification(
    n_samples=batch_size * n_updates, n_features=n_features, n_informative=n_features, n_redundant=0, n_classes=n_groups
)
group = [str(g) for g in group]

In [5]:
# define action model


def create_blr(n_features, bias_mu, bias_sigma, update_method, update_kwargs):
    """Create a BayesianLogisticRegression with given parameters."""
    bias = StudentTArray.cold_start(mu=bias_mu, sigma=bias_sigma, shape=1)
    weight = StudentTArray.cold_start(shape=(n_features, 1))
    layer_params = BnnLayerParams(weight=weight, bias=bias)
    model_params = BnnParams(bnn_layer_params=[layer_params])
    feature_config = FeaturesConfig(n_features=n_features)
    return BayesianLogisticRegression(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    )


update_method = "VI"
update_kwargs = {"num_steps": 10, "batch_size": 32, "optimizer_type": "adam"}
blr_kwargs = dict(
    n_features=n_features, bias_mu=1, bias_sigma=2, update_method=update_method, update_kwargs=update_kwargs
)
actions = {
    "a1": create_blr(**blr_kwargs),
    "a2": create_blr(**blr_kwargs),
    "a3": create_blr(**blr_kwargs),
}
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

Finally, we need to define the probabilities of positive rewards per each action/group, i.e. the ground truth ('Action A': 0.8 for group '0' means that if the bandits selects 'Action A' for samples that belong to group '0', then the environment will return a positive reward with 80% probability).

In [6]:
# init probability of rewards randomly using splines
probs_reward = None

Now, we initialize the cMAB as shown in the previous notebook and the CmabSimulator with the parameters set above.

In [7]:
# init simulation
cmab_simulator = CmabSimulator(
    mab=cmab,
    group=group,
    batch_size=batch_size,
    n_updates=n_updates,
    probs_reward=probs_reward,
    context=context,
    verbose=verbose,
)

Now, we can start simulation process by executing run() which performs the following steps:
```
For i=0 to n_updates:
    Extract batch[i] of samples from X
    Model recommends the best actions as the action with the highest reward probability to each simulated sample in batch[i] and collect corresponding simulated rewards
    Model priors are updated using information from recommended actions and returned rewards
```
Finally, we can visualize the results of the simulation. As defined in the ground truth: 'a2' was the action recommended the most for samples that belong to group '0', 'a1' to group '1' and both 'a1' and 'a3' to group '2'.

In [8]:
cmab_simulator.run()

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self._results = pd.concat((self._results, batch_results), ignore_index=True)

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:07,  1.28it/s]

SVI:  10%|█         | 1/10 [00:00<00:07,  1.28it/s, loss=102.2294]

SVI:  20%|██        | 2/10 [00:00<00:06,  1.28it/s, loss=97.8224]

SVI:  30%|███       | 3/10 [00:00<00:05,  1.28it/s, loss=90.2670]

SVI:  40%|████      | 4/10 [00:00<00:04,  1.28it/s, loss=103.6697]

SVI:  50%|█████     | 5/10 [00:00<00:03,  1.28it/s, loss=92.1459]

SVI:  60%|██████    | 6/10 [00:00<00:03,  1.28it/s, loss=102.3706]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.28it/s, loss=102.3315]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.28it/s, loss=100.0701]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.28it/s, loss=98.1306]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.28it/s, loss=101.1917]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 32 vs 30. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.98it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.98it/s, loss=125.4579]

SVI:  20%|██        | 2/10 [00:00<00:04,  1.98it/s, loss=124.9738]

SVI:  30%|███       | 3/10 [00:00<00:03,  1.98it/s, loss=122.2582]

SVI:  40%|████      | 4/10 [00:00<00:03,  1.98it/s, loss=120.2474]

SVI:  50%|█████     | 5/10 [00:00<00:02,  1.98it/s, loss=123.4749]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.98it/s, loss=124.0008]

SVI:  70%|███████   | 7/10 [00:00<00:01,  1.98it/s, loss=125.6780]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.98it/s, loss=124.6935]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.98it/s, loss=121.2811]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.98it/s, loss=122.4009]

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.41it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.41it/s, loss=225.3647]

SVI:  20%|██        | 2/10 [00:00<00:05,  1.41it/s, loss=236.7323]

SVI:  30%|███       | 3/10 [00:00<00:04,  1.41it/s, loss=242.3595]

SVI:  40%|████      | 4/10 [00:00<00:04,  1.41it/s, loss=235.5576]

SVI:  50%|█████     | 5/10 [00:00<00:03,  1.41it/s, loss=246.4469]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.41it/s, loss=221.1378]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.41it/s, loss=235.3422]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.41it/s, loss=258.7544]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.41it/s, loss=236.6042]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.41it/s, loss=250.8087]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 32 vs 20. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.88it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.88it/s, loss=38.4454]

SVI:  20%|██        | 2/10 [00:00<00:04,  1.88it/s, loss=38.3694]

SVI:  30%|███       | 3/10 [00:00<00:03,  1.88it/s, loss=38.1601]

SVI:  40%|████      | 4/10 [00:00<00:03,  1.88it/s, loss=38.4208]

SVI:  50%|█████     | 5/10 [00:00<00:02,  1.88it/s, loss=37.8435]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.88it/s, loss=38.1061]

SVI:  70%|███████   | 7/10 [00:00<00:01,  1.88it/s, loss=37.7554]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.88it/s, loss=37.7725]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.88it/s, loss=38.2925]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.88it/s, loss=38.4494]

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.38it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.38it/s, loss=279.9506]

SVI:  20%|██        | 2/10 [00:00<00:05,  1.38it/s, loss=333.0772]

SVI:  30%|███       | 3/10 [00:00<00:05,  1.38it/s, loss=371.1365]

SVI:  40%|████      | 4/10 [00:00<00:04,  1.38it/s, loss=326.4057]

SVI:  50%|█████     | 5/10 [00:00<00:03,  1.38it/s, loss=308.6768]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.38it/s, loss=396.1806]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.38it/s, loss=294.3600]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.38it/s, loss=311.2666]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.38it/s, loss=375.0743]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.38it/s, loss=372.9608]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 32 vs 28. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.95it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.95it/s, loss=170.1084]

SVI:  20%|██        | 2/10 [00:00<00:04,  1.95it/s, loss=171.4173]

SVI:  30%|███       | 3/10 [00:00<00:03,  1.95it/s, loss=170.7034]

SVI:  40%|████      | 4/10 [00:00<00:03,  1.95it/s, loss=164.6653]

SVI:  50%|█████     | 5/10 [00:00<00:02,  1.95it/s, loss=162.1709]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.95it/s, loss=166.6869]

SVI:  70%|███████   | 7/10 [00:00<00:01,  1.95it/s, loss=168.6992]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.95it/s, loss=164.9499]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.95it/s, loss=165.1845]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.95it/s, loss=165.6197]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 32 vs 20. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.89it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.89it/s, loss=16.9603]

SVI:  20%|██        | 2/10 [00:00<00:04,  1.89it/s, loss=14.9384]

SVI:  30%|███       | 3/10 [00:00<00:03,  1.89it/s, loss=17.8721]

SVI:  40%|████      | 4/10 [00:00<00:03,  1.89it/s, loss=16.8951]

SVI:  50%|█████     | 5/10 [00:00<00:02,  1.89it/s, loss=15.1302]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.89it/s, loss=17.0752]

SVI:  70%|███████   | 7/10 [00:00<00:01,  1.89it/s, loss=17.5195]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.89it/s, loss=15.7500]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.89it/s, loss=15.5991]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.89it/s, loss=15.8723]

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.41it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.41it/s, loss=400.7947]

SVI:  20%|██        | 2/10 [00:00<00:05,  1.41it/s, loss=332.2202]

SVI:  30%|███       | 3/10 [00:00<00:04,  1.41it/s, loss=344.5946]

SVI:  40%|████      | 4/10 [00:00<00:04,  1.41it/s, loss=357.7023]

SVI:  50%|█████     | 5/10 [00:00<00:03,  1.41it/s, loss=404.5207]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.41it/s, loss=402.5699]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.41it/s, loss=339.5095]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.41it/s, loss=373.5243]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.41it/s, loss=340.5722]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.41it/s, loss=375.6994]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 32 vs 24. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.95it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.95it/s, loss=151.7386]

SVI:  20%|██        | 2/10 [00:00<00:04,  1.95it/s, loss=148.0404]

SVI:  30%|███       | 3/10 [00:00<00:03,  1.95it/s, loss=155.5487]

SVI:  40%|████      | 4/10 [00:00<00:03,  1.95it/s, loss=145.8531]

SVI:  50%|█████     | 5/10 [00:00<00:02,  1.95it/s, loss=150.9455]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.95it/s, loss=152.4686]

SVI:  70%|███████   | 7/10 [00:00<00:01,  1.95it/s, loss=149.7406]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.95it/s, loss=149.2817]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.95it/s, loss=147.3692]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.95it/s, loss=151.3107]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.40it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.40it/s, loss=275.3340]

SVI:  20%|██        | 2/10 [00:00<00:05,  1.40it/s, loss=292.0961]

SVI:  30%|███       | 3/10 [00:00<00:05,  1.40it/s, loss=273.4753]

SVI:  40%|████      | 4/10 [00:00<00:04,  1.40it/s, loss=305.0940]

SVI:  50%|█████     | 5/10 [00:00<00:03,  1.40it/s, loss=275.6683]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.40it/s, loss=283.7588]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.40it/s, loss=305.7147]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.40it/s, loss=284.5583]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.40it/s, loss=291.4281]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.40it/s, loss=292.3857]

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 32 vs 15. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.96it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  1.96it/s, loss=35.1266]

SVI:  20%|██        | 2/10 [00:00<00:04,  1.96it/s, loss=35.1180]

SVI:  30%|███       | 3/10 [00:00<00:03,  1.96it/s, loss=35.0775]

SVI:  40%|████      | 4/10 [00:00<00:03,  1.96it/s, loss=35.0232]

SVI:  50%|█████     | 5/10 [00:00<00:02,  1.96it/s, loss=35.8938]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.96it/s, loss=34.3948]

SVI:  70%|███████   | 7/10 [00:00<00:01,  1.96it/s, loss=34.5166]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.96it/s, loss=35.0809]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.96it/s, loss=35.0234]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.96it/s, loss=33.9331]

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:07,  1.13it/s]

SVI:  10%|█         | 1/10 [00:00<00:07,  1.13it/s, loss=314.0696]

SVI:  20%|██        | 2/10 [00:00<00:07,  1.13it/s, loss=326.2058]

SVI:  30%|███       | 3/10 [00:00<00:06,  1.13it/s, loss=388.5471]

SVI:  40%|████      | 4/10 [00:00<00:05,  1.13it/s, loss=387.3197]

SVI:  50%|█████     | 5/10 [00:00<00:04,  1.13it/s, loss=308.9294]

SVI:  60%|██████    | 6/10 [00:00<00:03,  1.13it/s, loss=319.3260]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.13it/s, loss=359.3641]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.13it/s, loss=363.8247]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.13it/s, loss=330.4473]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.13it/s, loss=338.7049]

/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: overflow encountered in exp
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()
/home/runner/work/pybandits/pybandits/pybandits/simulator.py:229: RuntimeWarning: invalid value encountered in scalar divide
  return np.where(s >= 0, 1 / (1 + np.exp(-s)), np.exp(s) / (1 + np.exp(s))).item()

/home/runner/work/pybandits/pybandits/pybandits/model.py:1513: UserWarning: subsample_size does not match len(subsample), 32 vs 10. Did you accidentally use different subsample_size in the model and guide?
  with numpyro.plate("data", N, subsample_size=batch_size) as idx:

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  2.00it/s]

SVI:  10%|█         | 1/10 [00:00<00:04,  2.00it/s, loss=6.3788]

SVI:  20%|██        | 2/10 [00:00<00:04,  2.00it/s, loss=7.3054]

SVI:  30%|███       | 3/10 [00:00<00:03,  2.00it/s, loss=6.4920]

SVI:  40%|████      | 4/10 [00:00<00:03,  2.00it/s, loss=6.8864]

SVI:  50%|█████     | 5/10 [00:00<00:02,  2.00it/s, loss=7.4693]

SVI:  60%|██████    | 6/10 [00:00<00:02,  2.00it/s, loss=6.0819]

SVI:  70%|███████   | 7/10 [00:00<00:01,  2.00it/s, loss=6.7357]

SVI:  80%|████████  | 8/10 [00:00<00:01,  2.00it/s, loss=5.3515]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  2.00it/s, loss=6.3252]

SVI: 100%|██████████| 10/10 [00:00<00:00,  2.00it/s, loss=7.3869]

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.39it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.39it/s, loss=259.3723]

SVI:  20%|██        | 2/10 [00:00<00:05,  1.39it/s, loss=218.3436]

SVI:  30%|███       | 3/10 [00:00<00:05,  1.39it/s, loss=230.1103]

SVI:  40%|████      | 4/10 [00:00<00:04,  1.39it/s, loss=253.4959]

SVI:  50%|█████     | 5/10 [00:00<00:03,  1.39it/s, loss=266.8440]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.39it/s, loss=210.4041]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.39it/s, loss=226.7533]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.39it/s, loss=227.9504]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.39it/s, loss=222.4355]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.39it/s, loss=250.5795]

SVI:   0%|          | 0/10 [00:00<?, ?it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.42it/s]

SVI:  10%|█         | 1/10 [00:00<00:06,  1.42it/s, loss=391.7932]

SVI:  20%|██        | 2/10 [00:00<00:05,  1.42it/s, loss=397.2762]

SVI:  30%|███       | 3/10 [00:00<00:04,  1.42it/s, loss=367.3847]

SVI:  40%|████      | 4/10 [00:00<00:04,  1.42it/s, loss=282.0855]

SVI:  50%|█████     | 5/10 [00:00<00:03,  1.42it/s, loss=396.7608]

SVI:  60%|██████    | 6/10 [00:00<00:02,  1.42it/s, loss=310.9368]

SVI:  70%|███████   | 7/10 [00:00<00:02,  1.42it/s, loss=326.6007]

SVI:  80%|████████  | 8/10 [00:00<00:01,  1.42it/s, loss=382.1902]

SVI:  90%|█████████ | 9/10 [00:00<00:00,  1.42it/s, loss=361.0564]

SVI: 100%|██████████| 10/10 [00:00<00:00,  1.42it/s, loss=385.1503]

2026-04-09 18:38:57.927 | INFO     | pybandits.simulator:_print_results:541 - Simulation results (first 10 observations):

2026-04-09 18:38:57.948 | INFO     | pybandits.simulator:_print_results:542 - Count of actions selected by the bandit:

2026-04-09 18:38:57.951 | INFO     | pybandits.simulator:_print_results:543 - Observed proportion of positive rewards for each action:

Furthermore, we can examine the number of times each action was selected and the proportion of positive rewards for each action.

In [9]:
cmab_simulator.selected_actions_count

action        a1   a2   a3 cum_a1 cum_a2 cum_a3
group batch
0     0.0     11   16   12     11     16     12
1     0.0     13    9    7     13      9      7
2     0.0     11   10   11     11     10     11
0     1.0      9    2   17     20     18     29
1     1.0     22   11    8     35     20     15
2     1.0     21    7    3     32     17     14
0     2.0      9    4   15     29     22     44
1     2.0     20   13    5     55     33     20
2     2.0     27    3    4     59     20     18
0     3.0     10    2   23     39     24     67
1     3.0     15    5    7     70     38     27
2     3.0     26    8    4     85     28     22
0     4.0     11    3   22     50     27     89
1     4.0     19    2   11     89     40     38
2     4.0     22    5    5    107     33     27
0     total   50   27   89     50     27     89
1     total   89   40   38     89     40     38
2     total  107   33   27    107     33     27
total total  246  100  154    246    100    154

In [10]:
cmab_simulator.positive_reward_proportion

             proportion
action group
a1     0           0.18
       1       0.337079
       2       0.383178
a2     0       0.481481
       1           0.85
       2        0.69697
a3     0       0.280899
       1       0.026316
       2       0.148148