# Composing an Offer with a Contextual Bandit: Item Portions (that must sum to 1) + Price

We run a store that sells a **bundled offer** made of three items. For every customer we must decide two things at once:

1. **The mix** — what portion of the bundle each of the three items takes. The three portions must add up to **1** (it is a single bundle).
2. **The price** — a normalized price in `[0, 1]` for the whole offer.

Both decisions are *continuous* and both depend on **context** (who the customer is). This is a job for a **contextual multi-armed bandit with a BNN-based quantitative model**: a Bayesian Neural Network maps `(context, offer parameters) -> P(purchase)`, and Thompson sampling explores the continuous offer space while exploiting what it has learned.

## The catch: a structural equality constraint

`portion_1 + portion_2 + portion_3 = 1` is an **equality** constraint. The quantitative optimizer in `pybandits` searches the hyper-cube `[0, 1]^d` and treats a constraint callable `g(x)` as feasible where `g(x) >= 0` — i.e. it supports **inequalities**, not exact equalities. An exact equality carves out a measure-zero surface that a differential-evolution optimizer has nothing to descend on.

So we turn the equality into geometry the model and optimizer both like. The quantity vector is `[p_1, p_2, price]`: the first `N_ITEMS - 1 = 2` coordinates **are the item portions directly** (so the BNN reasons in real portion space), and the last portion is the leftover `p_3 = 1 - p_1 - p_2`. Keeping every portion non-negative reduces to a single **inequality**, `p_1 + p_2 <= 1`, which we hand to the optimizer as a *forbidden region*. The feasible set is a triangle (half the cube) — a full-measure region, far friendlier than the measure-zero equality.

This deliberately avoids two worse options: an exact equality on `[p_1, p_2, p_3]` (measure-zero for the optimizer, and a redundant third input the BNN cannot use), and a stick-breaking re-parameterization (valid by construction, but it warps the space and privileges one item, making the reward surface harder to learn).

In [1]:
import numpy as np
import pandas as pd

from pybandits.cmab import CmabBernoulli
from pybandits.quantitative_model import QuantitativeBayesianNeuralNetwork

rng = np.random.default_rng(seed=42)

%load_ext autoreload
%autoreload 2

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## The offer parameterization and its constraint

The quantity vector the bandit optimizes is `[p_1, p_2, price]`. `split` reads it back into the three portions (last = leftover) and the price. `portions_sum_over_one` is the forbidden-region margin: pybandits treats a region as forbidden where `region(x) > 0`, so returning `p_1 + p_2 - 1` forbids exactly the corner of the cube where the portions would exceed 1 (i.e. where `p_3` would go negative).

In [2]:
N_ITEMS = 3  # items in the bundle; their portions must sum to 1


def split(quantity):
    """Read a quantity vector [p_1, ..., p_{N-1}, price] into (portions, price).

    The first N_ITEMS - 1 coordinates are the item portions; the final
    portion is the leftover so the portions sum to 1. The BNN sees these
    coordinates directly, so it learns the reward in real portion space.
    """
    free = np.asarray(quantity[: N_ITEMS - 1], dtype=float)
    portions = np.append(free, 1.0 - free.sum())
    price = float(quantity[N_ITEMS - 1])
    return portions, price


def portions_sum_over_one(quantity):
    """Forbidden-region margin: > 0 where the free portions exceed 1 (invalid)."""
    return float(np.sum(quantity[: N_ITEMS - 1]) - 1.0)


# Passed to predict(): forbids the p_1 + p_2 > 1 corner for the 'offer' arm, in
# both the optimized (exploit) and Thompson-sampled (explore) branches.
forbidden_actions = {"offer": portions_sum_over_one}

A quick check of the feasible region: about half the cube is feasible, and every feasible point yields non-negative portions that sum to 1.

In [3]:
samples = rng.random((10000, N_ITEMS))
feasible = np.array([portions_sum_over_one(q) <= 0 for q in samples])
portions = np.array([split(q)[0] for q in samples[feasible]])

assert np.allclose(portions.sum(axis=1), 1.0), "portions must sum to 1"
assert (portions >= 0).all(), "feasible portions must be non-negative"
print(f"{feasible.mean():.0%} of the cube is feasible; all feasible offers have portions >= 0 summing to 1")

50% of the cube is feasible; all feasible offers have portions >= 0 summing to 1

## Simulated environment: what makes a customer buy

Context is three features in `[0, 1]`: `[affluence, preference_item_1, preference_item_2]`.

Each customer has a hidden **ideal offer**:
- an ideal portion mix that reflects their item preferences (item 3's preference is the leftover), and
- an ideal price that rises with affluence.

The purchase probability is high when the offer's mix and price are both close to the customer's ideal, and decays with distance (a bell curve on each). The bandit has to discover this per-context sweet spot from binary purchase feedback alone.

In [4]:
def make_ideal(context):
    """The customer's hidden sweet-spot offer, given their context."""
    affluence, pref1, pref2 = context
    raw = np.array([pref1, pref2, 1.0 - 0.5 * (pref1 + pref2)]) + 0.1  # keep every share positive
    ideal_portions = raw / raw.sum()
    ideal_price = 0.2 + 0.6 * affluence
    return ideal_portions, ideal_price


def reward_function(quantity, context):
    portions, price = split(quantity)
    ideal_portions, ideal_price = make_ideal(context)
    mix_fit = np.exp(-np.sum((portions - ideal_portions) ** 2) / 0.05)
    price_fit = np.exp(-((price - ideal_price) ** 2) / 0.03)
    prob = float(np.clip(mix_fit * price_fit, 0.0, 1.0))
    return rng.binomial(1, prob), prob


def get_optimal_reward(context):
    # The ideal offer hits mix_fit = price_fit = 1, so the best achievable prob is 1.
    return 1.0

## Build the bandit

A single quantitative action, `"offer"`, of dimension `N_ITEMS` (two free portion coordinates + price). The BNN receives `[quantity, context]` and outputs `P(purchase)`.

> With one action the arm choice is trivial (you'll see a "MAB will be deterministic" warning) — the real decision here is the *continuous* offer composition, which the quantity optimizer still explores. Add more actions (e.g. distinct bundle templates) if you also want the bandit to choose *between* offers.

In [5]:
n_features = 3  # [affluence, preference_item_1, preference_item_2]
dimension = N_ITEMS  # 2 free portion coordinates + 1 price

update_kwargs = {"epochs": 100, "optimizer_type": "adam", "batch_size": 64, "optimizer_kwargs": {"step_size": 0.001}}
dist_params_init = {"mu": 0, "sigma": 2}

actions = {
    "offer": QuantitativeBayesianNeuralNetwork.cold_start(
        dimension=dimension,
        n_features=n_features,
        base_model_cold_start_kwargs=dict(
            hidden_dim_list=[32],
            update_method="VI",
            update_kwargs=update_kwargs,
            dist_params_init=dist_params_init,
            activation="gelu",
            bias_std=0.1,
        ),
    ),
}

cmab = CmabBernoulli(actions=actions, epsilon=1)  # full exploration for the training batch

/home/runner/work/pybandits/pybandits/pybandits/meta_model.py:357: UserWarning: Only a single action was supplied. This MAB will be deterministic.
  warnings.warn("Only a single action was supplied. This MAB will be deterministic.")

## Train the bandit

We collect a **single exploration batch** of 4096 offers with `epsilon=1` (random, constraint-respecting offers — no optimizer on the cold model), then update the BNN once. `predict` is called on the whole batch at once — no loop. We pass `forbidden_actions` so every sampled offer respects `p_1 + p_2 <= 1`.

In [6]:
current_context = rng.uniform(0, 1, (4096, n_features))

# Single exploration batch: one batched predict, one update.
pred_actions, _, _ = cmab.predict(context=current_context, forbidden_actions=forbidden_actions)
chosen_actions = [a[0] for a in pred_actions]
chosen_quantities = [list(a[1]) for a in pred_actions]

rewards_and_probs = [reward_function(q, ctx) for q, ctx in zip(chosen_quantities, current_context)]
rewards = [r for r, _ in rewards_and_probs]
probs = [p for _, p in rewards_and_probs]

regret = float(np.mean([get_optimal_reward(ctx) for ctx in current_context]) - np.mean(probs))
cmab.update(actions=chosen_actions, rewards=rewards, context=current_context, quantities=chosen_quantities)

print(f"Explored and updated on {len(current_context)} offers. Avg exploration regret: {regret:.4f}")

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:01<02:42,  1.64s/it]

SVI:   1%|          | 1/100 [00:01<02:42,  1.64s/it, loss=19848.2422]

SVI:   2%|▏         | 2/100 [00:01<02:40,  1.64s/it, loss=21971.7090]

SVI:   3%|▎         | 3/100 [00:01<02:39,  1.64s/it, loss=11258.9395]

SVI:   4%|▍         | 4/100 [00:01<02:37,  1.64s/it, loss=24283.7441]

SVI:   5%|▌         | 5/100 [00:01<02:35,  1.64s/it, loss=20684.5742]

SVI:   6%|▌         | 6/100 [00:01<02:34,  1.64s/it, loss=14480.1299]

SVI:   7%|▋         | 7/100 [00:01<02:32,  1.64s/it, loss=20551.4492]

SVI:   8%|▊         | 8/100 [00:01<00:14,  6.14it/s, loss=20551.4492]

SVI:   8%|▊         | 8/100 [00:01<00:14,  6.14it/s, loss=16555.2930]

SVI:   9%|▉         | 9/100 [00:01<00:14,  6.14it/s, loss=16154.7588]

SVI:  10%|█         | 10/100 [00:01<00:14,  6.14it/s, loss=14229.0771]

SVI:  11%|█         | 11/100 [00:01<00:14,  6.14it/s, loss=10630.1250]

SVI:  12%|█▏        | 12/100 [00:01<00:14,  6.14it/s, loss=17023.1680]

SVI:  13%|█▎        | 13/100 [00:01<00:14,  6.14it/s, loss=11590.0117]

SVI:  14%|█▍        | 14/100 [00:01<00:14,  6.14it/s, loss=8699.4961]

SVI:  15%|█▌        | 15/100 [00:01<00:13,  6.14it/s, loss=11250.3096]

SVI:  16%|█▌        | 16/100 [00:01<00:06, 13.51it/s, loss=11250.3096]

SVI:  16%|█▌        | 16/100 [00:01<00:06, 13.51it/s, loss=10943.7148]

SVI:  17%|█▋        | 17/100 [00:01<00:06, 13.51it/s, loss=12616.7207]

SVI:  18%|█▊        | 18/100 [00:01<00:06, 13.51it/s, loss=9475.7988]

SVI:  19%|█▉        | 19/100 [00:01<00:05, 13.51it/s, loss=11775.6992]

SVI:  20%|██        | 20/100 [00:01<00:05, 13.51it/s, loss=11728.0039]

SVI:  21%|██        | 21/100 [00:01<00:05, 13.51it/s, loss=10788.2012]

SVI:  22%|██▏       | 22/100 [00:01<00:05, 13.51it/s, loss=9928.1309]

SVI:  23%|██▎       | 23/100 [00:01<00:03, 20.54it/s, loss=9928.1309]

SVI:  23%|██▎       | 23/100 [00:01<00:03, 20.54it/s, loss=8204.0928]

SVI:  24%|██▍       | 24/100 [00:01<00:03, 20.54it/s, loss=8269.3545]

SVI:  25%|██▌       | 25/100 [00:01<00:03, 20.54it/s, loss=8276.0371]

SVI:  26%|██▌       | 26/100 [00:02<00:03, 20.54it/s, loss=9992.6475]

SVI:  27%|██▋       | 27/100 [00:02<00:03, 20.54it/s, loss=7245.0337]

SVI:  28%|██▊       | 28/100 [00:02<00:03, 20.54it/s, loss=7958.1187]

SVI:  29%|██▉       | 29/100 [00:02<00:03, 20.54it/s, loss=5989.8486]

SVI:  30%|███       | 30/100 [00:02<00:02, 27.79it/s, loss=5989.8486]

SVI:  30%|███       | 30/100 [00:02<00:02, 27.79it/s, loss=9276.4971]

SVI:  31%|███       | 31/100 [00:02<00:02, 27.79it/s, loss=7934.5811]

SVI:  32%|███▏      | 32/100 [00:02<00:02, 27.79it/s, loss=9210.6807]

SVI:  33%|███▎      | 33/100 [00:02<00:02, 27.79it/s, loss=7930.6978]

SVI:  34%|███▍      | 34/100 [00:02<00:02, 27.79it/s, loss=6412.8672]

SVI:  35%|███▌      | 35/100 [00:02<00:02, 27.79it/s, loss=8608.4746]

SVI:  36%|███▌      | 36/100 [00:02<00:02, 27.79it/s, loss=6087.1963]

SVI:  37%|███▋      | 37/100 [00:02<00:01, 35.06it/s, loss=6087.1963]

SVI:  37%|███▋      | 37/100 [00:02<00:01, 35.06it/s, loss=8346.8877]

SVI:  38%|███▊      | 38/100 [00:02<00:01, 35.06it/s, loss=5872.0566]

SVI:  39%|███▉      | 39/100 [00:02<00:01, 35.06it/s, loss=7114.9121]

SVI:  40%|████      | 40/100 [00:02<00:01, 35.06it/s, loss=7975.0723]

SVI:  41%|████      | 41/100 [00:02<00:01, 35.06it/s, loss=8758.9482]

SVI:  42%|████▏     | 42/100 [00:02<00:01, 35.06it/s, loss=6784.0298]

SVI:  43%|████▎     | 43/100 [00:02<00:01, 35.06it/s, loss=8088.9990]

SVI:  44%|████▍     | 44/100 [00:02<00:01, 42.08it/s, loss=8088.9990]

SVI:  44%|████▍     | 44/100 [00:02<00:01, 42.08it/s, loss=7511.0645]

SVI:  45%|████▌     | 45/100 [00:02<00:01, 42.08it/s, loss=5612.8975]

SVI:  46%|████▌     | 46/100 [00:02<00:01, 42.08it/s, loss=7667.7764]

SVI:  47%|████▋     | 47/100 [00:02<00:01, 42.08it/s, loss=8182.3926]

SVI:  48%|████▊     | 48/100 [00:02<00:01, 42.08it/s, loss=8007.4717]

SVI:  49%|████▉     | 49/100 [00:02<00:01, 42.08it/s, loss=6356.4053]

SVI:  50%|█████     | 50/100 [00:02<00:01, 42.08it/s, loss=6146.5215]

SVI:  51%|█████     | 51/100 [00:02<00:01, 47.79it/s, loss=6146.5215]

SVI:  51%|█████     | 51/100 [00:02<00:01, 47.79it/s, loss=6248.9414]

SVI:  52%|█████▏    | 52/100 [00:02<00:01, 47.79it/s, loss=6363.3145]

SVI:  53%|█████▎    | 53/100 [00:02<00:00, 47.79it/s, loss=6515.7109]

SVI:  54%|█████▍    | 54/100 [00:02<00:00, 47.79it/s, loss=6298.3359]

SVI:  55%|█████▌    | 55/100 [00:02<00:00, 47.79it/s, loss=7287.0420]

SVI:  56%|█████▌    | 56/100 [00:02<00:00, 47.79it/s, loss=7238.4336]

SVI:  57%|█████▋    | 57/100 [00:02<00:00, 47.79it/s, loss=6917.6621]

SVI:  58%|█████▊    | 58/100 [00:02<00:00, 47.79it/s, loss=7692.1953]

SVI:  59%|█████▉    | 59/100 [00:02<00:00, 53.79it/s, loss=7692.1953]

SVI:  59%|█████▉    | 59/100 [00:02<00:00, 53.79it/s, loss=4999.0688]

SVI:  60%|██████    | 60/100 [00:02<00:00, 53.79it/s, loss=5940.0938]

SVI:  61%|██████    | 61/100 [00:02<00:00, 53.79it/s, loss=6247.9590]

SVI:  62%|██████▏   | 62/100 [00:02<00:00, 53.79it/s, loss=6733.9536]

SVI:  63%|██████▎   | 63/100 [00:02<00:00, 53.79it/s, loss=4588.9688]

SVI:  64%|██████▍   | 64/100 [00:02<00:00, 53.79it/s, loss=5687.3281]

SVI:  65%|██████▌   | 65/100 [00:02<00:00, 53.79it/s, loss=7676.9771]

SVI:  66%|██████▌   | 66/100 [00:02<00:00, 57.11it/s, loss=7676.9771]

SVI:  66%|██████▌   | 66/100 [00:02<00:00, 57.11it/s, loss=7246.8560]

SVI:  67%|██████▋   | 67/100 [00:02<00:00, 57.11it/s, loss=6873.5908]

SVI:  68%|██████▊   | 68/100 [00:02<00:00, 57.11it/s, loss=5911.3364]

SVI:  69%|██████▉   | 69/100 [00:02<00:00, 57.11it/s, loss=5353.3955]

SVI:  70%|███████   | 70/100 [00:02<00:00, 57.11it/s, loss=7753.3369]

SVI:  71%|███████   | 71/100 [00:02<00:00, 57.11it/s, loss=6089.2686]

SVI:  72%|███████▏  | 72/100 [00:02<00:00, 57.11it/s, loss=5757.8760]

SVI:  73%|███████▎  | 73/100 [00:02<00:00, 57.11it/s, loss=5265.8945]

SVI:  74%|███████▍  | 74/100 [00:02<00:00, 61.57it/s, loss=5265.8945]

SVI:  74%|███████▍  | 74/100 [00:02<00:00, 61.57it/s, loss=5464.0752]

SVI:  75%|███████▌  | 75/100 [00:02<00:00, 61.57it/s, loss=6300.3428]

SVI:  76%|███████▌  | 76/100 [00:02<00:00, 61.57it/s, loss=4938.5449]

SVI:  77%|███████▋  | 77/100 [00:02<00:00, 61.57it/s, loss=6187.9722]

SVI:  78%|███████▊  | 78/100 [00:02<00:00, 61.57it/s, loss=8072.3662]

SVI:  79%|███████▉  | 79/100 [00:02<00:00, 61.57it/s, loss=4759.0869]

SVI:  80%|████████  | 80/100 [00:02<00:00, 61.57it/s, loss=5493.5752]

SVI:  81%|████████  | 81/100 [00:02<00:00, 63.32it/s, loss=5493.5752]

SVI:  81%|████████  | 81/100 [00:02<00:00, 63.32it/s, loss=4833.7456]

SVI:  82%|████████▏ | 82/100 [00:02<00:00, 63.32it/s, loss=5509.2715]

SVI:  83%|████████▎ | 83/100 [00:02<00:00, 63.32it/s, loss=4975.7822]

SVI:  84%|████████▍ | 84/100 [00:02<00:00, 63.32it/s, loss=4619.1084]

SVI:  85%|████████▌ | 85/100 [00:02<00:00, 63.32it/s, loss=4753.4404]

SVI:  86%|████████▌ | 86/100 [00:02<00:00, 63.32it/s, loss=4108.8423]

SVI:  87%|████████▋ | 87/100 [00:02<00:00, 63.32it/s, loss=4674.5015]

SVI:  88%|████████▊ | 88/100 [00:02<00:00, 64.64it/s, loss=4674.5015]

SVI:  88%|████████▊ | 88/100 [00:02<00:00, 64.64it/s, loss=5573.9824]

SVI:  89%|████████▉ | 89/100 [00:02<00:00, 64.64it/s, loss=4738.0029]

SVI:  90%|█████████ | 90/100 [00:02<00:00, 64.64it/s, loss=4386.2139]

SVI:  91%|█████████ | 91/100 [00:02<00:00, 64.64it/s, loss=4216.7036]

SVI:  92%|█████████▏| 92/100 [00:02<00:00, 64.64it/s, loss=4334.7759]

SVI:  93%|█████████▎| 93/100 [00:02<00:00, 64.64it/s, loss=5959.7690]

SVI:  94%|█████████▍| 94/100 [00:02<00:00, 64.64it/s, loss=4172.3657]

SVI:  95%|█████████▌| 95/100 [00:03<00:00, 64.64it/s, loss=4082.9497]

SVI:  96%|█████████▌| 96/100 [00:03<00:00, 65.76it/s, loss=4082.9497]

SVI:  96%|█████████▌| 96/100 [00:03<00:00, 65.76it/s, loss=5373.7642]

SVI:  97%|█████████▋| 97/100 [00:03<00:00, 65.76it/s, loss=3883.4365]

SVI:  98%|█████████▊| 98/100 [00:03<00:00, 65.76it/s, loss=5289.2822]

SVI:  99%|█████████▉| 99/100 [00:03<00:00, 65.76it/s, loss=4017.0869]

SVI: 100%|██████████| 100/100 [00:03<00:00, 65.76it/s, loss=4396.9351]

Explored and updated on 4096 offers. Avg exploration regret: 0.9513

## Inspect the learned policy

We rebuild the bandit with `epsilon=0` to **exploit** the trained model, then ask it for the chosen offer at a handful of representative customers and compare to the hidden ideal. The `portion_sum` column is `1` and every portion is non-negative — guaranteed by the `p_1 + p_2 <= 1` forbidden region.

In [7]:
cmab = CmabBernoulli(actions=actions, epsilon=0)  # exploit the trained model

test_contexts = np.array(
    [
        [0.9, 0.9, 0.1],  # affluent, loves item 1
        [0.9, 0.1, 0.9],  # affluent, loves item 2
        [0.2, 0.4, 0.4],  # budget, balanced taste
        [0.5, 0.1, 0.1],  # mid, leftover preference -> item 3
    ]
)

pred_actions, _, _ = cmab.predict(context=test_contexts, forbidden_actions=forbidden_actions)

rows = []
for ctx, (_, quantity) in zip(test_contexts, pred_actions):
    portions, price = split(quantity)
    ideal_portions, ideal_price = make_ideal(ctx)
    rows.append(
        {
            "context": np.round(ctx, 2),
            "chosen_portions": np.round(portions, 3),
            "portion_sum": round(float(portions.sum()), 6),
            "chosen_price": round(price, 3),
            "ideal_portions": np.round(ideal_portions, 3),
            "ideal_price": round(float(ideal_price), 3),
        }
    )

pd.DataFrame(rows)

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py:552: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  self.H.update(delta_x, delta_g)

,context,chosen_portions,portion_sum,chosen_price,ideal_portions,ideal_price
0,"[0.9, 0.9, 0.1]","[0.0, 1.0, 0.0]",1.0,0.000,"[0.556, 0.111, 0.333]",0.74
1,"[0.9, 0.1, 0.9]","[0.0, 1.0, 0.0]",1.0,0.000,"[0.111, 0.556, 0.333]",0.74
2,"[0.2, 0.4, 0.4]","[0.0, 0.0, 1.0]",1.0,0.571,"[0.294, 0.294, 0.412]",0.32
3,"[0.5, 0.1, 0.1]","[0.0, 0.193, 0.807]",1.0,0.107,"[0.143, 0.143, 0.714]",0.50

## Continued example: discrete prices as separate arms

Suppose price is not a free continuous knob but a **discrete choice** — say **-10%, 0%, +10%** around a reference price. The natural model is one **quantitative arm per price level**: three arms that each optimize only the *portion mix* (dimension `N_ITEMS - 1 = 2`), while the bandit's **arm choice picks the price**. Now Thompson sampling does real work across arms *and* optimizes the continuous mix within the chosen arm.

Everything else carries over: the `p_1 + p_2 <= 1` forbidden region applies to every arm.

In [8]:
PRICE_LEVELS = {"price_down": 0.45, "price_same": 0.50, "price_up": 0.55}  # -10%, 0%, +10% of a 0.50 base


def portions_from(quantity):
    """Portions from a portions-only quantity (all coords are free portions; last = leftover)."""
    free = np.asarray(quantity, dtype=float)
    return np.append(free, 1.0 - free.sum())


def reward_price_arm(arm, quantity, context):
    portions = portions_from(quantity)
    price = PRICE_LEVELS[arm]
    ideal_portions, ideal_price = make_ideal(context)
    mix_fit = np.exp(-np.sum((portions - ideal_portions) ** 2) / 0.05)
    price_fit = np.exp(-((price - ideal_price) ** 2) / 0.03)
    prob = float(np.clip(mix_fit * price_fit, 0.0, 1.0))
    return rng.binomial(1, prob), prob


def get_optimal_reward_discrete(context):
    # Best achievable: perfect mix (mix_fit = 1) at the closest available price level.
    _, ideal_price = make_ideal(context)
    return max(np.exp(-((p - ideal_price) ** 2) / 0.03) for p in PRICE_LEVELS.values())


# One quantitative arm per price level; each optimizes portions only (dimension
# N_ITEMS - 1), under the same p_1 + p_2 <= 1 forbidden region.
forbidden_actions_multi = {arm: portions_sum_over_one for arm in PRICE_LEVELS}

actions_multi = {
    arm: QuantitativeBayesianNeuralNetwork.cold_start(
        dimension=N_ITEMS - 1,  # portions only; the price is the arm
        n_features=n_features,
        base_model_cold_start_kwargs=dict(
            hidden_dim_list=[32],
            update_method="VI",
            update_kwargs=update_kwargs,
            dist_params_init=dist_params_init,
            activation="gelu",
            bias_std=0.1,
        ),
    )
    for arm in PRICE_LEVELS
}

### Train the multi-arm bandit

Same single-batch recipe, but now `predict` also chooses among the three price arms. We explore one batch of 4096 (`epsilon=1`), update every arm from its share of the data, and measure regret against the best *achievable* reward on the discrete price grid (a perfect mix at the closest price level, generally below 1).

In [9]:
cmab_multi = CmabBernoulli(actions=actions_multi, epsilon=1)

current_context = rng.uniform(0, 1, (4096, n_features))
pred_actions, _, _ = cmab_multi.predict(context=current_context, forbidden_actions=forbidden_actions_multi)
chosen_arms = [a[0] for a in pred_actions]
chosen_quantities = [list(a[1]) for a in pred_actions]

rewards_and_probs = [
    reward_price_arm(arm, q, ctx) for arm, q, ctx in zip(chosen_arms, chosen_quantities, current_context)
]
rewards = [r for r, _ in rewards_and_probs]
probs = [p for _, p in rewards_and_probs]

regret = float(np.mean([get_optimal_reward_discrete(ctx) for ctx in current_context]) - np.mean(probs))
cmab_multi.update(actions=chosen_arms, rewards=rewards, context=current_context, quantities=chosen_quantities)

arm_counts = {arm: chosen_arms.count(arm) for arm in PRICE_LEVELS}
print(f"Explored and updated on {len(current_context)} offers. Avg regret: {regret:.4f}. Arm counts: {arm_counts}")

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:01<02:30,  1.52s/it]

SVI:   1%|          | 1/100 [00:01<02:30,  1.52s/it, loss=11682.3330]

SVI:   2%|▏         | 2/100 [00:01<02:29,  1.52s/it, loss=14418.2920]

SVI:   3%|▎         | 3/100 [00:01<02:27,  1.52s/it, loss=8437.9775]

SVI:   4%|▍         | 4/100 [00:01<02:26,  1.52s/it, loss=10111.3467]

SVI:   5%|▌         | 5/100 [00:01<02:24,  1.52s/it, loss=7599.6069]

SVI:   6%|▌         | 6/100 [00:01<02:23,  1.52s/it, loss=12243.9648]

SVI:   7%|▋         | 7/100 [00:01<02:21,  1.52s/it, loss=9588.4922]

SVI:   8%|▊         | 8/100 [00:01<02:20,  1.52s/it, loss=9895.6768]

SVI:   9%|▉         | 9/100 [00:01<02:18,  1.52s/it, loss=9943.7764]

SVI:  10%|█         | 10/100 [00:01<02:17,  1.52s/it, loss=5916.9150]

SVI:  11%|█         | 11/100 [00:01<02:15,  1.52s/it, loss=9202.2822]

SVI:  12%|█▏        | 12/100 [00:01<02:14,  1.52s/it, loss=10269.8398]

SVI:  13%|█▎        | 13/100 [00:01<02:12,  1.52s/it, loss=11914.5449]

SVI:  14%|█▍        | 14/100 [00:01<02:10,  1.52s/it, loss=6823.1616]

SVI:  15%|█▌        | 15/100 [00:01<02:09,  1.52s/it, loss=8512.1436]

SVI:  16%|█▌        | 16/100 [00:01<02:07,  1.52s/it, loss=8323.3926]

SVI:  17%|█▋        | 17/100 [00:01<02:06,  1.52s/it, loss=7839.6904]

SVI:  18%|█▊        | 18/100 [00:01<02:04,  1.52s/it, loss=8205.6426]

SVI:  19%|█▉        | 19/100 [00:01<00:05, 16.03it/s, loss=8205.6426]

SVI:  19%|█▉        | 19/100 [00:01<00:05, 16.03it/s, loss=9014.8047]

SVI:  20%|██        | 20/100 [00:01<00:04, 16.03it/s, loss=6814.7856]

SVI:  21%|██        | 21/100 [00:01<00:04, 16.03it/s, loss=4039.7122]

SVI:  22%|██▏       | 22/100 [00:01<00:04, 16.03it/s, loss=9900.4199]

SVI:  23%|██▎       | 23/100 [00:01<00:04, 16.03it/s, loss=7012.0869]

SVI:  24%|██▍       | 24/100 [00:01<00:04, 16.03it/s, loss=7531.2256]

SVI:  25%|██▌       | 25/100 [00:01<00:04, 16.03it/s, loss=8106.4463]

SVI:  26%|██▌       | 26/100 [00:01<00:04, 16.03it/s, loss=6304.1709]

SVI:  27%|██▋       | 27/100 [00:01<00:04, 16.03it/s, loss=4573.4351]

SVI:  28%|██▊       | 28/100 [00:01<00:04, 16.03it/s, loss=5673.4614]

SVI:  29%|██▉       | 29/100 [00:01<00:04, 16.03it/s, loss=9421.5000]

SVI:  30%|███       | 30/100 [00:01<00:04, 16.03it/s, loss=6250.2412]

SVI:  31%|███       | 31/100 [00:01<00:04, 16.03it/s, loss=5135.5864]

SVI:  32%|███▏      | 32/100 [00:01<00:04, 16.03it/s, loss=5485.1694]

SVI:  33%|███▎      | 33/100 [00:01<00:04, 16.03it/s, loss=6791.1206]

SVI:  34%|███▍      | 34/100 [00:01<00:04, 16.03it/s, loss=7056.2017]

SVI:  35%|███▌      | 35/100 [00:01<00:04, 16.03it/s, loss=4534.7944]

SVI:  36%|███▌      | 36/100 [00:01<00:03, 16.03it/s, loss=5913.8188]

SVI:  37%|███▋      | 37/100 [00:01<00:03, 16.03it/s, loss=5669.6831]

SVI:  38%|███▊      | 38/100 [00:01<00:01, 34.93it/s, loss=5669.6831]

SVI:  38%|███▊      | 38/100 [00:01<00:01, 34.93it/s, loss=3263.0325]

SVI:  39%|███▉      | 39/100 [00:01<00:01, 34.93it/s, loss=5944.4072]

SVI:  40%|████      | 40/100 [00:01<00:01, 34.93it/s, loss=7730.3169]

SVI:  41%|████      | 41/100 [00:01<00:01, 34.93it/s, loss=3615.7598]

SVI:  42%|████▏     | 42/100 [00:01<00:01, 34.93it/s, loss=5070.0654]

SVI:  43%|████▎     | 43/100 [00:01<00:01, 34.93it/s, loss=5306.9204]

SVI:  44%|████▍     | 44/100 [00:01<00:01, 34.93it/s, loss=5171.2168]

SVI:  45%|████▌     | 45/100 [00:01<00:01, 34.93it/s, loss=5584.1626]

SVI:  46%|████▌     | 46/100 [00:01<00:01, 34.93it/s, loss=3903.2842]

SVI:  47%|████▋     | 47/100 [00:01<00:01, 34.93it/s, loss=4275.4492]

SVI:  48%|████▊     | 48/100 [00:01<00:01, 34.93it/s, loss=7477.9048]

SVI:  49%|████▉     | 49/100 [00:01<00:01, 34.93it/s, loss=2795.0715]

SVI:  50%|█████     | 50/100 [00:01<00:01, 34.93it/s, loss=3936.6599]

SVI:  51%|█████     | 51/100 [00:01<00:01, 34.93it/s, loss=6107.5762]

SVI:  52%|█████▏    | 52/100 [00:01<00:01, 34.93it/s, loss=4401.1851]

SVI:  53%|█████▎    | 53/100 [00:01<00:01, 34.93it/s, loss=3258.8755]

SVI:  54%|█████▍    | 54/100 [00:01<00:01, 34.93it/s, loss=5060.7510]

SVI:  55%|█████▌    | 55/100 [00:01<00:01, 34.93it/s, loss=3486.4800]

SVI:  56%|█████▌    | 56/100 [00:01<00:01, 34.93it/s, loss=6825.7573]

SVI:  57%|█████▋    | 57/100 [00:01<00:01, 34.93it/s, loss=5610.7236]

SVI:  58%|█████▊    | 58/100 [00:01<00:00, 56.86it/s, loss=5610.7236]

SVI:  58%|█████▊    | 58/100 [00:01<00:00, 56.86it/s, loss=5999.8350]

SVI:  59%|█████▉    | 59/100 [00:01<00:00, 56.86it/s, loss=3436.7166]

SVI:  60%|██████    | 60/100 [00:01<00:00, 56.86it/s, loss=3631.2351]

SVI:  61%|██████    | 61/100 [00:01<00:00, 56.86it/s, loss=3149.8374]

SVI:  62%|██████▏   | 62/100 [00:01<00:00, 56.86it/s, loss=3566.1738]

SVI:  63%|██████▎   | 63/100 [00:01<00:00, 56.86it/s, loss=3056.6580]

SVI:  64%|██████▍   | 64/100 [00:01<00:00, 56.86it/s, loss=3610.0647]

SVI:  65%|██████▌   | 65/100 [00:01<00:00, 56.86it/s, loss=3463.4651]

SVI:  66%|██████▌   | 66/100 [00:01<00:00, 56.86it/s, loss=4774.1675]

SVI:  67%|██████▋   | 67/100 [00:01<00:00, 56.86it/s, loss=4024.2449]

SVI:  68%|██████▊   | 68/100 [00:01<00:00, 56.86it/s, loss=5415.6226]

SVI:  69%|██████▉   | 69/100 [00:01<00:00, 56.86it/s, loss=6677.7681]

SVI:  70%|███████   | 70/100 [00:01<00:00, 56.86it/s, loss=7889.2646]

SVI:  71%|███████   | 71/100 [00:01<00:00, 56.86it/s, loss=5668.4712]

SVI:  72%|███████▏  | 72/100 [00:01<00:00, 56.86it/s, loss=3631.0127]

SVI:  73%|███████▎  | 73/100 [00:01<00:00, 56.86it/s, loss=3245.1357]

SVI:  74%|███████▍  | 74/100 [00:01<00:00, 56.86it/s, loss=3577.8098]

SVI:  75%|███████▌  | 75/100 [00:01<00:00, 56.86it/s, loss=4525.8877]

SVI:  76%|███████▌  | 76/100 [00:01<00:00, 56.86it/s, loss=3745.0647]

SVI:  77%|███████▋  | 77/100 [00:01<00:00, 77.73it/s, loss=3745.0647]

SVI:  77%|███████▋  | 77/100 [00:01<00:00, 77.73it/s, loss=3539.1250]

SVI:  78%|███████▊  | 78/100 [00:01<00:00, 77.73it/s, loss=3571.4878]

SVI:  79%|███████▉  | 79/100 [00:01<00:00, 77.73it/s, loss=3550.8823]

SVI:  80%|████████  | 80/100 [00:01<00:00, 77.73it/s, loss=2818.4231]

SVI:  81%|████████  | 81/100 [00:01<00:00, 77.73it/s, loss=4873.9336]

SVI:  82%|████████▏ | 82/100 [00:01<00:00, 77.73it/s, loss=3748.8821]

SVI:  83%|████████▎ | 83/100 [00:01<00:00, 77.73it/s, loss=6004.3989]

SVI:  84%|████████▍ | 84/100 [00:01<00:00, 77.73it/s, loss=3001.2104]

SVI:  85%|████████▌ | 85/100 [00:01<00:00, 77.73it/s, loss=3321.3743]

SVI:  86%|████████▌ | 86/100 [00:01<00:00, 77.73it/s, loss=2508.1284]

SVI:  87%|████████▋ | 87/100 [00:01<00:00, 77.73it/s, loss=4446.5850]

SVI:  88%|████████▊ | 88/100 [00:02<00:00, 77.73it/s, loss=2473.4529]

SVI:  89%|████████▉ | 89/100 [00:02<00:00, 77.73it/s, loss=3247.5183]

SVI:  90%|█████████ | 90/100 [00:02<00:00, 77.73it/s, loss=2493.2444]

SVI:  91%|█████████ | 91/100 [00:02<00:00, 77.73it/s, loss=3830.4397]

SVI:  92%|█████████▏| 92/100 [00:02<00:00, 77.73it/s, loss=2693.7036]

SVI:  93%|█████████▎| 93/100 [00:02<00:00, 77.73it/s, loss=3804.4404]

SVI:  94%|█████████▍| 94/100 [00:02<00:00, 92.37it/s, loss=3804.4404]

SVI:  94%|█████████▍| 94/100 [00:02<00:00, 92.37it/s, loss=3220.2358]

SVI:  95%|█████████▌| 95/100 [00:02<00:00, 92.37it/s, loss=4321.9927]

SVI:  96%|█████████▌| 96/100 [00:02<00:00, 92.37it/s, loss=3511.4224]

SVI:  97%|█████████▋| 97/100 [00:02<00:00, 92.37it/s, loss=3951.1001]

SVI:  98%|█████████▊| 98/100 [00:02<00:00, 92.37it/s, loss=3343.0703]

SVI:  99%|█████████▉| 99/100 [00:02<00:00, 92.37it/s, loss=3327.0320]

SVI: 100%|██████████| 100/100 [00:02<00:00, 92.37it/s, loss=2855.4661]

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:01<02:27,  1.49s/it]

SVI:   1%|          | 1/100 [00:01<02:27,  1.49s/it, loss=11980.1426]

SVI:   2%|▏         | 2/100 [00:01<02:26,  1.49s/it, loss=6871.1694]

SVI:   3%|▎         | 3/100 [00:01<02:24,  1.49s/it, loss=10264.8047]

SVI:   4%|▍         | 4/100 [00:01<02:23,  1.49s/it, loss=10911.0322]

SVI:   5%|▌         | 5/100 [00:01<02:21,  1.49s/it, loss=7503.5552]

SVI:   6%|▌         | 6/100 [00:01<02:20,  1.49s/it, loss=10691.5645]

SVI:   7%|▋         | 7/100 [00:01<02:18,  1.49s/it, loss=11901.5684]

SVI:   8%|▊         | 8/100 [00:01<02:17,  1.49s/it, loss=8032.4160]

SVI:   9%|▉         | 9/100 [00:01<02:15,  1.49s/it, loss=6225.4854]

SVI:  10%|█         | 10/100 [00:01<02:14,  1.49s/it, loss=6295.6660]

SVI:  11%|█         | 11/100 [00:01<02:12,  1.49s/it, loss=5617.4351]

SVI:  12%|█▏        | 12/100 [00:01<02:11,  1.49s/it, loss=8791.6387]

SVI:  13%|█▎        | 13/100 [00:01<02:09,  1.49s/it, loss=7048.0156]

SVI:  14%|█▍        | 14/100 [00:01<02:08,  1.49s/it, loss=8971.8828]

SVI:  15%|█▌        | 15/100 [00:01<02:06,  1.49s/it, loss=4892.3257]

SVI:  16%|█▌        | 16/100 [00:01<02:05,  1.49s/it, loss=6427.0586]

SVI:  17%|█▋        | 17/100 [00:01<02:03,  1.49s/it, loss=8674.0957]

SVI:  18%|█▊        | 18/100 [00:01<02:02,  1.49s/it, loss=5819.0303]

SVI:  19%|█▉        | 19/100 [00:01<00:04, 16.30it/s, loss=5819.0303]

SVI:  19%|█▉        | 19/100 [00:01<00:04, 16.30it/s, loss=9402.3340]

SVI:  20%|██        | 20/100 [00:01<00:04, 16.30it/s, loss=4866.5098]

SVI:  21%|██        | 21/100 [00:01<00:04, 16.30it/s, loss=4140.9707]

SVI:  22%|██▏       | 22/100 [00:01<00:04, 16.30it/s, loss=6265.1055]

SVI:  23%|██▎       | 23/100 [00:01<00:04, 16.30it/s, loss=9930.1670]

SVI:  24%|██▍       | 24/100 [00:01<00:04, 16.30it/s, loss=9761.9512]

SVI:  25%|██▌       | 25/100 [00:01<00:04, 16.30it/s, loss=7118.2739]

SVI:  26%|██▌       | 26/100 [00:01<00:04, 16.30it/s, loss=6346.3252]

SVI:  27%|██▋       | 27/100 [00:01<00:04, 16.30it/s, loss=5932.1548]

SVI:  28%|██▊       | 28/100 [00:01<00:04, 16.30it/s, loss=6619.8423]

SVI:  29%|██▉       | 29/100 [00:01<00:04, 16.30it/s, loss=6820.8169]

SVI:  30%|███       | 30/100 [00:01<00:04, 16.30it/s, loss=3926.8230]

SVI:  31%|███       | 31/100 [00:01<00:04, 16.30it/s, loss=4852.2817]

SVI:  32%|███▏      | 32/100 [00:01<00:04, 16.30it/s, loss=4309.8887]

SVI:  33%|███▎      | 33/100 [00:01<00:04, 16.30it/s, loss=5224.7480]

SVI:  34%|███▍      | 34/100 [00:01<00:04, 16.30it/s, loss=3966.0242]

SVI:  35%|███▌      | 35/100 [00:01<00:03, 16.30it/s, loss=4826.8467]

SVI:  36%|███▌      | 36/100 [00:01<00:03, 16.30it/s, loss=8198.8594]

SVI:  37%|███▋      | 37/100 [00:01<00:01, 34.40it/s, loss=8198.8594]

SVI:  37%|███▋      | 37/100 [00:01<00:01, 34.40it/s, loss=5631.0342]

SVI:  38%|███▊      | 38/100 [00:01<00:01, 34.40it/s, loss=5083.9731]

SVI:  39%|███▉      | 39/100 [00:01<00:01, 34.40it/s, loss=4516.3540]

SVI:  40%|████      | 40/100 [00:01<00:01, 34.40it/s, loss=7369.5352]

SVI:  41%|████      | 41/100 [00:01<00:01, 34.40it/s, loss=2547.3093]

SVI:  42%|████▏     | 42/100 [00:01<00:01, 34.40it/s, loss=3429.6763]

SVI:  43%|████▎     | 43/100 [00:01<00:01, 34.40it/s, loss=3153.4595]

SVI:  44%|████▍     | 44/100 [00:01<00:01, 34.40it/s, loss=3234.2400]

SVI:  45%|████▌     | 45/100 [00:01<00:01, 34.40it/s, loss=4581.5181]

SVI:  46%|████▌     | 46/100 [00:01<00:01, 34.40it/s, loss=4051.3630]

SVI:  47%|████▋     | 47/100 [00:01<00:01, 34.40it/s, loss=2217.6648]

SVI:  48%|████▊     | 48/100 [00:01<00:01, 34.40it/s, loss=3730.6589]

SVI:  49%|████▉     | 49/100 [00:01<00:01, 34.40it/s, loss=7231.1226]

SVI:  50%|█████     | 50/100 [00:01<00:01, 34.40it/s, loss=4115.2734]

SVI:  51%|█████     | 51/100 [00:01<00:01, 34.40it/s, loss=5421.7031]

SVI:  52%|█████▏    | 52/100 [00:01<00:01, 34.40it/s, loss=3475.1448]

SVI:  53%|█████▎    | 53/100 [00:01<00:01, 34.40it/s, loss=4039.7324]

SVI:  54%|█████▍    | 54/100 [00:01<00:01, 34.40it/s, loss=2738.5981]

SVI:  55%|█████▌    | 55/100 [00:01<00:00, 54.21it/s, loss=2738.5981]

SVI:  55%|█████▌    | 55/100 [00:01<00:00, 54.21it/s, loss=4965.5146]

SVI:  56%|█████▌    | 56/100 [00:01<00:00, 54.21it/s, loss=3607.3496]

SVI:  57%|█████▋    | 57/100 [00:01<00:00, 54.21it/s, loss=3476.8501]

SVI:  58%|█████▊    | 58/100 [00:01<00:00, 54.21it/s, loss=2800.3877]

SVI:  59%|█████▉    | 59/100 [00:01<00:00, 54.21it/s, loss=3755.0825]

SVI:  60%|██████    | 60/100 [00:01<00:00, 54.21it/s, loss=4531.2744]

SVI:  61%|██████    | 61/100 [00:01<00:00, 54.21it/s, loss=3145.4292]

SVI:  62%|██████▏   | 62/100 [00:01<00:00, 54.21it/s, loss=2999.9470]

SVI:  63%|██████▎   | 63/100 [00:01<00:00, 54.21it/s, loss=4848.9258]

SVI:  64%|██████▍   | 64/100 [00:01<00:00, 54.21it/s, loss=2405.1575]

SVI:  65%|██████▌   | 65/100 [00:01<00:00, 54.21it/s, loss=3255.5066]

SVI:  66%|██████▌   | 66/100 [00:01<00:00, 54.21it/s, loss=7194.0522]

SVI:  67%|██████▋   | 67/100 [00:01<00:00, 54.21it/s, loss=3055.5481]

SVI:  68%|██████▊   | 68/100 [00:01<00:00, 54.21it/s, loss=2720.9150]

SVI:  69%|██████▉   | 69/100 [00:01<00:00, 54.21it/s, loss=3445.8738]

SVI:  70%|███████   | 70/100 [00:01<00:00, 54.21it/s, loss=2909.8232]

SVI:  71%|███████   | 71/100 [00:01<00:00, 54.21it/s, loss=3796.2896]

SVI:  72%|███████▏  | 72/100 [00:01<00:00, 54.21it/s, loss=3229.8032]

SVI:  73%|███████▎  | 73/100 [00:01<00:00, 54.21it/s, loss=3062.8982]

SVI:  74%|███████▍  | 74/100 [00:01<00:00, 75.72it/s, loss=3062.8982]

SVI:  74%|███████▍  | 74/100 [00:01<00:00, 75.72it/s, loss=3203.7144]

SVI:  75%|███████▌  | 75/100 [00:01<00:00, 75.72it/s, loss=3382.0264]

SVI:  76%|███████▌  | 76/100 [00:01<00:00, 75.72it/s, loss=3002.9490]

SVI:  77%|███████▋  | 77/100 [00:01<00:00, 75.72it/s, loss=3532.8452]

SVI:  78%|███████▊  | 78/100 [00:01<00:00, 75.72it/s, loss=2564.5999]

SVI:  79%|███████▉  | 79/100 [00:01<00:00, 75.72it/s, loss=5391.0103]

SVI:  80%|████████  | 80/100 [00:01<00:00, 75.72it/s, loss=3088.0872]

SVI:  81%|████████  | 81/100 [00:01<00:00, 75.72it/s, loss=2752.2922]

SVI:  82%|████████▏ | 82/100 [00:01<00:00, 75.72it/s, loss=3021.4277]

SVI:  83%|████████▎ | 83/100 [00:01<00:00, 75.72it/s, loss=2952.3982]

SVI:  84%|████████▍ | 84/100 [00:01<00:00, 75.72it/s, loss=2971.3147]

SVI:  85%|████████▌ | 85/100 [00:01<00:00, 75.72it/s, loss=3720.1917]

SVI:  86%|████████▌ | 86/100 [00:01<00:00, 75.72it/s, loss=4002.2458]

SVI:  87%|████████▋ | 87/100 [00:01<00:00, 75.72it/s, loss=2986.2307]

SVI:  88%|████████▊ | 88/100 [00:01<00:00, 75.72it/s, loss=2001.3853]

SVI:  89%|████████▉ | 89/100 [00:01<00:00, 75.72it/s, loss=3653.2395]

SVI:  90%|█████████ | 90/100 [00:01<00:00, 75.72it/s, loss=2997.0864]

SVI:  91%|█████████ | 91/100 [00:01<00:00, 75.72it/s, loss=2089.1143]

SVI:  92%|█████████▏| 92/100 [00:01<00:00, 75.72it/s, loss=3921.1675]

SVI:  93%|█████████▎| 93/100 [00:02<00:00, 96.69it/s, loss=3921.1675]

SVI:  93%|█████████▎| 93/100 [00:02<00:00, 96.69it/s, loss=2432.1777]

SVI:  94%|█████████▍| 94/100 [00:02<00:00, 96.69it/s, loss=2699.0630]

SVI:  95%|█████████▌| 95/100 [00:02<00:00, 96.69it/s, loss=3264.6458]

SVI:  96%|█████████▌| 96/100 [00:02<00:00, 96.69it/s, loss=2679.6926]

SVI:  97%|█████████▋| 97/100 [00:02<00:00, 96.69it/s, loss=2336.6248]

SVI:  98%|█████████▊| 98/100 [00:02<00:00, 96.69it/s, loss=3075.5613]

SVI:  99%|█████████▉| 99/100 [00:02<00:00, 96.69it/s, loss=2948.1362]

SVI: 100%|██████████| 100/100 [00:02<00:00, 96.69it/s, loss=3410.2776]

SVI:   0%|          | 0/100 [00:00<?, ?it/s]

SVI:   1%|          | 1/100 [00:01<02:26,  1.48s/it]

SVI:   1%|          | 1/100 [00:01<02:26,  1.48s/it, loss=14958.8809]

SVI:   2%|▏         | 2/100 [00:01<02:24,  1.48s/it, loss=6539.2500]

SVI:   3%|▎         | 3/100 [00:01<02:23,  1.48s/it, loss=9058.1904]

SVI:   4%|▍         | 4/100 [00:01<02:21,  1.48s/it, loss=10696.7061]

SVI:   5%|▌         | 5/100 [00:01<02:20,  1.48s/it, loss=17029.4570]

SVI:   6%|▌         | 6/100 [00:01<02:18,  1.48s/it, loss=9314.9404]

SVI:   7%|▋         | 7/100 [00:01<02:17,  1.48s/it, loss=11382.8506]

SVI:   8%|▊         | 8/100 [00:01<02:15,  1.48s/it, loss=9285.4453]

SVI:   9%|▉         | 9/100 [00:01<02:14,  1.48s/it, loss=11339.8047]

SVI:  10%|█         | 10/100 [00:01<02:12,  1.48s/it, loss=10355.8623]

SVI:  11%|█         | 11/100 [00:01<02:11,  1.48s/it, loss=13382.7529]

SVI:  12%|█▏        | 12/100 [00:01<02:09,  1.48s/it, loss=10835.1357]

SVI:  13%|█▎        | 13/100 [00:01<02:08,  1.48s/it, loss=10493.1484]

SVI:  14%|█▍        | 14/100 [00:01<02:07,  1.48s/it, loss=8239.1592]

SVI:  15%|█▌        | 15/100 [00:01<02:05,  1.48s/it, loss=7195.2827]

SVI:  16%|█▌        | 16/100 [00:01<02:04,  1.48s/it, loss=6670.5239]

SVI:  17%|█▋        | 17/100 [00:01<02:02,  1.48s/it, loss=11699.2832]

SVI:  18%|█▊        | 18/100 [00:01<02:01,  1.48s/it, loss=5452.9893]

SVI:  19%|█▉        | 19/100 [00:01<01:59,  1.48s/it, loss=11785.2422]

SVI:  20%|██        | 20/100 [00:01<00:04, 17.33it/s, loss=11785.2422]

SVI:  20%|██        | 20/100 [00:01<00:04, 17.33it/s, loss=10834.9756]

SVI:  21%|██        | 21/100 [00:01<00:04, 17.33it/s, loss=4605.2383]

SVI:  22%|██▏       | 22/100 [00:01<00:04, 17.33it/s, loss=5113.2529]

SVI:  23%|██▎       | 23/100 [00:01<00:04, 17.33it/s, loss=7634.6934]

SVI:  24%|██▍       | 24/100 [00:01<00:04, 17.33it/s, loss=4207.6870]

SVI:  25%|██▌       | 25/100 [00:01<00:04, 17.33it/s, loss=8016.6929]

SVI:  26%|██▌       | 26/100 [00:01<00:04, 17.33it/s, loss=4123.1870]

SVI:  27%|██▋       | 27/100 [00:01<00:04, 17.33it/s, loss=7712.4590]

SVI:  28%|██▊       | 28/100 [00:01<00:04, 17.33it/s, loss=8421.0986]

SVI:  29%|██▉       | 29/100 [00:01<00:04, 17.33it/s, loss=7348.7944]

SVI:  30%|███       | 30/100 [00:01<00:04, 17.33it/s, loss=8823.9980]

SVI:  31%|███       | 31/100 [00:01<00:03, 17.33it/s, loss=7360.9229]

SVI:  32%|███▏      | 32/100 [00:01<00:03, 17.33it/s, loss=5923.6621]

SVI:  33%|███▎      | 33/100 [00:01<00:03, 17.33it/s, loss=3787.3210]

SVI:  34%|███▍      | 34/100 [00:01<00:03, 17.33it/s, loss=7078.8535]

SVI:  35%|███▌      | 35/100 [00:01<00:03, 17.33it/s, loss=7472.8726]

SVI:  36%|███▌      | 36/100 [00:01<00:03, 17.33it/s, loss=6730.4302]

SVI:  37%|███▋      | 37/100 [00:01<00:03, 17.33it/s, loss=7541.6846]

SVI:  38%|███▊      | 38/100 [00:01<00:03, 17.33it/s, loss=9263.0684]

SVI:  39%|███▉      | 39/100 [00:01<00:01, 36.51it/s, loss=9263.0684]

SVI:  39%|███▉      | 39/100 [00:01<00:01, 36.51it/s, loss=8562.3662]

SVI:  40%|████      | 40/100 [00:01<00:01, 36.51it/s, loss=7601.5522]

SVI:  41%|████      | 41/100 [00:01<00:01, 36.51it/s, loss=6151.0303]

SVI:  42%|████▏     | 42/100 [00:01<00:01, 36.51it/s, loss=3541.9468]

SVI:  43%|████▎     | 43/100 [00:01<00:01, 36.51it/s, loss=4119.2217]

SVI:  44%|████▍     | 44/100 [00:01<00:01, 36.51it/s, loss=8000.6162]

SVI:  45%|████▌     | 45/100 [00:01<00:01, 36.51it/s, loss=5550.2783]

SVI:  46%|████▌     | 46/100 [00:01<00:01, 36.51it/s, loss=4956.8413]

SVI:  47%|████▋     | 47/100 [00:01<00:01, 36.51it/s, loss=4645.2622]

SVI:  48%|████▊     | 48/100 [00:01<00:01, 36.51it/s, loss=4092.4084]

SVI:  49%|████▉     | 49/100 [00:01<00:01, 36.51it/s, loss=5054.2593]

SVI:  50%|█████     | 50/100 [00:01<00:01, 36.51it/s, loss=5090.0166]

SVI:  51%|█████     | 51/100 [00:01<00:01, 36.51it/s, loss=2722.6777]

SVI:  52%|█████▏    | 52/100 [00:01<00:01, 36.51it/s, loss=6841.9458]

SVI:  53%|█████▎    | 53/100 [00:01<00:01, 36.51it/s, loss=4620.3252]

SVI:  54%|█████▍    | 54/100 [00:01<00:01, 36.51it/s, loss=3421.4702]

SVI:  55%|█████▌    | 55/100 [00:01<00:01, 36.51it/s, loss=8002.5132]

SVI:  56%|█████▌    | 56/100 [00:01<00:01, 36.51it/s, loss=6136.5361]

SVI:  57%|█████▋    | 57/100 [00:01<00:01, 36.51it/s, loss=2483.4346]

SVI:  58%|█████▊    | 58/100 [00:01<00:00, 57.43it/s, loss=2483.4346]

SVI:  58%|█████▊    | 58/100 [00:01<00:00, 57.43it/s, loss=5998.2290]

SVI:  59%|█████▉    | 59/100 [00:01<00:00, 57.43it/s, loss=5251.8091]

SVI:  60%|██████    | 60/100 [00:01<00:00, 57.43it/s, loss=3896.3765]

SVI:  61%|██████    | 61/100 [00:01<00:00, 57.43it/s, loss=4839.1064]

SVI:  62%|██████▏   | 62/100 [00:01<00:00, 57.43it/s, loss=2693.8914]

SVI:  63%|██████▎   | 63/100 [00:01<00:00, 57.43it/s, loss=3905.8198]

SVI:  64%|██████▍   | 64/100 [00:01<00:00, 57.43it/s, loss=5209.4473]

SVI:  65%|██████▌   | 65/100 [00:01<00:00, 57.43it/s, loss=3821.0469]

SVI:  66%|██████▌   | 66/100 [00:01<00:00, 57.43it/s, loss=3665.2991]

SVI:  67%|██████▋   | 67/100 [00:01<00:00, 57.43it/s, loss=6682.8096]

SVI:  68%|██████▊   | 68/100 [00:01<00:00, 57.43it/s, loss=3191.2705]

SVI:  69%|██████▉   | 69/100 [00:01<00:00, 57.43it/s, loss=2514.9084]

SVI:  70%|███████   | 70/100 [00:01<00:00, 57.43it/s, loss=2775.0388]

SVI:  71%|███████   | 71/100 [00:01<00:00, 57.43it/s, loss=3789.3367]

SVI:  72%|███████▏  | 72/100 [00:01<00:00, 57.43it/s, loss=3108.1646]

SVI:  73%|███████▎  | 73/100 [00:01<00:00, 57.43it/s, loss=2616.5994]

SVI:  74%|███████▍  | 74/100 [00:01<00:00, 57.43it/s, loss=3382.1570]

SVI:  75%|███████▌  | 75/100 [00:01<00:00, 57.43it/s, loss=2619.1265]

SVI:  76%|███████▌  | 76/100 [00:01<00:00, 57.43it/s, loss=2471.2520]

SVI:  77%|███████▋  | 77/100 [00:01<00:00, 57.43it/s, loss=3444.3074]

SVI:  78%|███████▊  | 78/100 [00:01<00:00, 80.15it/s, loss=3444.3074]

SVI:  78%|███████▊  | 78/100 [00:01<00:00, 80.15it/s, loss=3738.9766]

SVI:  79%|███████▉  | 79/100 [00:01<00:00, 80.15it/s, loss=4160.1235]

SVI:  80%|████████  | 80/100 [00:01<00:00, 80.15it/s, loss=3305.5972]

SVI:  81%|████████  | 81/100 [00:01<00:00, 80.15it/s, loss=2923.5083]

SVI:  82%|████████▏ | 82/100 [00:01<00:00, 80.15it/s, loss=6237.8330]

SVI:  83%|████████▎ | 83/100 [00:01<00:00, 80.15it/s, loss=2460.4341]

SVI:  84%|████████▍ | 84/100 [00:01<00:00, 80.15it/s, loss=2280.0076]

SVI:  85%|████████▌ | 85/100 [00:01<00:00, 80.15it/s, loss=2819.7788]

SVI:  86%|████████▌ | 86/100 [00:01<00:00, 80.15it/s, loss=3935.9795]

SVI:  87%|████████▋ | 87/100 [00:01<00:00, 80.15it/s, loss=4769.4624]

SVI:  88%|████████▊ | 88/100 [00:01<00:00, 80.15it/s, loss=4740.4126]

SVI:  89%|████████▉ | 89/100 [00:01<00:00, 80.15it/s, loss=3249.4646]

SVI:  90%|█████████ | 90/100 [00:01<00:00, 80.15it/s, loss=3731.2715]

SVI:  91%|█████████ | 91/100 [00:01<00:00, 80.15it/s, loss=3393.9097]

SVI:  92%|█████████▏| 92/100 [00:01<00:00, 80.15it/s, loss=3059.9758]

SVI:  93%|█████████▎| 93/100 [00:01<00:00, 80.15it/s, loss=2059.8901]

SVI:  94%|█████████▍| 94/100 [00:01<00:00, 80.15it/s, loss=3298.4062]

SVI:  95%|█████████▌| 95/100 [00:01<00:00, 80.15it/s, loss=3426.0286]

SVI:  96%|█████████▌| 96/100 [00:01<00:00, 80.15it/s, loss=3512.9543]

SVI:  97%|█████████▋| 97/100 [00:01<00:00, 100.48it/s, loss=3512.9543]

SVI:  97%|█████████▋| 97/100 [00:01<00:00, 100.48it/s, loss=4119.6270]

SVI:  98%|█████████▊| 98/100 [00:01<00:00, 100.48it/s, loss=2816.8342]

SVI:  99%|█████████▉| 99/100 [00:02<00:00, 100.48it/s, loss=4292.0000]

SVI: 100%|██████████| 100/100 [00:02<00:00, 100.48it/s, loss=4040.2258]

Explored and updated on 4096 offers. Avg regret: 0.5854. Arm counts: {'price_down': 1357, 'price_same': 1365, 'price_up': 1374}

### Inspect the learned price + mix

Rebuild with `epsilon=0` to exploit the trained arms. For each test customer the bandit now returns a **price arm** and a portion mix; it should lean toward the price level nearest the customer's ideal price and a mix near their ideal portions.

In [10]:
cmab_multi = CmabBernoulli(actions=actions_multi, epsilon=0)  # exploit the trained arms
pred_actions, _, _ = cmab_multi.predict(context=test_contexts, forbidden_actions=forbidden_actions_multi)

rows = []
for ctx, (arm, quantity) in zip(test_contexts, pred_actions):
    portions = portions_from(quantity)
    ideal_portions, ideal_price = make_ideal(ctx)
    rows.append(
        {
            "context": np.round(ctx, 2),
            "chosen_price_arm": arm,
            "chosen_price": PRICE_LEVELS[arm],
            "chosen_portions": np.round(portions, 3),
            "portion_sum": round(float(portions.sum()), 6),
            "ideal_portions": np.round(ideal_portions, 3),
            "ideal_price": round(float(ideal_price), 3),
        }
    )

pd.DataFrame(rows)

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py:552: UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  self.H.update(delta_x, delta_g)

,context,chosen_price_arm,chosen_price,chosen_portions,portion_sum,ideal_portions,ideal_price
0,"[0.9, 0.9, 0.1]",price_same,0.50,"[1.0, 0.0, 0.0]",1.0,"[0.556, 0.111, 0.333]",0.74
1,"[0.9, 0.1, 0.9]",price_up,0.55,"[0.0, 1.0, 0.0]",1.0,"[0.111, 0.556, 0.333]",0.74
2,"[0.2, 0.4, 0.4]",price_down,0.45,"[0.094, 0.906, 0.0]",1.0,"[0.294, 0.294, 0.412]",0.32
3,"[0.5, 0.1, 0.1]",price_same,0.50,"[1.0, 0.0, 0.0]",1.0,"[0.143, 0.143, 0.714]",0.50

## Conclusion

We used a contextual bandit with a BNN quantitative model to choose **both** the item mix **and** the price of an offer, conditioned on customer context — a fully continuous, multi-dimensional decision learned from binary purchase feedback.

The key idea for the `sum(portions) == 1` requirement:

> **Optimize the portions directly and reduce the equality to one inequality.** The first `N_ITEMS - 1` coordinates are the actual portions (so the BNN learns in un-warped portion space), the last portion is the leftover, and `p_1 + p_2 <= 1` is enforced as a forbidden region — a full-measure triangle, far friendlier than a measure-zero equality.

Contrast with the alternatives: an exact equality on `[p_1, p_2, p_3]` gives the optimizer a measure-zero feasible set and the model a redundant input; a stick-breaking encoding is always valid but warps the space and privileges one item. Reach for the forbidden-region / `constraint=` callables whenever feasibility is a genuine **inequality** ("price must exceed cost", "item 1 below 0.5"); reduce a structural equality to the smallest inequality you can, as we did here.

And when a dimension is **discrete** rather than continuous (a fixed set of prices, tiers, or templates), don't force it into the quantity vector — model it as **separate quantitative arms**, one per level, and let the bandit choose the level while each arm optimizes the continuous remainder, as in the discrete-price example above.